### ISSUE TITLE
Cannot build 7.2.2 with CUDA 11.2

### ISSUE THREAD

**Issue by Maik93** [NVIDIA/TensorRT#1064]
## Description

Even if the [download link](https://developer.nvidia.com/nvidia-tensorrt-7x-download) explicitly states that v7.2.2 can be compiled with CUDA 11.2, doing so throws a linker error that seems related to closed source libraries built explicitly with CUDA 11.1:
```
/usr/bin/ld: TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcDestroyProgram@libnvrtc.so.11.1'
/usr/bin/ld: TensorRT-7.2.2.3/lib/libnvinfer_plugin.so: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.11.1'
[...]
```

Is there any way to compile tensorrt with 11.2 or the download link is just misleading?

## Environment

**TensorRT Version**: 7.2.2
**NVIDIA GPU**: GTX 1060
**NVIDIA Driver Version**: 460.32.03
**CUDA Version**: 11.2
**CUDNN Version**: 8.1.0.77-1
**Operating System**: Archlinux

**Comment by ttyio** [comment]
Hello @Maik93 , thanks for reporting.
This is limitation of nvrtc library. Could you try install nvrtc for cuda 11.1?

see https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html

    Note: If you are developing an application that is being compiled with CUDA 11.2 or you are using CUDA 11.2 libraries to run your application, then you must install CUDA 11.1 using either the Debian/RPM packages or using a CUDA 11.1 tar/zip/exe package. NVRTC from CUDA 11.1 is a runtime requirement of TensorRT and must be present to run TensorRT applications. If you are using the network repo installation method, this additional step is not needed.

**Comment by Maik93** [comment]
Hello @ttyio, thanks for your assistance.
AFAIK nvrtc is contained in the CUDA toolkit ([installation guide](https://docs.nvidia.com/cuda/nvrtc/index.html#installation)) and can be only installed together with the CUDA package itself. Are you suggesting to reinstall CUDA?
In that case, should I install CUDA 11.1 in place of 11.2 or alongside it?

**Comment by ttyio** [comment]
Hello @Maik93 ,
Yes nvrtc is deliver inside the CUDA toolkit, you can also install it separate, I find the links in:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-11-1_11.1.105-1_amd64.deb
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-dev-11-1_11.1.105-1_amd64.deb
Could you take a try?

**Comment by Maik93** [comment]
Sorry, I'm on Arch and it took me some time to repack those two deb files due to conflicts.
I've achieved it now and I can confirm that everything works: I was able to compile TensorRT with CUDA 11.2 with just nvrtc 11.1 as additional dependency! Thank you!!

----

If someone is interested and if you are ok with it, I can submit to the AUR those two deb file converted for Archlinux. In this case, I probably need to know under what licence they are supposed to be shared.

**Comment by ttyio** [comment]
Thanks @Maik93  for the update.
BTW, nvrtc team is working on the improvement on the compatibility between minor versions, and we will no longer hit such problem when this feature is done in nvrtc library.

**Comment by DavorJordacevic** [comment]
> Hello @Maik93 ,
> Yes nvrtc is deliver inside the CUDA toolkit, you can also install it separate, I find the links in:
> https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-11-1_11.1.105-1_amd64.deb
> https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-dev-11-1_11.1.105-1_amd64.deb
> Could you take a try?

I was able to compile TensorRT with CUDA 11.2 and nvrtc 11.1! Thank you!

**Comment by Maik93** [comment]
@jinfagang try a `sudo find / -name libnvrtc.so.11.1` and check if it is in a correct path.
For me (on Archlinux), it is in `/opt/cuda/targets/x86_64-linux/lib/`, but I don't know if it should be there even on Ubuntu.
If it is on a different directory, try to add it to the environmental variable `LD_LIBRARY_PATH`.

**Comment by jinfagang** [comment]
@Maik93 It is correct since I am in standared ubuntu 18.04 and standared way installed cuda11.2. Now I try reinstall CUDA......

**Comment by lonngxiang** [comment]
install nvrtc 11.1 still not work@Maik93
![image](https://user-images.githubusercontent.com/40717349/131429528-2c68b6d1-a6d6-47ee-91a0-925afd3a42d5.png)
![image](https://user-images.githubusercontent.com/40717349/131429527-0d58426d-456b-4952-844b-823af222ac24.png)

**Comment by zengjie617789** [comment]
my error is solved when i check the system version which should match the version of tensorrt download.
and everthing is fine. 
I used the way of tar file installation on Ubuntun16.04 , Tensort7.0.0, cuda10.1, cudnn7.6.5

**Comment by Darwin84** [comment]
get same problem

**Comment by kulkarnivishal** [comment]
> Sorry, I'm on Arch and it took me some time to repack those two deb files due to conflicts. I've achieved it now and I can confirm that everything works: I was able to compile TensorRT with CUDA 11.2 with just nvrtc 11.1 as additional dependency! Thank you!!
> 
> If someone is interested and if you are ok with it, I can submit to the AUR those two deb file converted for Archlinux. In this case, I probably need to know under what licence they are supposed to be shared.

Hi @Maik93 could you list the steps if possible, please? 
is it possible to just install nvrtc 11.1 in a 11.2 container?

I tried adding path to libnvrtc.so.11.1 to LD_LIBRARY_PATH but I still get unmet dependencies when installing trt 7.2.2 
```
The following packages have unmet dependencies:
 libnvinfer-dev : Depends: libcublas.so.11-dev but it is not installable or
                           libcublas-dev-11-1 but it is not installable
 libnvinfer7 : Depends: libcublas.so.11 but it is not installable or
                        libcublas-11-1 but it is not installable
```

**Comment by Shuolongbj** [comment]
> @Maik93 I installed this two deb, it still got this:
> 
> ```
> /home//TensorRT/lib/libnvinfer.so: undefined reference to `nvrtcCompileProgram@libnvrtc.so.11.1'
> /home//TensorRT/lib/libnvinfer.so: undefined reference to `nvrtcVersion@libnvrtc.so.11.1'
> /home//TensorRT/lib/libnvinfer.so: undefined reference to `nvrtcGetPTX@libnvrtc.so.11.1'
> /home//TensorRT/lib/libnvinfer.so: undefined reference to `nvrtcDestroyProgram@libnvrtc.so.11.1'
> /home//TensorRT/lib/libnvinfer.so: undefined reference to `nvrtcGetPTXSize@libnvrtc.so.11.1'
> /home//TensorRT/lib/libnvinfer_plugin.so: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.11.1'
> /home//TensorRT/lib/libnvinfer.so: undefined reference to `nvrtcCreateProgram@libnvrtc.so.11.1'
> ```
> 
> Also tried `sudo ln -s 11.2 11.1` not work

**the same as to me**

P1:~/TensorRT-7.2.3.4/samples/sampleMNIST$ make -j18
../Makefile.config:10: CUDA_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDA_INSTALL_DIR=<cuda_directory> to change.
../Makefile.config:15: CUDNN_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDNN_INSTALL_DIR=<cudnn_directory> to change.
../Makefile.config:28: TRT_LIB_DIR is not specified, searching ../../lib, ../../lib, ../lib by default, use TRT_LIB_DIR=<trt_lib_directory> to change.
Linking: ../../bin/sample_mnist_debug
**/usr/bin/ld: warning: libnvrtc.so.11.1, needed by ../../lib/libnvinfer.so, not found (try using -rpath or -rpath-link)**
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcDestroyProgram@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libmyelin.so: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcCreateProgram@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcCompileProgram@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcGetPTX@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcVersion@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcGetProgramLog@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libmyelin.so: undefined reference to `nvrtcGetLoweredName@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcGetErrorString@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcGetProgramLogSize@libnvrtc.so.11.1'
/usr/bin/ld: ../../lib/libnvinfer.so: undefined reference to `nvrtcGetPTXSize@libnvrtc.so.11.1'
**collect2: error: ld returned 1 exit status
make: *** [../Makefile.config:309: ../../bin/sample_mnist_debug] Error 1**

**TensorRT Version: 7.2.3.4
CUDA Version: 11.2
CUDNN Version:  8.1.1.33-1
Operating System: Ubuntu-20.04**

$ **gcc -v**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

P1:~/TensorRT-7.2.3.4/samples/sampleMNIST$ **sudo dpkg -l | grep cudnn**
ii  libcudnn8                      8.1.1.33-1+cuda11.2                   amd64        cuDNN runtime libraries
ii  libcudnn8-dev                  8.1.1.33-1+cuda11.2                   amd64        cuDNN development libraries and headers

P1:~/TensorRT-7.2.3.4/samples/sampleMNIST$ **sudo dpkg -l | grep cuda**
ii  cuda-11-2                      11.2.2-1                              amd64        CUDA 11.2 meta-package
ii  cuda-command-line-tools-11-2   11.2.2-1                              amd64        CUDA command-line tools
ii  cuda-compiler-11-2             11.2.2-1                              amd64        CUDA compiler
ii  cuda-cudart-11-2               11.2.152-1                            amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-11-2           11.2.152-1                            amd64        CUDA Runtime native dev links, headers
ii  cuda-cuobjdump-11-2            11.2.152-1                            amd64        CUDA cuobjdump
ii  cuda-cupti-11-2                11.2.152-1                            amd64        CUDA profiling tools runtime libs.
ii  cuda-cupti-dev-11-2            11.2.152-1                            amd64        CUDA profiling tools interface.
ii  cuda-cuxxfilt-11-2             11.2.152-1                            amd64        CUDA cuxxfilt
ii  cuda-demo-suite-11-2           11.2.152-1                            amd64        Demo suite for CUDA
ii  cuda-documentation-11-2        11.2.154-1                            amd64        CUDA documentation
ii  cuda-driver-dev-11-2           11.2.152-1                            amd64        CUDA Driver native dev stub library
ii  cuda-gdb-11-2                  11.2.152-1                            amd64        CUDA-GDB
ii  cuda-libraries-11-2            11.2.2-1                              amd64        CUDA Libraries 11.2 meta-package
ii  cuda-libraries-dev-11-2        11.2.2-1                              amd64        CUDA Libraries 11.2 development meta-package
ii  cuda-memcheck-11-2             11.2.152-1                            amd64        CUDA-MEMCHECK
ii  cuda-nsight-11-2               11.2.152-1                            amd64        CUDA nsight
ii  cuda-nsight-compute-11-2       11.2.2-1                              amd64        NVIDIA Nsight Compute
ii  cuda-nsight-systems-11-2       11.2.2-1                              amd64        NVIDIA Nsight Systems
ii  cuda-nvcc-11-2                 11.2.152-1                            amd64        CUDA nvcc
ii  cuda-nvdisasm-11-2             11.2.152-1                            amd64        CUDA disassembler
ii  cuda-nvml-dev-11-2             11.2.152-1                            amd64        NVML native dev links, headers
ii  cuda-nvprof-11-2               11.2.152-1                            amd64        CUDA Profiler tools
ii  cuda-nvprune-11-2              11.2.152-1                            amd64        CUDA nvprune
ii  cuda-nvrtc-11-1                11.1.105-1                            amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-11-2                11.2.152-1                            amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-11-1            11.1.105-1                            amd64        NVRTC native dev links, headers
ii  cuda-nvrtc-dev-11-2            11.2.152-1                            amd64        NVRTC native dev links, headers
ii  cuda-nvtx-11-2                 11.2.152-1                            amd64        NVIDIA Tools Extension
ii  cuda-nvvp-11-2                 11.2.152-1                            amd64        CUDA Profiler tools
ii  cuda-runtime-11-2              11.2.2-1                              amd64        CUDA Runtime 11.2 meta-package
ii  cuda-samples-11-2              11.2.152-1                            amd64        CUDA example applications
ii  cuda-sanitizer-11-2            11.2.152-1                            amd64        CUDA Sanitizer
ii  cuda-toolkit-11-2              11.2.2-1                              amd64        CUDA Toolkit 11.2 meta-package
ii  cuda-tools-11-2                11.2.2-1                              amd64        CUDA Tools meta-package
ii  cuda-visual-tools-11-2         11.2.2-1                              amd64        CUDA visual tools
ii  libcudnn8                      8.1.1.33-1+cuda11.2                   amd64        cuDNN runtime libraries
ii  libcudnn8-dev                  8.1.1.33-1+cuda11.2                   amd64        cuDNN development libraries and headers

**Comment by Shuolongbj** [comment]
https://github.com/NVIDIA/TensorRT/issues/2884 FYI.

https://github.com/tensorflow/tensorflow/blob/master/.bazelrc
TensorRT 7 for CUDA 11.1 is compatible with CUDA 11.2, but requires
 libnvrtc.so.11.1. See https://github.com/NVIDIA/TensorRT/issues/1064.
TODO(b/187962120): Remove when upgrading to TensorRT 8.
test:rbe_linux_cuda_base --test_env=LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-11.1/lib64"

TensorRT Version: 7.2.3.4 CUDA Version: 11.2 CUDNN Version: 8.1.1.33-1 Operating System: Ubuntu-20.04

CUDA Version 11.2 **must be** [11.2 update 1](https://developer.nvidia.com/cuda-toolkit-archive),not 11.2 update 2

**Comment by Shuolongbj** [comment]
> Hello @Maik93 , Yes nvrtc is deliver inside the CUDA toolkit, you can also install it separate, I find the links in: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-11-1_11.1.105-1_amd64.deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-dev-11-1_11.1.105-1_amd64.deb Could you take a try?

nvrtc is deliver inside the CUDA toolkit, you can also install it separate, I find the links in:

#https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-11-1_11.1.105-1_amd64.deb
#https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-nvrtc-dev-11-1_11.1.105-1_amd64.deb

TensorRT Version: 7.2.3.4 CUDA Version: 11.2 CUDNN Version: 8.1.1.33-1
##ubuntu2004
https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64/cuda-nvrtc-11-1_11.1.105-1_amd64.deb
https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64/cuda-nvrtc-dev-11-1_11.1.105-1_amd64.deb

###ubuntu2204
https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2204/x86_64/cuda-nvrtc-11-1_11.1.105-1_amd64.deb https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2204/x86_64/cuda-nvrtc-dev-11-1_11.1.105-1_amd64.deb
