### ISSUE TITLE
do_inference by tensorrt7.0.0.11 pythonAPI, but get "Cuda Error in executeMemcpy"

### ISSUE THREAD

**Issue by y200504040u** [NVIDIA/TensorRT#1149]
I got the following error message when I do_inference by **tensorrt7.0.0.11 python API**
[TensorRT] ERROR: ../rtSafe/cuda/genericReformat.cu (1262) - Cuda Error in executeMemcpy: 1 (invalid argument)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
Traceback (most recent call last):
  File "onnx2trt/demo_trt.py", line 208, in <module>
    main()
  File "onnx2trt/demo_trt.py", line 197, in main
    demo.process_video(args.input_video_path)
  File "onnx2trt/demo_trt.py", line 136, in process_video
    context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream
  File "/onnx2trt/common.py", line 195, in **do_inference_v2**
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
  File "/onnx2trt/common.py", line 195, in <listcomp>
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
AttributeError: 'str' object has no attribute 'host'

My .trt weights file was converted from a onnx file. 
I did inference on an image sequence by **common.do_inference_v2**, it **ran correctly on the first image**, and the **output was correct**, but **collapsed on the second image**, and got the above error messages.
I'm not sure what mistakes I made.

**Environment:**
TensorRT Version: 7.0.0.11 Python API
GPU Type: 2080ti
CUDA Version: 10.1
CUDNN Version: 7.6.3
Operating System Version: ubuntu 20.04

**Comment by y200504040u** [comment]
I have fixed this bug which made by myself.

**Comment by woshidengweimo** [comment]
can you tell me how you deal with this bug?

**Comment by y200504040u** [comment]
> can you tell me how you deal with this bug?

It's been so long that I can't remember it clearly.
But I remember that I made a stupid mistake.
Maybe when I used the function **common.do_inference_v2(context, bindings, inputs, outputs, stream)**, I passed a wrong argument into the **outputs**.
