### ISSUE TITLE
Cuda Error in executeFused: 46 (all CUDA-capable devices are busy or unavailable)

### ISSUE THREAD

**Issue by KarKLi** [NVIDIA/TensorRT#1173]
## Environment

**TensorRT Version**: 6.0.1.5
**NVIDIA GPU**: GeForce RTX 2080 Ti
**NVIDIA Driver Version**: 418.87.00
**CUDA Version**: 10.1
**CUDNN Version**: 7.6.5
**Operating System**: CentOS
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

We use MNIST by onnx format from TensorRT sample.

## Steps To Reproduce

I implemented my own GPU allocator, and take control of the allocate and free by inherit from IGpuAllocator *. It works well when GPU 0 (index got by nvidia-smi) is available.

Because the server is used by multi-user, so sometimes GPU 0 may not avaliable. So I set my device by cudaSetDevice(2); before executing ```context->execute(buffers);```, but still get error:

```
[03/08/2021-11:02:17] [E] [TRT] ../rtExt/cuda/cudaFusedConvActRunner.cpp (302) - Cuda Error in executeFused: 46 (all CUDA-capable devices are busy or unavailable)
[03/08/2021-11:02:17] [E] [TRT] FAILED_EXECUTION: std::exception
```
And server nvidia-smi output has attached at below:
![image](https://user-images.githubusercontent.com/34907015/113963035-71957c00-985b-11eb-8003-32e7062191fe.png)

As you can see, the GPU 0 and 1 is working, but 2 and 3 is idle.

For business usage, all of the GPUs must be set on exclusive mode by command ```sudo nvidia-smi -c 3```.

**Comment by KarKLi** [comment]
By the way, I ran the sample ```sampleOnnxMNIST``` just now, and it works well. I don't know which GPU was selected for computation.

**Comment by KarKLi** [comment]
And IExecutionContext pointer is created with engine->createExecutionContextWithoutDeviceMemory(). And later allocated by my own allocator, like this:
```
        context = SampleUniquePtr<nvinfer1::IExecutionContext>(engine->createExecutionContextWithoutDeviceMemory());
        if (!context)
        {
            gLogError  << "engine start failed, context error." << endl;
            return -1;
        }
       uint64_t execute_memory_size = engine->getDeviceMemorySize();
       void *execution_memory = allocator->allocate(execute_memory_size, alignment, 0);
       context->setDeviceMemory(execution_memory);
       // execution...
       allocator->free(execution_memory);
```
Where alignment is get by cudaGetDeviceProp, equals to texture memory alignment. I think alignment is not a problem.
