### ISSUE TITLE
C:\source\rtSafe\cuda\cudaConvolutionRunner.cpp (483) - Cudnn Error in nvinfer1::rt::cuda::CudnnConvolutionRunner::executeConv

### ISSUE THREAD

**Issue by Z-XQ** [NVIDIA/TensorRT#1371]
## Description
TensorRT-7.2.3.4\bin>sample_mnist.exe --datadir=D:\code\Cplusplus\TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.0.cudnn8.1\TensorRT-7.2.3.4\data\mnist
&&&& RUNNING TensorRT.sample_mnist # sample_mnist.exe --datadir=D:\code\Cplusplus\TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.0.cudnn8.1\TensorRT-7.2.3.4\data\mnist
[07/14/2021-14:31:39] [I] Building and running a GPU inference engine for MNIST
[07/14/2021-14:31:41] [W] [TRT] TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.2
[07/14/2021-14:32:04] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[07/14/2021-14:32:05] [E] [TRT] C:\source\rtSafe\cuda\cudaConvolutionRunner.cpp (483) - Cudnn Error in nvinfer1::rt::cuda::CudnnConvolutionRunner::executeConv: 8 (CUDNN_STATUS_EXECUTION_FAILED)
[07/14/2021-14:32:05] [E] [TRT] C:\source\rtSafe\cuda\cudaConvolutionRunner.cpp (483) - Cudnn Error in nvinfer1::rt::cuda::CudnnConvolutionRunner::executeConv: 8 (CUDNN_STATUS_EXECUTION_FAILED)
&&&& FAILED TensorRT.sample_mnist # sample_mnist.exe --datadir=D:\code\Cplusplus\TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.0.cudnn8.1\TensorRT-7.2.3.4\data\mnist

## Environment
TensorRT 7.2.3.4
window10
cuda11.0
cudnn8.0.2

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by Z-XQ** [comment]
> ## Description
> TensorRT-7.2.3.4\bin>sample_mnist.exe --datadir=D:\code\Cplusplus\TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.0.cudnn8.1\TensorRT-7.2.3.4\data\mnist
> &&&& RUNNING TensorRT.sample_mnist # sample_mnist.exe --datadir=D:\code\Cplusplus\TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.0.cudnn8.1\TensorRT-7.2.3.4\data\mnist
> [07/14/2021-14:31:39] [I] Building and running a GPU inference engine for MNIST
> [07/14/2021-14:31:41] [W] [TRT] TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.2
> [07/14/2021-14:32:04] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
> [07/14/2021-14:32:05] [E] [TRT] C:\source\rtSafe\cuda\cudaConvolutionRunner.cpp (483) - Cudnn Error in nvinfer1::rt::cuda::CudnnConvolutionRunner::executeConv: 8 (CUDNN_STATUS_EXECUTION_FAILED)
> [07/14/2021-14:32:05] [E] [TRT] C:\source\rtSafe\cuda\cudaConvolutionRunner.cpp (483) - Cudnn Error in nvinfer1::rt::cuda::CudnnConvolutionRunner::executeConv: 8 (CUDNN_STATUS_EXECUTION_FAILED)
> &&&& FAILED TensorRT.sample_mnist # sample_mnist.exe --datadir=D:\code\Cplusplus\TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.0.cudnn8.1\TensorRT-7.2.3.4\data\mnist
> 
> ## Environment
> TensorRT 7.2.3.4
> window10
> cuda11.0
> cudnn8.0.2
> 
> **TensorRT Version**:
> **NVIDIA GPU**:
> **NVIDIA Driver Version**:
> **CUDA Version**:
> **CUDNN Version**:
> **Operating System**:
> **Python Version (if applicable)**:
> **Tensorflow Version (if applicable)**:
> **PyTorch Version (if applicable)**:
> **Baremetal or Container (if so, version)**:
> 
> ## Relevant Files
> ## Steps To Reproduce

**Comment by Z-XQ** [comment]
I fixed it. The reason is that the cudnn is two low. I update version of cudnn and cuda.
