### ISSUE TITLE
pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered

### ISSUE THREAD

**Issue by liyuyuan6969** [NVIDIA/TensorRT#1469]
## Description
hi,guys,i am having some problem when i use TensorRT to optimize yolact++,you know,TensorRT does not support DCNv2,so i find a DCNv2 TensorRT Plugin in github and i transform my yolact++ to trt successfully,but when i run trt model to infer,some error occured.i don't know what to do.Maybe some wrong in .cu?i am a new player in CUDA program.Can you give me a hand?

this plugin i add noexcept to suit TensorRT8.0.others no changed.
[DCNv2 Plugin](https://github.com/lesliejackson/TensorRT7-DCNv2-Plugin/tree/master/DCNv2)

## error information
```
[TensorRT] VERBOSE: Using cublasLt a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 3582, GPU 7704 (MiB)
[TensorRT] VERBOSE: Using cuDNN as a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 3582, GPU 7712 (MiB)
[TensorRT] VERBOSE: Total per-runner device memory is 187544576
[TensorRT] VERBOSE: Total per-runner host memory is 167648
[TensorRT] VERBOSE: Allocated activation device memory of size 93570048
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data1/xuduo/optimize/yolact_dir_0804/inference.py", line 124, in <module>
    trt_outputs = common.do_inference_v2(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
  File "/data1/xuduo/optimize/yolact_dir_0804/common.py", line 163, in do_inference_v2
    stream.synchronize()
pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
[TensorRT] ERROR: 1: [fusedConvActRunner.cpp::destroyFilterTexture::301] Error Code 1: Cuda Runtime (all CUDA-capable devices are busy or unavailable)
[TensorRT] INTERNAL ERROR: [defaultAllocator.cpp::free::71] Error Code 1: Cuda Runtime (all CUDA-capable devices are busy or unavailable)
[TensorRT] WARNING: Unable to determine GPU memory usage
[TensorRT] WARNING: Unable to determine GPU memory usage
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 3624, GPU 0 (MiB)
[TensorRT] INTERNAL ERROR: [defaultAllocator.cpp::free::71] Error Code 1: Cuda Runtime (all CUDA-capable devices are busy or unavailable)
[TensorRT] INTERNAL ERROR: [resources.cpp::~ScopedCudaStream::450] Error Code 1: Cuda Runtime (all CUDA-capable devices are busy or unavailable)
```

## Environment
- Ubuntu18.04
- GeForce RTX 2080TI
- Driver Version 450.51.06
- NVIDIA-SMI 450.51.06
- CUDA Version: 11.0
- python3.6.8
- Cmake3.13.0
- CUDA toolkit 11.0.221
- CUDNN8.05
- TensorRT8.0-EA（Early Access）
- onnx1.6
- onnx-tensorrt8.0-EA

### inference.py

```
import os
import torch
import tensorrt as trt
from PIL import Image
import numpy as np
import time
import cv2
import glob
import config as cfg
import torch.nn.functional as F
import sys
sys.path.insert(1, os.path.join(sys.path[0], ".."))
import common
print("sys.path[0]",sys.path[0])
TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
def GiB(val):
    return val * 1 << 30
def conver_engine(onnx_file_path, engine_file_path="", max_batch_size=1):
    """Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""
    """Takes an ONNX file and creates a TensorRT engine to run inference with"""
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        # builder.max_workspace_size = GiB(max_batch_size)
        builder.max_batch_size = max_batch_size
        # Parse model file
        if not os.path.exists(onnx_file_path):
            print('ONNX file {} not found, please run onnx2trt_yolact.py first to generate it.'.format(onnx_file_path))
            exit(0)
        print('Loading ONNX file from path {}...'.format(onnx_file_path))
        with open(onnx_file_path, 'rb') as model:
            print('Beginning ONNX file parsing')
            if not parser.parse(model.read()):
                print ('ERROR: Failed to parse the ONNX file.')
                for error in range(parser.num_errors):
                    print (parser.get_error(error))
                return None
        # The actual yolov3.onnx is generated with batch size 64. Reshape input to batch size 1
        print('Completed parsing of ONNX file')
        print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
        engine_config = builder.create_builder_config()
        engine = builder.build_engine(network,engine_config)
        print("Completed creating Engine")
        with open(engine_file_path, "wb") as f:
            f.write(engine.serialize())
        print("Completed writing Engine. Well done!")
    return engine

def preprocess_image(path):
    # img [h,w,c]
    image = cv2.imread(image_name)
    img_raw_data = cv2.imencode('.jpg', image)[1].tobytes()
    img_data = cv2.imdecode(np.asarray(bytearray(img_raw_data), dtype=np.uint8),
                       cv2.IMREAD_COLOR)
    frame = torch.from_numpy(img_data).cuda().float()
    # print(frame.size)
    batch = FastBaseTransform()(frame.unsqueeze(0))
    return batch

class FastBaseTransform(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mean = torch.Tensor(cfg.MEANS).float().cuda()[None, :, None, None]
        self.std = torch.Tensor(cfg.STD).float().cuda()[None, :, None, None]
        self.transform = cfg.resnet_transform
    def forward(self, img):
        self.mean = self.mean.to(img.device)
        self.std = self.std.to(img.device)
        # img assumed to be a pytorch BGR image with channel order [n, h, w, c]
        img_size = (cfg.max_size, cfg.max_size)
        # 图片转为[n,c,h,w]格式
        img = img.permute(0, 3, 1, 2).contiguous()
        img = F.interpolate(img, img_size, mode='bilinear', align_corners=False)
        if self.transform.normalize:
            img = (img - self.mean) / self.std
        elif self.transform.subtract_means:
            img = (img - self.mean)
        elif self.transform.to_float:
            img = img / 255
        if self.transform.channel_order != 'RGB':
            raise NotImplementedError
        img = img[:, (2, 1, 0), :, :].contiguous()
        # Return value is in channel order [n, c, h, w] and RGB
        return img

if __name__ == "__main__":
    onnx_file_path = "yolact.onnx"
    engine_file_path = "yolact.trt"
    # threshold = 0.5
    image_name = "/data1/xuduo/optimize/yolact_dir_0804/img/material_WholeBookQuestionData_7H1110B44850N_QuestionBookImage20210713083208_164_586_7H1110B44850N.jpg"
    if not os.path.exists(engine_file_path):
        print("no engine file")
        # conver_engine(onnx_file_path, engine_file_path)
    print(f"Reading engine from file {engine_file_path}")
    # preprocess_time = 0
    # process_time = 0
    engine = conver_engine(onnx_file_path, engine_file_path)
    # Allocate buffers and create a CUDA stream.
    inputs, outputs, bindings, stream = common.allocate_buffers(engine)
    # Contexts are used to perform inference.
    context = engine.create_execution_context()
    batch = preprocess_image(image_name)
    np.copyto(inputs[0].host, batch.cpu().numpy().ravel())
    trt_outputs = common.do_inference_v2(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
    print("预测结果：",trt_outputs)
```
`
when i load model from yolact.trt,same error occured
```
[TensorRT] VERBOSE: Registered plugin creator - ::BatchTilePlugin_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::BatchedNMS_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::CoordConvAC version 1
[TensorRT] VERBOSE: Registered plugin creator - ::CropAndResize version 1
[TensorRT] VERBOSE: Registered plugin creator - ::CropAndResizeDynamic version 1
[TensorRT] VERBOSE: Registered plugin creator - ::DetectionLayer_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::EfficientNMS_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::FlattenConcat_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::GenerateDetection_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::GridAnchor_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::GridAnchorRect_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::InstanceNormalization_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::LReLU_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::MultilevelCropAndResize_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::MultilevelProposeROI_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::NMS_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::NMSDynamic_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Normalize_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::PriorBox_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::ProposalLayer_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Proposal version 1
[TensorRT] VERBOSE: Registered plugin creator - ::ProposalDynamic version 1
[TensorRT] VERBOSE: Registered plugin creator - ::PyramidROIAlign_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Region_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Reorg_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::ResizeNearest_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::RPROI_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::ScatterND version 1
[TensorRT] VERBOSE: Registered plugin creator - ::SpecialSlice_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Split version 1
[TensorRT] VERBOSE: Registered plugin creator - ::DCNv2 version 1
Reading engine from file yolact.trt
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +300, GPU +0, now: CPU 361, GPU 5136 (MiB)
[TensorRT] INFO: Loaded engine size: 408 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 361 MiB, GPU 5136 MiB
[TensorRT] VERBOSE: Using cublasLt a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 791, GPU 5592 (MiB)
[TensorRT] VERBOSE: Using cuDNN as a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +439, GPU +172, now: CPU 1230, GPU 5764 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 3110, GPU 7010 (MiB)
[TensorRT] VERBOSE: Deserialization required 16166066 microseconds.
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine end: CPU 3110 MiB, GPU 7010 MiB
[TensorRT] VERBOSE: Using cublasLt a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 3110, GPU 7058 (MiB)
[TensorRT] VERBOSE: Using cuDNN as a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +1, GPU +8, now: CPU 3111, GPU 7066 (MiB)
[TensorRT] VERBOSE: Total per-runner device memory is 187544576
[TensorRT] VERBOSE: Total per-runner host memory is 167648
[TensorRT] VERBOSE: Allocated activation device memory of size 93570048
[TensorRT] ERROR: 1: [scaleRunner.cpp::execute::139] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data1/xuduo/optimize/yolact_dir_0804/inference.py", line 128, in <module>
    trt_outputs = common.do_inference_v2(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
  File "/data1/xuduo/optimize/yolact_dir_0804/common.py", line 161, in do_inference_v2
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
  File "/data1/xuduo/optimize/yolact_dir_0804/common.py", line 161, in <listcomp>
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
pycuda._driver.LogicError: cuMemcpyDtoHAsync failed: an illegal memory access was encountered
```

**Comment by ttyio** [comment]
Hello @liyuyuan6969 , have you tried `TRT 8.0GA update1`? thanks

**Comment by ttyio** [comment]
@liyuyuan6969 , also could you debug the crash with adding 'cudaStreamSynchronize' inside your plugin enqueue function, in case this illegal memory is from the previous plugin. thanks!

**Comment by wxinbeings** [comment]
I got the same error, have you solved it?

**Comment by wxinbeings** [comment]
> I got the same error, have you solved it?

When I use TensorRT 7.0.0.11, cuda 10.0, cudnn 7.6, it works well. And TRT 8.0GA update1 does not work.

**Comment by ttyio** [comment]
@lesliejackson 
hmmm, the plugin function prototype changed in 8.0, could you adding `noexcept` to `initialize` ? see https://github.com/NVIDIA/TensorRT/blob/main/include/NvInferRuntimeCommon.h#L479

thanks

**Comment by ttyio** [comment]
Closing since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by hyperfraise** [comment]
I have the same issue on 
2060 SUPER
Driver 470.86
TensorRT 8.0.3 
CUDA 11.4.2 
cuBLAS 11.6.1.51
cuDNN 8.2.4.15
NCCL 2.11.4

**Comment by ttyio** [comment]
@hyperfraise , have you tried 8.2? thanks

**Comment by hyperfraise** [comment]
> @hyperfraise , have you tried 8.2? thanks

On it.

**Comment by NicholasYoungAI** [comment]
> I have the same issue on 2060 SUPER Driver 470.86 TensorRT 8.0.3 CUDA 11.4.2 cuBLAS 11.6.1.51 cuDNN 8.2.4.15 NCCL 2.11.4 with Resnext 3D network

I have same issue on same version

**Comment by hyperfraise** [comment]
The problem indeed disappears with 8.2 (in 21.12)

**Comment by JeanValere** [comment]
Everyone, 
please check your network input and output, 
I changed my network output from multiple to one, 
problem solved.

**Comment by husterdjx** [comment]
Hi @JeanValere,
I encountered the same reported error. I am using Pytorch SSD300 model, converted to onnx format and then using tensorrt for inference. According to your description I should change the multiple outputs of the SSD (one is float32[4,4,8732] and one is float32[4,81,8732]) to one, which is strange.

## Environment
TensorRT Version: 8.2.5.1
NVIDIA GPU: V100
NVIDIA Driver Version: 520.61.05
CUDA Version: 11.8
CUDNN Version: 8401
Operating System: 4.15.0-45-generic
Python Version (if applicable): 3.8.13
PyTorch Version (if applicable): 1.13.0
Container (if so, version): nvcr.io/nvidia/pytorch:22.06-py3

## Code
```python
import skimage
from skimage import io
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
import torch
import torchvision
import tensorrt as trt
import numpy as np
import time

import pycuda.driver as cuda  

import pycuda.autoinit

def load_image(image_path):
    """Code from Loading_Pretrained_Models.ipynb - a Caffe2 tutorial"""
    img = skimage.img_as_float(io.imread(image_path))
    if len(img.shape) == 2:
        img = np.array([img, img, img]).swapaxes(0, 2)
    # print("type: ", type(img)) # np.ndarray
    img = torch.from_numpy(img).float().cuda()
    return img

def ssd_output(detections_batch_, prefix):
    results_per_input = ssd_util.decode_results(detections_batch_)
    best_results_per_input = [ssd_util.pick_best(results, 0.4) for results in results_per_input]
    classes_to_labels = ssd_util.get_coco_object_dictionary()

    for i in range(len(best_results_per_input)):
        bboxes, classes, confidences = best_results_per_input[i]
        for idx in range(len(bboxes)):
            left, bot, right, top = bboxes[idx]
            x, y, w, h = [val * 300 for val in [left, bot, right - left, top - bot]]
            print("[{}]\timg{:4}|{:4} {:<15} {:.2f}% ({:.0f}, {:.0f}) ({:.0f}, {:.0f})".format(
                prefix, i, idx, classes_to_labels[classes[idx] - 1], confidences[idx] * 100, x, y, w, h))

batch = 4
# Step 1: Load pretrained model from PyTorch Hub
ssd_model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd')
ssd_util = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd_processing_utils')
ssd_model.eval()
ssd_model = ssd_model.cuda()

uris = []
for _ in range(batch):
    uris.append('http://images.cocodataset.org/val2017/000000397133.jpg')
inputs = [load_image(uri) for uri in uris]

# Step 2: Export PyTorch model to ONNX
ssd_dummy_input = torch.randn(batch, 3, 300, 300).cuda()
ssd_onnx_file_path = f'ssd_batch{batch}.onnx'
torch.onnx.export(ssd_model, ssd_dummy_input, ssd_onnx_file_path)

# Step 3: Create a TensorRT engine from the ONNX model
TRT_LOGGER = trt.Logger(trt.Logger.ERROR)
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

def make_rt_engine(onnx_file_path):
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        config = builder.create_builder_config()
        config.max_workspace_size = 1 << 34
        builder.max_batch_size = batch
        
        # builder.fp16_mode = True
        if builder.platform_has_fast_fp16:
            config.set_flag(trt.BuilderFlag.FP16)

        # Parse the ONNX model
        print("Parsing onnx file {}...".format(onnx_file_path))
        with open(onnx_file_path, 'rb') as model_file:
            if not parser.parse(model_file.read()):
                print('ERROR: Failed to parse the ONNX file.')
                for error in range(parser.num_errors):
                    print(parser.get_error(error))
                return None

        # Build and serialize the TensorRT engine
        # engine = builder.build_cuda_engine(network)
        profile = builder.create_optimization_profile()
        config.add_optimization_profile(profile)

        print("Building an engine...")
        engine = builder.build_engine(network, config)

        # with open('alexnet.trt', 'wb') as trt_model_file:
        #     trt_model_file.write(engine.serialize())
    return engine

class HostDeviceMem(object):
    def __init__(self, host_mem, device_mem):
        """
        host_mem: cpu memory
        device_mem: gpu memory
        """
        self.host = host_mem
        self.device = device_mem

    def __str__(self):
        return "Host:\n" + str(self.host)+"\nDevice:\n"+str(self.device)

    def __repr__(self):
        return self.__str__()

def allocate_buffers(engine):
    inputs, outputs, bindings = [], [], []
    stream = cuda.Stream()
    for binding in engine:
        size = trt.volume(engine.get_binding_shape(binding)) * engine.max_batch_size # 
        # size = trt.volume(engine.get_binding_shape(binding))                       # dynamic batch
        size = abs(size)                                
        print("size:", size, end=" ")
        dtype = trt.nptype(engine.get_binding_dtype(binding))
        print("dtype:", dtype)
        host_mem = cuda.pagelocked_empty(size, dtype)   
        device_mem = cuda.mem_alloc(host_mem.nbytes)    
        bindings.append(int(device_mem))                
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))
    input("Press Enter to continue...")

    return inputs, outputs, bindings, stream

def inference(context, bindings, inputs, outputs, stream, batch_size=1):
    # Transfer data from CPU to the GPU.
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    # Run inference.
    context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)
    # Transfer predictions back from the GPU.
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    # gpu to cpu
    # Synchronize the stream
    stream.synchronize()
    # Return only the host outputs.
    return [out.host for out in outputs]

def postprocess_the_outputs(h_outputs, shape_of_output):
    h_outputs = h_outputs.reshape(*shape_of_output)
    return h_outputs

def execute_ssd_engine(engine, input_data):
    with engine.create_execution_context() as context:
        '''
        dev = cuda.Device(3)
        ctx = dev.make_context()    
        '''

        inputs, outputs, bindings, stream = allocate_buffers(engine)
        output_shapes = [(batch, 4, 8732), (batch, 81, 8732)]
        trt_outputs = []
        inputs[0].device = input_data
        
        # Execute inference
        # warmup
        print("[SSD]warmup...")
        for i in range(50):
            trt_outputs = inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
        
        print("[SSD]start inference...")
        times = []
        for i in range(100):
            T1=time.perf_counter()   
            trt_outputs = inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
            T2=time.perf_counter()
            times.append(T2-T1)
            if (i + 1) % 10 == 0:
                print('[SSD]TensorRT Inference {:d}/{:d}: {:.3f}ms'.format(i + 1, 100, np.mean(times) * 1000))

        print("[SSD]finish!")
    return [output.reshape(shape) for output, shape in zip(trt_outputs, output_shapes)]

ssd_engine = make_rt_engine(ssd_onnx_file_path)

rt_outputs = execute_ssd_engine(ssd_engine, _images_dali_tensor_data_ptr)

print("ploc shape:", rt_outputs[0].shape)
print("plable shape:", rt_outputs[1].shape)

# transfer to torch.Tensor
ploc = torch.from_numpy(rt_outputs[0])
plable = torch.from_numpy(rt_outputs[1])

ssd_output((ploc, plable), "TensorRT")
```
I got the following errors:
```txt
Traceback (most recent call last):
  File "ssd_rt.py", line 281, in <module>
    # Step 4: Run inference with TensorRT engine
  File "ssd_rt.py", line 190, in execute_ssd_engine
    for i in range(50):
  File "ssd_rt.py", line 160, in inference
    # Synchronize the stream
pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 1616, in _shutdown_pipelines
    p._shutdown()
  File "/opt/conda/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 354, in _shutdown
    self._pipe.Shutdown()
RuntimeError: CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered
[01/21/2024-14:16:54] [TRT] [E] 1: [resizingAllocator.cpp::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [resizingAllocator.cpp::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[01/21/2024-14:16:54] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuStreamDestroy failed: an illegal memory access was encountered
Exception ignored in: <function Pipeline.__del__ at 0x7fc5706bcaf0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 350, in __del__
  File "/opt/conda/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 354, in _shutdown
RuntimeError: CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered
terminate called after throwing an instance of 'dali::CUDAError'
  what():  CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered
Aborted (core dumped)
```
Additionally, I use dali to preprocess dara, and put `_images_dali_tensor_data_ptr ` into the tensorrt, and I'm sure it works.
