### ISSUE TITLE
Bert trt fp16 gives nan values

### ISSUE THREAD

**Issue by ramaneswaran** [NVIDIA/TensorRT#1500]
## Description

I have converted a BERT model from huggingface into onnx
Then used trtexec to convert to TensortRT file with the --fp16 flag.

The model is sucessfully converted to TensortRT however on inference it gives output as all NaN values.

The same onnx model when converted to FP32 TensorRT gives correct output during inference.

## Environment

**TensorRT Version**: 8.0.1.6 
**NVIDIA GPU**: Quadro RTX 6000
**NVIDIA Driver Version**: 460.91.03
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: Ubuntu 20.04.2 LTS
**Python Version (if applicable)**:  3.8.10
**PyTorch Version (if applicable)**:  1.10

## 1.  Convert onnx model to trt using trtexec 
 
```
!trtexec --onnx=deepset_roberta.onnx \
--saveEngine=roberta_fp16.engine --fp16 \
--explicitBatch --iterations=100 --avgRuns=100 --workspace=16320 \
--minShapes=input_ids:1x384,attention_mask:1x384 \
        --optShapes=input_ids:4x384,attention_mask:4x384 \
                --maxShapes=input_ids:64x384,attention_mask:64x384
```

## 2. Output returned after successful conversion

```
&&&& PASSED TensorRT.trtexec [TensorRT v8001] # trtexec --onnx=deepset_roberta.onnx --saveEngine=roberta_fp16.engine --fp16 --explicitBatch --iterations=100 --avgRuns=100 --workspace=16320 --minShapes=input_ids:1x384,attention_mask:1x384 --optShapes=input_ids:4x384,attention_mask:4x384 --maxShapes=input_ids:64x384,attention_mask:64x384
[09/20/2021-11:42:55] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 1126, GPU 3329 (MiB)
```

However when i try to do inference it gives nan output

**Comment by vietbeu** [comment]
Same issues. Do u fix it ? Helppppppp

**Comment by ramaneswaran** [comment]
The issue I had was with the inputs I was passing. They were not of the correct data type. With the following code for allocating buffers and doing model inference.

```python
    def allocate_buffers(self):
        
        # Allocate the required buffers with batch_size 1
        input_shape = (1, 384)
        input_nbytes = trt.volume(input_shape) *  trt.int32.itemsize
        
        d_inputs = [cuda.mem_alloc(input_nbytes) for binding in range(2)]
        
        # Create a stream in which to copy inputs/outputs and run inference.
        stream = cuda.Stream()

        # Specify the input shapes
        for binding in range(2):
            self.context.set_binding_shape(binding, input_shape)
        assert self.context.all_binding_shapes_specified
        
        h_outputs = [cuda.pagelocked_empty(input_shape, dtype=np.float32) for binding in range(2)]
        d_outputs = [cuda.mem_alloc(h_outputs[0].nbytes) for binding in range(2)]
        
        # Create a stream in which to copy inputs/outputs and run inference.
        stream = cuda.Stream()
        
        return d_inputs, d_outputs, h_outputs, stream
    
    def __call__(self, input_ids: np.ndarray, attention_mask: np.ndarray):
        
        
        input_ids = input_ids.astype(np.int32)
        attention_mask = attention_mask.astype(np.int32)
        
        # Copy inputs
        cuda.memcpy_htod_async(self.d_inputs[0], input_ids, self.stream)
        cuda.memcpy_htod_async(self.d_inputs[1], attention_mask, self.stream)

        # Run inference
        self.context.execute_async(bindings=[int(d_inp) for d_inp in self.d_inputs] + 
                              [int(d_out) for d_out in self.d_outputs], stream_handle=self.stream.handle)
        
        # Transfer predictions back from GPU
        cuda.memcpy_dtoh_async(self.h_outputs[0], self.d_outputs[0], self.stream)
        cuda.memcpy_dtoh_async(self.h_outputs[1], self.d_outputs[1], self.stream)

        # Synchronize the stream
        self.stream.synchronize()
        
        return self.h_outputs[0], self.h_outputs[1]
```

**Comment by nvpohanh** [comment]
@ramaneswaran So is this issue solved? If so, I am closing this issue. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
