### ISSUE TITLE
[BUG] T5 demo broken for T5-3b

### ISSUE THREAD

**Issue by michaelroyzen** [NVIDIA/TensorRT#1686]
## Description

The [blog post announcing TensorRT 8.2](https://developer.nvidia.com/blog/optimizing-t5-and-gpt-2-for-real-time-inference-with-tensorrt/) claims that TensorRT can support T5 up to 11B and includes metrics for T5-3B, but running the [mentioned notebook fails](https://github.com/NVIDIA/TensorRT/blob/main/demo/HuggingFace/notebooks/t5.ipynb):

```
[12/27/2021-06:28:24] [TRT] [W] Skipping tactic 0 due to Myelin error: CUDA error 2 for 4963639552-byte allocation.
[12/27/2021-06:28:24] [TRT] [E] 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[(Unnamed Layer* 13) [Constant] + (Unnamed Layer* 14) [Shuffle]...Mul_1396]}.)
[12/27/2021-06:28:24] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
```

The notebook works up to t5-large but fails with t5-3B, which is puzzling because the config files in the repo are seemingly set up to handle t5-3B and t5-3B compatibility is advertised.

## Environment

The environment is a TensorRT Docker container built based on the instructions based on the blog post linked above. Below are the specs for the host OS.

**TensorRT Version**: 8.2 GA
**NVIDIA GPU**: Tested on T4 and A10
**NVIDIA Driver Version**: 450.142.00 on T4, 495 on A10
**CUDA Version**: 11.4
**CUDNN Version**: 8
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: Tested with 1.8 and 1.10.1
**Baremetal or Container (if so, version)**:

**Comment by michaelroyzen** [comment]
I was able to fix the issue above by increasing the size of DEFAULT_TRT_WORKSPACE_MB in export.py and not running the PyTorch benchmarking cells in `t5.ipynb`, hence saving GPU memory for where it is needed during TRT export.

However, I discovered a number of other bugs in the notebook. `T5TRTDecoder` needs `self.return_device` specified for `forward()` to run properly, but `t5.ipynb` doesn't set it so it needs to be set manually by calling `T5TRTDecoder .set_return_device("cuda")`.

Yet, setting the decoder return device to CUDA as opposed to cpu triggers another bug in `trt.py`. There is separate logic for cpu and CUDA return device decoding at line 267: 
`if is_cpu_mode:
            self.inputs["input_ids"] = input_ids.int().flatten().contiguous().cuda()
            self.bindings[0] = self.inputs["input_ids"].data_ptr()
        else:
            self.inputs["input_ids"][:bs * input_length] = input_ids.flatten()`.

With decoder_input_ids on CUDA, this causes a tensor mismatch error. Setting the GPU logic to the CPU logic is a quick workaround (it works), but I don't think it's necessarily optimal.

Please take a look @ttyio, these notebooks are very impressive but they appear to need some refactoring to work properly out of the box.

**Comment by ttyio** [comment]
Thanks @michaelroyzen , I have created internal issue to tracking this.

**Comment by nvpohanh** [comment]
@ttyio does the issue still exist?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
