### ISSUE TITLE
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Baiyixuan1113** [NVIDIA/TensorRT#1747]
## Environment

**TensorRT Version**: 7.2.1.6
**NVIDIA GPU**: RTX2080
**NVIDIA Driver Version**:  NVIDIA-Linux-x86_64-470.94.run
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.4/8.0.3/7.6.5
**Operating System**: Ubuntu18.04
**Python Version (if applicable)**: 3.7
**PyTorch Version (if applicable)**: 1.8.1
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

I want to build a tensorrt env, after I run ```pip install tensorrt-7.2.1.6-cp37-none-linux_x86_64.whl```, import tensorrt in python will report the following error```ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory```
But my cuda env is fine, I can run ```cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2 ```to get my cudnn version, and libcudnn.so.8 is in /usr/local/cuda-10.2/lib64

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Comment by Andy-Dang12** [comment]
you can try solution [here](https://github.com/pytorch/TensorRT/issues/1026#issuecomment-1119561746)

**Comment by ashmalvayani** [comment]
solve this by installing:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

this worked for me. I had to check the cuda version currently installed and download the appropriate PyTorch version from this website:
https://pytorch.org/
