### ISSUE TITLE
TRT8.2.1.8 and CUDA11.3 - Missing libmyelin.so.1 library

### ISSUE THREAD

**Issue by AstonnMartin** [NVIDIA/TensorRT#1798]
## Description

I am compiling a TRT8 project using TRT8.2.1.8. The error I got is: 
[cuda_trt_wrapper]: Load libnvinfer.so failed - libmyelin.so.1: cannot open shared object file: No such file or directory.  
Same setup (Machine, OS, code) works fine under CUDA 10.0 + TRT7. And I did find libmyelin.so.1 under my trt7 lib dir (my case /usr/local/trt7/lib), and I can't find it under trt8 lib dir (/usr/local/trt8.2/lib). Can I build it from source or get a copy somewhere? Thanks.

## Environment

**TensorRT Version**: 8.2.1.8
**NVIDIA GPU**: P40
**NVIDIA Driver Version**: 452
**CUDA Version**: 11.3
**CUDNN Version**: cudnn-11.3-linux-x64-v8.2.1.32
**Operating System**: Redhat7
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by AstonnMartin** [comment]
I fixed it. My LD_LIB_PATH was pointed to trt8.2 yet part of the code still has a hard link to trt7's location. After update the code, the error is gone.

**Comment by ttyio** [comment]
Cool, closing since this is solved
