### ISSUE TITLE
fp16 less batchsize inference get cuStreamSynchronize failed: an illegal memory access was encountered

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#1842]
Hi, as all we know, TensorRT in python is robust, if an engine generated with batchsize == 8, we still can get result even input batch is 6.
The rest result are zeros.

This is normal on FP32, but I found in FP16, if engine batchsize == 8, I using batchsize==6 data as input, will got error like this:

```
stream.synchronize()
pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered

```

Does anyone know why about this? (this can be easily revealed, I got same problem on a classification model and a detection model)

**Comment by ttyio** [comment]
@jinfagang , this not guarantee to work, could you build engine with dynamic shape, and bind the batch size to 6 before inference? thanks

**Comment by jinfagang** [comment]
@ttyio  this is a bug of BatchedNMSPlugin , it will get into this error if using. fp16 on multi-batch. However, I have solved it.
