### ISSUE TITLE
TensorRT 8.2 INT8 :  Cuda Runtime (an illegal memory access was encountered)

### ISSUE THREAD

**Issue by DataXujing** [NVIDIA/TensorRT#1869]
## Description

```
[03/21/2022-00:31:25] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +51, now: CPU 9, GPU 171 (MiB)
[03/21/2022-00:31:25] [TRT] [V] Calculating Maxima
[03/21/2022-00:31:25] [TRT] [I] Starting Calibration.
[03/21/2022-00:31:25] [TRT] [E] 1: [calibrator.cpp::nvinfer1::builder::Histogram::add::777] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
Traceback (most recent call last):
[03/21/2022-00:31:25] [TRT] [E] 1: [executionContext.cpp::nvinfer1::rt::ExecutionContext::commonEmitDebugTensor::1234] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [calibrator.cu::cuCalibrator::absTensorMax::130] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [executionContext.cpp::nvinfer1::rt::ExecutionContext::commonEmitDebugTensor::1234] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [executionContext.cpp::nvinfer1::rt::ExecutionContext::executeInternal::610] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [resizingAllocator.cpp::nvinfer1::internal::ResizingAllocator::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [resizingAllocator.cpp::nvinfer1::internal::ResizingAllocator::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [resizingAllocator.cpp::nvinfer1::internal::ResizingAllocator::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [resizingAllocator.cpp::nvinfer1::internal::ResizingAllocator::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [resizingAllocator.cpp::nvinfer1::internal::ResizingAllocator::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [resizingAllocator.cpp::nvinfer1::internal::ResizingAllocator::deallocate::100] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::~StdVirtualMemoryBufferImpl::121] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[03/21/2022-00:31:25] [TRT] [E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (an illegal memory access was encountered)
```

**Comment by DataXujing** [comment]
💯 This problem was fixed, I gave one less input when doing quantization, which caused the error above

**Comment by yasho191** [comment]
> 💯 This problem was fixed, I gave one less input when doing quantization, which caused the error above

@DataXujing Please can you elaborate more on this I am facing a similar error but still haven't been able to figure out a solution.

**Comment by slai-natanijel** [comment]
@yasho191 I had this issue today. I fixed it by making sure that the batch size of the calibration dataset/dataloader matches the model's expected batch size - then it worked :)

**Comment by sang981113** [comment]
This error was caused because of not setting cuda() into data in my case. thanks

**Comment by Egorundel** [comment]
@DataXujing Can you help me solve the problem in my efforts? 
I will be very grateful to you.

https://github.com/NVIDIA/TensorRT/issues/4053

**Comment by Egorundel** [comment]
@DataXujing @slai-natanijel @sang981113 Can you help me solve the problem in my efforts? 
I will be very grateful to you.

https://github.com/NVIDIA/TensorRT/issues/4053
