### ISSUE TITLE
deserializeCudaEngine failed(cuda error in nvinfer1::internal::defaultallocator::free:17 invalid device pointer)

### ISSUE THREAD

**Issue by RalphGuo** [NVIDIA/TensorRT#1910]
Hi, I'm currently using tensorRT-8.2.1.8(C++) for inference in VS2017(before this what I used is tensorRT-7 and it worked well). When I using the same code to run the same project, an error occured when at "runtime ->deserializeCudaEngine". In the control panel, it shows that, "C://source/rtSafe/safeRuntime.cpp(32) - Cuda error in nvinfer1::internal::defaultallocator::free:17 (invalid device pointer)."

After checking lots of documents and forums, I didn't see any similar questions, or any essential change should be made when chenging tensorRT-7 to 8.  Does anyone know that this error indicate?

Btw, the .engine file is converted from ONNX using tensorRT-8.2.1.8 (trtexec).

Any comment will be appreciated!
@pbridger @aaronp24 @ttyio @lukeyeager @elezar

**Comment by ttyio** [comment]
@RalphGuo , since you are upgrading the trt, there might multiple trt lib installed in your system. Could you check if your app and the trtexec has load the same nvinfer.dll? thanks

**Comment by RalphGuo** [comment]
> @RalphGuo , since you are upgrading the trt, there might multiple trt lib installed in your system. Could you check if your app and the trtexec has load the same nvinfer.dll? thanks

@ttyio Thanks for your reply. I'm sure I loaded the same nvinfer.dll. 
The error shows that there's something wrong at "defaultallocator" or "device pointer" which I never met before.

**Comment by ttyio** [comment]
@RalphGuo did you see any error like `out of memory` besides the log you showed in comment? maybe worth trying set a smaller workspace size?

**Comment by RalphGuo** [comment]
> @RalphGuo did you see any error like `out of memory` besides the log you showed in comment? maybe worth trying set a smaller workspace size?

No, the error I mentioned is all I got.
Fortunately problem solved, you are right, I did use the different nvinfer.dll in my app. There's a old version of nvinfer.dll in my folder, so app used the old one first rather than from the environment. Shoulda be more careful lol
Thanks again for your quick reply

**Comment by ttyio** [comment]
thanks @RalphGuo , closing
