### ISSUE TITLE
Multithread tensorrt

### ISSUE THREAD

**Issue by guetzhouyanxiao** [NVIDIA/TensorRT#2040]
Multithreaded tensorrt is used to infer a large number of images. After analyzing some images, an error is reported, and no result is returned
[TRT] [E] 1: [convolutionRunner.cpp::executeConv::511] Error Code 1: Cudnn (CUDNN_STATUS_BAD_PARAM)

**Comment by nvpohanh** [comment]
Could you follow this template to fill in more information so that we can investigate? Thanks

```
## Description

<!-- A clear and concise description of the bug or issue. -->


## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 


## Relevant Files

<!-- Please include links to any models, data, files, or scripts necessary to reproduce your issue. (Github repo, Google Drive/Dropbox, etc.) -->


## Steps To Reproduce

<!-- 
  Craft a minimal bug report following this guide - https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

  Please include:
  * Exact steps/commands to build your repro
  * Exact steps/commands to run your repro
  * Full traceback of errors encountered 
-->

```

**Comment by guetzhouyanxiao** [comment]
> 
## Environment

**TensorRT Version: 8.2.1.8
**NVIDIA GPU: NVIDIA GeForce RTX 3080
**NVIDIA Driver Version: 470.94
**CUDA Version: 11.1
**CUDNN Version: v8.0.5.39
**Operating System: Ubuntu 18.04
**Python Version (if applicable): python 3.7
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable):  1.9.1
**Baremetal or Container (if so, version)**:

**Comment by nvpohanh** [comment]
Could you share your code to run TRT in multi-thread environment?

Please note that execution context is not thread-safe. You need to create one execution context per thread.

**Comment by guetzhouyanxiao** [comment]
> 您能否分享您在多线程环境中运行 TRT 的代码？
> 
> 请注意，执行上下文不是线程安全的。您需要为每个线程创建一个执行上下文。

import os
import time
import torch
import torch.nn as nn
import numpy as np
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
import cv2
import netron
from tqdm import tqdm
import threading

G_LOGGER = trt.Logger(trt.Logger.WARNING)

def load_serialize_to_engine(serialize_file_path):
    # If a serialized engine exists, use it instead of building an engine.
    print("Reading engine from file {}".format(serialize_file_path))
    with open(serialize_file_path, "rb") as f, trt.Runtime(G_LOGGER) as runtime:
        return runtime.deserialize_cuda_engine(f.read())


# Simple helper data class that's a little nicer to use than a 2-tuple.
class HostDeviceMem(object):
    def __init__(self, host_mem, device_mem):
        self.host = host_mem
        self.device = device_mem

    def __str__(self):
        return "Host:\n" + str(self.host) + "\nDevice:\n" + str(self.device)

    def __repr__(self):
        return self.__str__()


def allocate_buffers2(engine, batch_size, image_size):
    inputs = []
    outputs = []
    bindings = []
    stream = cuda.Stream()

    tmp=[1, 4, 4, 4, 4]

    for count,binding in enumerate(engine):
        #print('binding:',engine.get_binding_shape(binding))
        if engine.get_binding_shape(binding)[-1]==-1:
            size = trt.volume(engine.get_binding_shape(binding)) * batch_size*(int)(image_size[-1]/tmp[count])*(int)(image_size[-2]/tmp[count])
        else:
            size = trt.volume(engine.get_binding_shape(binding))
        dtype = trt.nptype(engine.get_binding_dtype(binding))

        # Allocate host and device buffers
        host_mem = cuda.pagelocked_empty(size, dtype)
        device_mem = cuda.mem_alloc(host_mem.nbytes)
        # Append the device buffer to device bindings.
        bindings.append(int(device_mem))
        # Append to the appropriate list.
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))

    return inputs, outputs, bindings, stream

def do_inference(context, bindings, inputs, outputs, stream, batch_size=1, image_size=(1,3, 1024,1024)):

    #print("image_size", image_size)
    context.set_binding_shape(0, trt.Dims([batch_size, 3, image_size[-2], image_size[-1]]))#动态尺寸时一定要加上

    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    #print("copy data to cuda done!")
    
    # Run inference.
    ta = time.time()
    context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
    #context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)


    # Transfer predictions back from the GPU.
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    
    # Synchronize the stream
    stream.synchronize()

    
    # Return only the host outputs.
    return [out.host for out in outputs]


class PolarmaskTRT(nn.Module) :
    def __init__(self, engine_path, batch_size=1, down_scale=4, *args, **kwargs):
        super(PolarmaskTRT, self).__init__(*args, **kwargs)

        self.cfx = cuda.Device(0).make_context()

        self.engine = load_serialize_to_engine(engine_path)
        self.image_size = (1,3,1024, 1024)
        self.batch_size = batch_size
        self.down_scale = down_scale
        self.context = self.engine.create_execution_context()

        self.buffers = allocate_buffers2(self.engine, self.batch_size, self.image_size)
        self.inputs, self.outputs, self.bindings, self.stream = self.buffers
        self.context.set_optimization_profile_async(profile_index=0, stream_handle=self.stream.handle)
        
        print("polarmask TRT init done!")


    def __del__(self):
        del self.inputs
        del self.outputs
        del self.stream
        self.cfx.detach()

    def infer_image(self, img_input):

        self.cfx.push()
        img_input = np.ascontiguousarray(img_input)

        #single
        self.inputs[0].host = img_input
        trt_outputs = do_inference(self.context, bindings=self.bindings, inputs=self.inputs, outputs=self.outputs, stream=self.stream, batch_size=self.batch_size, image_size=img_input.shape)

        cls_pred_data = trt_outputs[0][:self.batch_size*5*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        polar_center_ness_pred_data = trt_outputs[1][:self.batch_size*1*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        center_offset_pred_data = trt_outputs[2][:self.batch_size*2*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        dist_pred_data = trt_outputs[3][:self.batch_size*36*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]

        cls_pred = torch.from_numpy(cls_pred_data.reshape(self.batch_size,5,img_input.shape[-2]//4,img_input.shape[-1]//4))
        polar_center_ness_pred = torch.from_numpy(polar_center_ness_pred_data.reshape(self.batch_size,1,img_input.shape[-2]//4,img_input.shape[-1]//4))
        center_offset_pred = torch.from_numpy(center_offset_pred_data.reshape(self.batch_size,2,img_input.shape[-2]//4,img_input.shape[-1]//4))
        dist_pred = torch.from_numpy(dist_pred_data.reshape(self.batch_size,36,img_input.shape[-2]//4,img_input.shape[-1]//4))

        #print("cls_pred", cls_pred)

        self.cfx.pop()
        return cls_pred, polar_center_ness_pred, dist_pred, center_offset_pred


#### I only create a context during initialization, and each thread calls the function infer_ image

**Comment by guetzhouyanxiao** [comment]
import os
import time
import torch
import torch.nn as nn
import numpy as np
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
import cv2
import netron
from tqdm import tqdm
import threading

G_LOGGER = trt.Logger(trt.Logger.WARNING)

def load_serialize_to_engine(serialize_file_path):
    # If a serialized engine exists, use it instead of building an engine.
    print("Reading engine from file {}".format(serialize_file_path))
    with open(serialize_file_path, "rb") as f, trt.Runtime(G_LOGGER) as runtime:
        return runtime.deserialize_cuda_engine(f.read())


# Simple helper data class that's a little nicer to use than a 2-tuple.
class HostDeviceMem(object):
    def __init__(self, host_mem, device_mem):
        self.host = host_mem
        self.device = device_mem

    def __str__(self):
        return "Host:\n" + str(self.host) + "\nDevice:\n" + str(self.device)

    def __repr__(self):
        return self.__str__()


def allocate_buffers2(engine, batch_size, image_size):
    inputs = []
    outputs = []
    bindings = []
    stream = cuda.Stream()

    tmp=[1, 4, 4, 4, 4]

    for count,binding in enumerate(engine):
        #print('binding:',engine.get_binding_shape(binding))
        if engine.get_binding_shape(binding)[-1]==-1:
            size = trt.volume(engine.get_binding_shape(binding)) * batch_size*(int)(image_size[-1]/tmp[count])*(int)(image_size[-2]/tmp[count])
        else:
            size = trt.volume(engine.get_binding_shape(binding))
        dtype = trt.nptype(engine.get_binding_dtype(binding))

        # Allocate host and device buffers
        host_mem = cuda.pagelocked_empty(size, dtype)
        device_mem = cuda.mem_alloc(host_mem.nbytes)
        # Append the device buffer to device bindings.
        bindings.append(int(device_mem))
        # Append to the appropriate list.
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))

    return inputs, outputs, bindings, stream

def do_inference(context, bindings, inputs, outputs, stream, batch_size=1, image_size=(1,3, 1024,1024)):

    #print("image_size", image_size)
    context.set_binding_shape(0, trt.Dims([batch_size, 3, image_size[-2], image_size[-1]]))#动态尺寸时一定要加上

    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    #print("copy data to cuda done!")
    
    # Run inference.
    ta = time.time()
    context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
    #context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)


    # Transfer predictions back from the GPU.
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    
    # Synchronize the stream
    stream.synchronize()

    
    # Return only the host outputs.
    return [out.host for out in outputs]


class PolarmaskTRT(nn.Module) :
    def __init__(self, engine_path, batch_size=1, down_scale=4, *args, **kwargs):
        super(PolarmaskTRT, self).__init__(*args, **kwargs)

        self.cfx = cuda.Device(0).make_context()

        self.engine = load_serialize_to_engine(engine_path)
        self.image_size = (1,3,1024, 1024)
        self.batch_size = batch_size
        self.down_scale = down_scale
        self.context = self.engine.create_execution_context()

        self.buffers = allocate_buffers2(self.engine, self.batch_size, self.image_size)
        self.inputs, self.outputs, self.bindings, self.stream = self.buffers
        self.context.set_optimization_profile_async(profile_index=0, stream_handle=self.stream.handle)
        
        print("polarmask TRT init done!")


    def __del__(self):
        del self.inputs
        del self.outputs
        del self.stream
        self.cfx.detach()

    def infer_image(self, img_input):

        self.cfx.push()
        img_input = np.ascontiguousarray(img_input)

        #single
        self.inputs[0].host = img_input
        trt_outputs = do_inference(self.context, bindings=self.bindings, inputs=self.inputs, outputs=self.outputs, stream=self.stream, batch_size=self.batch_size, image_size=img_input.shape)

        cls_pred_data = trt_outputs[0][:self.batch_size*5*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        polar_center_ness_pred_data = trt_outputs[1][:self.batch_size*1*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        center_offset_pred_data = trt_outputs[2][:self.batch_size*2*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        dist_pred_data = trt_outputs[3][:self.batch_size*36*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]

        cls_pred = torch.from_numpy(cls_pred_data.reshape(self.batch_size,5,img_input.shape[-2]//4,img_input.shape[-1]//4))
        polar_center_ness_pred = torch.from_numpy(polar_center_ness_pred_data.reshape(self.batch_size,1,img_input.shape[-2]//4,img_input.shape[-1]//4))
        center_offset_pred = torch.from_numpy(center_offset_pred_data.reshape(self.batch_size,2,img_input.shape[-2]//4,img_input.shape[-1]//4))
        dist_pred = torch.from_numpy(dist_pred_data.reshape(self.batch_size,36,img_input.shape[-2]//4,img_input.shape[-1]//4))

        #print("cls_pred", cls_pred)

        self.cfx.pop()
        return cls_pred, polar_center_ness_pred, dist_pred, center_offset_pred

**Comment by guetzhouyanxiao** [comment]
####I only create a context during initialization, and each thread calls the function infer_ image
class PolarmaskTRT(nn.Module) :
    def __init__(self, engine_path, batch_size=1, down_scale=4, *args, **kwargs):
        super(PolarmaskTRT, self).__init__(*args, **kwargs)

        self.cfx = cuda.Device(0).make_context()

        self.engine = load_serialize_to_engine(engine_path)
        self.image_size = (1,3,1024, 1024)
        self.batch_size = batch_size
        self.down_scale = down_scale
        self.context = self.engine.create_execution_context()

        self.buffers = allocate_buffers2(self.engine, self.batch_size, self.image_size)
        self.inputs, self.outputs, self.bindings, self.stream = self.buffers
        self.context.set_optimization_profile_async(profile_index=0, stream_handle=self.stream.handle)
        
        print("polarmask TRT init done!")


    def __del__(self):
        del self.inputs
        del self.outputs
        del self.stream
        self.cfx.detach()

    def infer_image(self, img_input):

        self.cfx.push()
        img_input = np.ascontiguousarray(img_input)

        #single
        self.inputs[0].host = img_input
        trt_outputs = do_inference(self.context, bindings=self.bindings, inputs=self.inputs, outputs=self.outputs, stream=self.stream, batch_size=self.batch_size, image_size=img_input.shape)

        cls_pred_data = trt_outputs[0][:self.batch_size*5*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        polar_center_ness_pred_data = trt_outputs[1][:self.batch_size*1*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        center_offset_pred_data = trt_outputs[2][:self.batch_size*2*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]
        dist_pred_data = trt_outputs[3][:self.batch_size*36*(img_input.shape[-1]//4)*(img_input.shape[-2]//4)]

        cls_pred = torch.from_numpy(cls_pred_data.reshape(self.batch_size,5,img_input.shape[-2]//4,img_input.shape[-1]//4))
        polar_center_ness_pred = torch.from_numpy(polar_center_ness_pred_data.reshape(self.batch_size,1,img_input.shape[-2]//4,img_input.shape[-1]//4))
        center_offset_pred = torch.from_numpy(center_offset_pred_data.reshape(self.batch_size,2,img_input.shape[-2]//4,img_input.shape[-1]//4))
        dist_pred = torch.from_numpy(dist_pred_data.reshape(self.batch_size,36,img_input.shape[-2]//4,img_input.shape[-1]//4))

        #print("cls_pred", cls_pred)

        self.cfx.pop()
        return cls_pred, polar_center_ness_pred, dist_pred, center_offset_pred

**Comment by guetzhouyanxiao** [comment]
This problem occurs when my model is dynamic dimension input, and no error occurs when the model is fixed dimension

**Comment by liwenju0** [comment]
I also encounter this problem, have U solved it?

**Comment by Qiancj0605** [comment]
> Could you share your code to run TRT in multi-thread environment?
> 
> Please note that execution context is not thread-safe. You need to create one execution context per thread.

Since trt8.4 provides a thread-safe enqueueV2 api, does it mean that an engine with multiple streams and a single context is feasible?  Thanks @nvpohanh

**Comment by Qiancj0605** [comment]
> > Could you share your code to run TRT in multi-thread environment?
> > Please note that execution context is not thread-safe. You need to create one execution context per thread.
> 
> Since trt8.4 provides a thread-safe enqueueV2 api, does it mean that an engine with multiple streams and a single context is feasible? Thanks @nvpohanh @ttyio
Recently, it has been found that multiple streams and a single context will not work，Experts please confirm！Thanks.
@nvpohanh @ttyio

**Comment by nvpohanh** [comment]
No, as of TRT 8.6, each context can only be used by one thread at a time. 

You can enable `PROFILE_SHARING_0806` preview feature so that you can create multiple execution contexts from one optimization profile, but each context should still belongs to one thread at a time.

**Comment by Qiancj0605** [comment]
> No, as of TRT 8.6, each context can only be used by one thread at a time.
> 
> You can enable `PROFILE_SHARING_0806` preview feature so that you can create multiple execution contexts from one optimization profile, but each context should still belongs to one thread at a time.

In this case（each context can only be used by one thread at a time）, if multiple streams are set, it means that there will be a corresponding number of contexts, which will cause excessive video memory usage. Is there any way to optimize it? Thanks @nvpohanh

**Comment by nvpohanh** [comment]
Well, each context has its own scratch space and intermediate buffers to store intermediate activations, and these buffers cannot be shared across multiple threads. So there is a tradeoff: more parallelism means more memory consumption.

**Comment by Qiancj0605** [comment]
It seems reasonable, but because the maintenance of intermediate buffers requires repeated creation of context, it seems unreasonable. Is it possible to create a context and then maintain multiple intermediate buffers？
For example, for a large language model, we cannot create multiple contexts due to memory problems, resulting in a lack of concurrency and the inability to make full use of the GPU.

**Comment by nvpohanh** [comment]
> Is it possible to create a context and then maintain multiple intermediate buffers？

I don't understand this part. The memory that context needs is those intermediate activation buffers. The weights are not duplicated: they are part of the engine and creating a new context does not load extra weights.

**Comment by Qiancj0605** [comment]
> I don't understand this part. The memory that context needs is those intermediate activation buffers. The weights are not duplicated: they are part of the engine and creating a new context does not load extra weights.

Let’s explain our concern through a phenomenon: Suppose creating a context and a stream requires 2G of video memory, then creating two contexts and two streams will require about 3.5G, and the increase is mainly from createExecutionContext. In theory, this part of the increased video memory should be unnecessary, right?

**Comment by nvpohanh** [comment]
In that case, you can also call [create_execution_context_without_device_memory()](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Engine.html#tensorrt.ICudaEngine.create_execution_context_without_device_memory) and allocate the intermediate buffers on your own. But the user will be responsible for not allowing two contexts to run in parallel because there may be reace conditions. 

For example, if two contexts run on the same stream and is guaranteed to never run in parallel, then you can call `create_execution_context_without_device_memory()` to create the context, allocate one GPU buffer with size equals to `engine.device_memory_size`, and set `context.device_memory` on both context so that they share the same intermediate buffers.

**Comment by Qiancj0605** [comment]
> In that case, you can also call [create_execution_context_without_device_memory()](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Engine.html#tensorrt.ICudaEngine.create_execution_context_without_device_memory) and allocate the intermediate buffers on your own. But the user will be responsible for not allowing two contexts to run in parallel because there may be reace conditions.
> 
> For example, if two contexts run on the same stream and is guaranteed to never run in parallel, then you can call `create_execution_context_without_device_memory()` to create the context, allocate one GPU buffer with size equals to `engine.device_memory_size`, and set `context.device_memory` on both context so that they share the same intermediate buffers.

Thanks,I try it.

**Comment by HuangYison** [comment]
> It seems reasonable, but because the maintenance of intermediate buffers requires repeated creation of context, it seems unreasonable. Is it possible to create a context and then maintain multiple intermediate buffers？ For example, for a large language model, we cannot create multiple contexts due to memory problems, resulting in a lack of concurrency and the inability to make full use of the GPU.

I got the same problem, have this problem solved? Multi contexts require too much device memory, like create an execution context require 1-8G device memory, which makes it difficult to create multiple contexts in parallel under multi-threading。

**Comment by HuangYison** [comment]
> No, as of TRT 8.6, each context can only be used by one thread at a time.
> 
> You can enable preview feature so that you can create multiple execution contexts from one optimization profile, but each context should still belongs to one thread at a time.`PROFILE_SHARING_0806`

In TensortRT10.1, the feature `PROFILE_SHARING_0806` is enabled default, we can create multiple execution contexts from one optimization profile, but about this `So there is a tradeoff: more parallelism means more memory consumption.`, have any good solutions for now? I tried create context with KUSER_MANAGED strategy and assign less device memory for each context, but it's failed, Could not reduce memory for single context. @nvpohanh
