### ISSUE TITLE
sample_ssd save and load engine file TensorRT5.1.5 win10

### ISSUE THREAD

**Issue by neuwangmq** [NVIDIA/TensorRT#253]
I added the following codes for serialize and save engine file
```c++
	std::ofstream p(engineFile.c_str(), std::ios::binary);
	IHostMemory* m_ModelStream = engine->serialize();
	p.write(reinterpret_cast<const char*>(m_ModelStream->data()), m_ModelStream->size());
	p.close();
```
and the following codes for load and deserialize CudaEngine
```c++
std::vector<char> trtModelStreamfromFile;	
	size_t size{ 0 };
	std::ifstream file(engine_file, std::ios::binary);
	if (file.good())
	{
		file.seekg(0, file.end);
		size = file.tellg();
		file.seekg(0, file.beg);
		trtModelStreamfromFile.resize(size);
		file.read(trtModelStreamfromFile.data(), size);
		file.close();
		//IRuntime* infer = createInferRuntime(gLogger.getTRTLogger());
		engine_ = runtime_->deserializeCudaEngine(trtModelStreamfromFile.data(), size, nullptr);
	}
```
on  GeForce RTX1080 it works.
but on  GeForce RTX2060 , it got error at 

```c++
 context_ = engine_->createExecutionContext();
```
the error is 

[**E][TRT] c:\p4sw\sw\gpgpu\MachineLearning\DIT\release\5.1\plugin\priorBoxPlugin.cpp (197) - Cuda Error in nvinfer1::plugin::PriorBox::copyToDevice: 1 (invalid argument)**

I don't know how to solve it!!!

thanks~

**Comment by rmccorm4** [comment]
Hi @neuwangmq, can you try upgrading to TensorRT 7.0 and see if this fixes your issue?

**Comment by neuwangmq** [comment]
thanks for your answer, I have found the problem. I use the5.0.2.6 to generate the calibrator file,and use the 5.1.5.0 to do the inference .after I change the 5.0.2.6 to 5.1.5.0 ,it's OK!
