### ISSUE TITLE
python3: error while loading shared libraries: libnvinfer.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nrakltx** [NVIDIA/TensorRT#2596]
## Description

I am trying to use the diffusion demo from outside the `nvidia/tensorrt:22.10-py3` image, so to understand what plugin libs need to be preloaded etc when running inference in a production environment.
For this I am building the required shared libraries from within the docker image, then running the inference code from outside.
This doesn't work and results in an error when running `demo-diffusion.py` with `LD_PRELOAD`, namely
```
python3: error while loading shared libraries: libnvinfer.so.8: cannot open shared object file: No such file or directory
```
Running `LD_PRELOAD=$TRT_OSSPATH/build/out/libnvinfer_plugin.so echo Hello World` does work, but `LD_PRELOAD=$TRT_OSSPATH/build/out/libnvinfer_plugin.so python3 -h` already fails.
I have tried `ldconfig`, adding the `out` directory to `LD_LIBRARY_PATH`, moving the `libnvinfer_plugin.so*` to `/usr/lib64` and much more, non of which have helped.

Note that running inference from *inside* the docker container that created the images **does** work, as well as from within a new `nvidia/tensorrt:22.10-py3` container.
This means something is wrong with my environment, but I can't for the life of me figure it out. I'd very much appreciate any suggestions on this topic.

Thanks in advance,

N
## Environment

**TensorRT Version**: 8.5.2.2
**NVIDIA GPU**: A100 40GB
**NVIDIA Driver Version**: 520.61.05
**CUDA Version**: 11.8
**CUDNN Version**: 
**Operating System**: debian 10
**Python Version (if applicable)**: 3.9.15
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

[These](https://file.io/iFGtZ8BLJsTh) are the files in the `build/out` directory after building everything from inside the model (one `.so` and two soft links to it).

## Steps To Reproduce
Run the steps from the [diffusion]() demo inside the relevant docker container.
Run `LD_PRELOAD=$TRT_OSSPATH/build/out/libnvinfer_plugin.so python3 -h`.

**Comment by nvpohanh** [comment]
Did you install TensorRT 8.5.2.2? https://developer.nvidia.com/tensorrt

**Comment by nrakltx** [comment]
Thank you for the prompt response!

Yes, of course, via 'pip install tensorrt==8.5.2.2`.

**Comment by nrakltx** [comment]
Thank you for the prompt response!

Yes, of course, via 'pip install tensorrt==8.5.2.2`.

**Comment by nvpohanh** [comment]
Could you run: `python3 -c "import tensorrt; print(tensorrt.__path__)"` and it should print the path to the `libnvinfer.so.8`. You can add this path to `LD_LIBRARY_PATH` environment variable.

**Comment by nrakltx** [comment]
Awesome, that was the problem, and this solved it!
For posterity purposes, I thought the issue was with the manually built library not being found, but it really was with a corrupt `tensorrt` installation, thanks!

**Comment by MadMartian** [comment]
I realize this issue is closed, but why doesn't the installation symlink the pertinent shared objects to a Unix System Resource library sub-folder?

**Comment by theanh-ktmt** [comment]
@yashcfg Thank you! That really helped me resolve the issue.
