### ISSUE TITLE
Onnx output is differs largely to TRT engine output

### ISSUE THREAD

**Issue by 1049451037** [NVIDIA/TensorRT#2691]
## Description

I have a onnx model, whose output has beed verified to be almost identical with my original PyTorch model.

After I convert it to tensorrt engine, the output changes too much.

## Environment

nvidia docker container 22.12

## Relevant Files

Here is the onnx model: https://cloud.tsinghua.edu.cn/f/8e1a7623952946c7bb76/?dl=1

## Steps To Reproduce

Use this script to reproduce:

```python
import os
import torch
import torch.nn as nn
import tensorrt as trt

TRT_LOGGER = trt.Logger()
trt.init_libnvinfer_plugins(TRT_LOGGER, '')

def load_engine(engine_file_path):
    assert os.path.exists(engine_file_path)
    print("Reading engine from file {}".format(engine_file_path))
    with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
        return runtime.deserialize_cuda_engine(f.read())

from torch.testing._internal.common_utils import numpy_to_torch_dtype_dict
def get_trt_stuff(engine_path):
    engine = load_engine(engine_path)
    context = engine.create_execution_context()
    inputs_dict = {}
    outputs_dict = {}
    bindings = []
    for binding in engine:
        binding_idx = engine.get_binding_index(binding)
        # size = trt.volume(context.get_binding_shape(binding_idx))
        dtype = trt.nptype(engine.get_binding_dtype(binding))
        shape = tuple(context.get_binding_shape(binding_idx))
        if engine.binding_is_input(binding):
            inputs_dict[binding] = torch.empty(*shape, dtype=numpy_to_torch_dtype_dict[dtype], device='cuda')
            bindings.append(int(inputs_dict[binding].data_ptr()))
        else:
            outputs_dict[binding] = torch.empty(*shape, dtype=numpy_to_torch_dtype_dict[dtype], device='cuda')
            bindings.append(int(outputs_dict[binding].data_ptr()))
    return context, bindings, inputs_dict, outputs_dict

def run_trt(context, bindings, stream=None):
    if stream is None:
        stream = torch.cuda.default_stream()
    state = context.execute_async_v2(bindings=bindings, stream_handle=stream.cuda_stream)
    stream.synchronize()
    return state

class TRTModule(nn.Module):
    def __init__(self, engine_path):
        super().__init__()
        self.context, self.bindings, self.inputs_dict, self.outputs_dict = get_trt_stuff(engine_path)
    def forward(self, *inputs, **kw_args):
        device = 'cpu'
        for i, inp in enumerate(inputs):
            self.inputs_dict['input_{}'.format(i)].copy_(inp)
            device = inp.device
        shift = len(inputs)
        for k in kw_args:
            self.inputs_dict['input_{}'.format(shift)].copy_(kw_args[k])
            shift += 1
        state = run_trt(self.context, self.bindings)
        if not state:
            raise Exception("trt engine execution failed")
        outputs = []
        for i in range(len(self.outputs_dict)):
            outputs.append(self.outputs_dict['output_{}'.format(i)].cpu().to(device))
        if len(outputs) == 1:
            outputs = outputs[0]
        return outputs

import onnxruntime as ort

def get_ort_stuff(onnx_path, providers):
    return ort.InferenceSession(onnx_path, providers=providers)

class ORTModule(nn.Module):
    def __init__(self, onnx_path, providers=['CUDAExecutionProvider', 'CPUExecutionProvider']):
        super().__init__()
        self.sess = get_ort_stuff(onnx_path, providers)
    def forward(self, *inputs, **kw_args):
        device = 'cpu'
        for inp in inputs:
            device = inp.device
        for k in kw_args:
            device = kw_args[k].device
        inputs_dict = {'input_{}'.format(i):x.cpu().numpy() if isinstance(x, torch.Tensor) else x for i, x in enumerate(inputs)}
        shift = len(inputs_dict)
        for k in kw_args:
            inputs_dict['input_{}'.format(shift)] = kw_args[k].cpu().numpy()
            shift += 1
        outputs = self.sess.run(None, inputs_dict)
        outputs = [torch.from_numpy(x).to(device) for x in outputs]
        if len(outputs) == 1:
            outputs = outputs[0]
        return outputs

input_0 = torch.randn(2, 3, 256, 256, dtype=torch.float32).cuda()
input_1 = torch.tensor([1, 3], dtype=torch.int32).cuda()
input_2 = torch.randn(2, 81, 640, dtype=torch.float32).cuda()

ort = ORTModule('onnx/EfficientUNetModel_.onnx', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
os.system('trtexec --onnx=onnx/EfficientUNetModel_.onnx --saveEngine=onnx/EfficientUNetModel_.trt --fp16 --buildOnly')
trt = TRTModule('onnx/EfficientUNetModel_.trt')
out_ort = ort(input_0, input_1, input_2)
out_trt = trt(input_0, input_1, input_2)
print((out_ort-out_trt).abs().max().item())
```

Before run it, you should `pip install onnxruntime-gpu`.

It shows the absolute error is ~4.6 that large.

**Comment by zerollzeng** [comment]
From what I see with polygraphy, the max absolute diff is only 0.00022328 .
```
[I] Accuracy Comparison | trt-runner-N0-02/18/23-15:21:41 vs. onnxrt-runner-N0-02/18/23-15:21:41
[I]     Comparing Output: 'output_0' (dtype=float32, shape=(2, 3, 256, 256)) with 'output_0' (dtype=float32, shape=(2, 3, 256, 256))
[I]         Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
[I]         trt-runner-N0-02/18/23-15:21:41: output_0 | Stats: mean=0.027493, std-dev=1.1574, var=1.3395, median=0.0010827, min=-4.9687 at (0, 0, 188, 87), max=5.004 at (1, 1, 60, 10), avg-magnitude=0.92063
[I]             ---- Histogram ----
                Bin Range        |  Num Elems | Visualization
                (-4.97 , -3.97 ) |        104 |
                (-3.97 , -2.97 ) |       1527 |
                (-2.97 , -1.98 ) |      13445 | ####
                (-1.98 , -0.98 ) |      59962 | ###################
                (-0.98 , 0.0177) |     123869 | ########################################
                (0.0177, 1.01  ) |     117847 | ######################################
                (1.01  , 2.01  ) |      57519 | ##################
                (2.01  , 3.01  ) |      16646 | #####
                (3.01  , 4.01  ) |       2189 |
                (4.01  , 5     ) |        108 |
[I]         onnxrt-runner-N0-02/18/23-15:21:41: output_0 | Stats: mean=0.027494, std-dev=1.1574, var=1.3395, median=0.0010866, min=-4.9687 at (0, 0, 188, 87), max=5.004 at (1, 1, 60, 10), avg-magnitude=0.92063
[I]             ---- Histogram ----
                Bin Range        |  Num Elems | Visualization
                (-4.97 , -3.97 ) |        104 |
                (-3.97 , -2.97 ) |       1527 |
                (-2.97 , -1.98 ) |      13444 | ####
                (-1.98 , -0.98 ) |      59964 | ###################
                (-0.98 , 0.0177) |     123867 | ########################################
                (0.0177, 1.01  ) |     117848 | ######################################
                (1.01  , 2.01  ) |      57518 | ##################
                (2.01  , 3.01  ) |      16646 | #####
                (3.01  , 4.01  ) |       2190 |
                (4.01  , 5     ) |        108 |
[I]         Error Metrics: output_0
[I]             Minimum Required Tolerance: elemwise error | [abs=0.00022328] OR [rel=0.44028] (requirements may be lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=6.7205e-06, std-dev=6.4983e-06, var=4.2228e-11, median=5.126e-06, min=0 at (0, 0, 0, 16), max=0.00022328 at (1, 1, 152, 253), avg-magnitude=6.7205e-06
[I]                 ---- Histogram ----
                    Bin Range            |  Num Elems | Visualization
                    (0       , 2.23e-05) |     383158 | ########################################
                    (2.23e-05, 4.47e-05) |       9162 |
                    (4.47e-05, 6.7e-05 ) |        671 |
                    (6.7e-05 , 8.93e-05) |        127 |
                    (8.93e-05, 0.000112) |         56 |
                    (0.000112, 0.000134) |         26 |
                    (0.000134, 0.000156) |         10 |
                    (0.000156, 0.000179) |          5 |
                    (0.000179, 0.000201) |          0 |
                    (0.000201, 0.000223) |          1 |
[I]             Relative Difference | Stats: mean=4.9736e-05, std-dev=0.0016256, var=2.6424e-06, median=6.9019e-06, min=0 at (0, 0, 0, 16), max=0.44028 at (1, 0, 85, 219), avg-magnitude=4.9736e-05
[I]                 ---- Histogram ----
                    Bin Range        |  Num Elems | Visualization
                    (0     , 0.044 ) |     393179 | ########################################
                    (0.044 , 0.0881) |         21 |
                    (0.0881, 0.132 ) |          5 |
                    (0.132 , 0.176 ) |          3 |
                    (0.176 , 0.22  ) |          3 |
                    (0.22  , 0.264 ) |          2 |
                    (0.264 , 0.308 ) |          0 |
                    (0.308 , 0.352 ) |          0 |
                    (0.352 , 0.396 ) |          1 |
                    (0.396 , 0.44  ) |          2 |
[E]         FAILED | Output: 'output_0' | Difference exceeds tolerance (rel=1e-05, abs=1e-05)
[E]     FAILED | Mismatched outputs: ['output_0']
[E] Accuracy Summary | trt-runner-N0-02/18/23-15:21:41 vs. onnxrt-runner-N0-02/18/23-15:21:41 | Passed: 0/1 iterations | Pass Rate: 0.0%
[E] FAILED | Runtime: 385.500s | Command: /usr/local/bin/polygraphy run EfficientUNetModel_.onnx --trt --onnxrt

```

**Comment by zerollzeng** [comment]
If you still think there are accuracy issue, you can try our Polygraphy tool, see https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy

**Comment by 1049451037** [comment]
Have you tried to first convert the onnx into trt using trtexec? I think this produces much error.

**Comment by SakuraRiven** [comment]
Perhaps the --noTF32 in trtexec could help?

**Comment by 1049451037** [comment]
@SakuraRiven emm... `--noTF32` works a little, but not much. The error drops from 4.6 to 3.5 now.

**Comment by 1049451037** [comment]
@SakuraRiven I tried using trtexec without `--fp16`, the error drops a lot from 3.5 to 0.11 now! Although the error is also not that tolerable for pixel values from [-1, 1]...

**Comment by 1049451037** [comment]
Is there any way to make error smaller?

**Comment by SakuraRiven** [comment]
@1049451037  Which one is your model, detection or classification? Turn off fp16 would bring normal fp32 which is nearly the same with original torch. In this way, 0.11 error is ok. As for the speed I am also confused.

**Comment by 1049451037** [comment]
My model is a diffusion model unet, which outputs the predicted pixel values of images which ranges from [-1, 1]. So 0.11 is not that ok...

**Comment by 1049451037** [comment]
Hi @zerollzeng , I used polygraphy. And the result is the same. Large error happens. My command is:

```
polygraphy run onnx/EfficientUNetModel_.onnx --trt --fp16 --onnxrt
```

The result is:

```
[I] onnxrt-runner-N0-02/21/23-13:21:06                                                                        
    ---- Inference Input(s) ----                                                                              
    {input_0 [dtype=float32, shape=(2, 3, 256, 256)],                                                         
     input_1 [dtype=int32, shape=(2,)],                                                                       
     input_2 [dtype=float32, shape=(2, 81, 640)]}                                                             
[I] onnxrt-runner-N0-02/21/23-13:21:06                                                                        
    ---- Inference Output(s) ----                                                                             
    {output_0 [dtype=float32, shape=(2, 3, 256, 256)]}                                                        
[I] onnxrt-runner-N0-02/21/23-13:21:06  | Completed 1 iteration(s) in 7196 ms | Average inference time: 7196 $
s.                                                                                                            
[I] Accuracy Comparison | trt-runner-N0-02/21/23-13:21:06 vs. onnxrt-runner-N0-02/21/23-13:21:06              
[I]     Comparing Output: 'output_0' (dtype=float32, shape=(2, 3, 256, 256)) with 'output_0' (dtype=float32, $
hape=(2, 3, 256, 256))                                                                                        
[I]         Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error                                       
[I]         trt-runner-N0-02/21/23-13:21:06: output_0 | Stats: mean=0.026445, std-dev=1.1546, var=1.3332, med$
an=0.00091553, min=-5.0312 at (0, 0, 188, 87), max=4.8164 at (1, 1, 60, 10), avg-magnitude=0.91801
[I]             ---- Histogram ----                                                                           
                Bin Range          |  Num Elems | Visualization                                               
                (-5.03  , -4.03  ) |         80 |                                                             
                (-4.03  , -3.02  ) |       1313 |                                                             
                (-3.02  , -2.02  ) |      12489 | ####                                                        
                (-2.02  , -1.02  ) |      57214 | ##################                                          
                (-1.02  , -0.0136) |     123487 | ########################################
                (-0.0136, 0.99   ) |     120372 | ######################################
                (0.99   , 1.99   ) |      58938 | ###################
                (1.99   , 3      ) |      16942 | #####
                (3      , 4      ) |       2274 |
                (4      , 5      ) |        107 |
[I]         onnxrt-runner-N0-02/21/23-13:21:06: output_0 | Stats: mean=0.027494, std-dev=1.1574, var=1.3395, $
edian=0.0010874, min=-4.9687 at (0, 0, 188, 87), max=5.004 at (1, 1, 60, 10), avg-magnitude=0.92063
[I]             ---- Histogram ----
                Bin Range          |  Num Elems | Visualization
                (-5.03  , -4.03  ) |         84 |
                (-4.03  , -3.02  ) |       1342 |
                (-3.02  , -2.02  ) |      12376 | ####
                (-2.02  , -1.02  ) |      57717 | ##################
                (-1.02  , -0.0136) |     122906 | ########################################
                (-0.0136, 0.99   ) |     120029 | #######################################
                (0.99   , 1.99   ) |      59222 | ###################
                (1.99   , 3      ) |      17178 | #####
                (3      , 4      ) |       2252 |
                (4      , 5      ) |        110 |
[I]         Error Metrics: output_0
[I]             Minimum Required Tolerance: elemwise error | [abs=2.8635] OR [rel=3744.8] (requirements may be
 lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=0.072908, std-dev=0.089021, var=0.0079247, median=0.047533,
min=2.0117e-07 at (1, 2, 89, 10), max=2.8635 at (1, 2, 210, 25), avg-magnitude=0.072908
[I]                 ---- Histogram ----
                    Bin Range         |  Num Elems | Visualization
                    (2.01e-07, 0.286) |     382812 | ########################################
                    (0.286   , 0.573) |       8826 |
                    (0.573   , 0.859) |       1111 |
                    (0.859   , 1.15 ) |        311 |
                    (1.15    , 1.43 ) |        105 |
                    (1.43    , 1.72 ) |         28 |
                    (1.72    , 2    ) |         11 |
                    (2       , 2.29 ) |          6 |
                    (2.29    , 2.58 ) |          4 |
                    (2.58    , 2.86 ) |          2 |
[I]             Relative Difference | Stats: mean=0.48615, std-dev=12.805, var=163.96, median=0.066396, min=3$
0215e-07 at (1, 0, 144, 221), max=3744.8 at (0, 2, 42, 158), avg-magnitude=0.48615
[I]                 ---- Histogram ----
                    Bin Range            |  Num Elems | Visualization
                    (3.02e-07, 374     ) |     393171 | ########################################
                    (374     , 749     ) |         26 |
                    (749     , 1.12e+03) |          8 |
                    (1.12e+03, 1.5e+03 ) |          5 |
                    (1.5e+03 , 1.87e+03) |          3 |
                    (1.87e+03, 2.25e+03) |          0 |
                    (2.25e+03, 2.62e+03) |          1 |
                    (2.62e+03, 3e+03   ) |          1 |
                    (3e+03   , 3.37e+03) |          0 |
                    (3.37e+03, 3.74e+03) |          1 |
[E]         FAILED | Output: 'output_0' | Difference exceeds tolerance (rel=1e-05, abs=1e-05)
[E]     FAILED | Mismatched outputs: ['output_0']
[E] Accuracy Summary | trt-runner-N0-02/21/23-13:21:06 vs. onnxrt-runner-N0-02/21/23-13:21:06 | Passed: 0/1 it
erations | Pass Rate: 0.0%
[E] FAILED | Runtime: 837.896s | Command: /usr/local/bin/polygraphy run onnx/EfficientUNetModel_.onnx --trt --
fp16 --onnxrt
```

**Comment by zerollzeng** [comment]
1. when use Polygraphy, it will also build the TRT engine as trtexec.
2. FP16 has a smaller range than FP32 and can introduce some numerical errors due to the lower precision. Does the FP32 difference satisfy your need? if yes then you can try to fallback some sensitive layers back to FP32.

**Comment by 1049451037** [comment]
Actually, my first goal is to speed up the inference. FP32 difference satisfy my need, but its speed is slow. I have checked my model, and there is no numerical overflow because when I use PyTorch model.half(), everything works fine. Is there any way to locate where are the sensitive layers?

**Comment by 1049451037** [comment]
This is the simplified problem for now:

I have a very simple onnx file (Where I locate the problematic sub-network): https://cloud.tsinghua.edu.cn/f/5db9c79dc5a841ada575/?dl=1

When I use `polygraphy run onnx/sample.onnx --trt --fp16 --onnxrt` to test it. The output engine makes very large error.

So how to fix this problem? @zerollzeng Thank you!

**Comment by 1049451037** [comment]
As the per-layer polygraphy `polygraphy run onnx/sample.onnx --trt --fp16 --onnxrt --trt-outputs mark all --onnx-outputs mark all` shows, InstanceNormalization contributes most error:

```
[I]     Comparing Output: '/input_blocks.1/input_blocks.1.0/in_layers.0/InstanceNormalization_output_0' (dtype=fl
oat32, shape=(2, 32, 262144)) with '/input_blocks.1/input_blocks.1.0/in_layers.0/InstanceNormalization_output_0' 
(dtype=float16, shape=(2, 32, 262144))                                                                           
[I]         Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error                                          
[I]         trt-runner-N0-02/22/23-06:48:38: /input_blocks.1/input_blocks.1.0/in_layers.0/InstanceNormalization_$
utput_0 | Stats: mean=-1.7115e-09, std-dev=0.005532, var=3.0603e-05, median=0, min=-0.042147 at (1, 13, 123060), 
max=0.045272 at (0, 11, 47871), avg-magnitude=0.0031986                                                          
[I]             ---- Histogram ----                                                                              
                Bin Range        |  Num Elems | Visualization                                                    
                (-5.38 , -4.27 ) |          0 |                                                                  
                (-4.27 , -3.15 ) |          0 |                                                                  
                (-3.15 , -2.03 ) |          0 |                                                                  
                (-2.03 , -0.916) |          0 |                                                                  
                (-0.916, 0.201 ) |   16777216 | ########################################                         
                (0.201 , 1.32  ) |          0 |                                                                  
                (1.32  , 2.43  ) |          0 |                                                                  
                (2.43  , 3.55  ) |          0 |                                                                  
                (3.55  , 4.67  ) |          0 |
                (4.67  , 5.79  ) |          0 |
[I]         onnxrt-runner-N0-02/22/23-06:48:38: /input_blocks.1/input_blocks.1.0/in_layers.0/InstanceNormalizati$
n_output_0 | Stats: mean=2.0576e-07, std-dev=0.99961, var=0.99923, median=0.053864, min=-5.3828 at (1, 13, 12306$
), max=5.7852 at (0, 11, 47871), avg-magnitude=0.82224
[I]             ---- Histogram ----
                Bin Range        |  Num Elems | Visualization
                (-5.38 , -4.27 ) |         62 |
                (-4.27 , -3.15 ) |       4321 |
                (-3.15 , -2.03 ) |     246204 | #
                (-2.03 , -0.916) |    3273482 | ######################
                (-0.916, 0.201 ) |    5860698 | ########################################
                (0.201 , 1.32  ) |    5725682 | #######################################
                (1.32  , 2.44  ) |    1631536 | ###########
                (2.44  , 3.55  ) |      34636 |
                (3.55  , 4.67  ) |        578 |
                (4.67  , 5.79  ) |         17 |
[I]         Error Metrics: /input_blocks.1/input_blocks.1.0/in_layers.0/InstanceNormalization_output_0           
[I]             Minimum Required Tolerance: elemwise error | [abs=5.7399] OR [rel=1.0935] (requirements may be lo
wer if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=0.81905, std-dev=0.56622, var=0.3206, median=0.74607, min=3.40$
4e-07 at (0, 1, 150973), max=5.7399 at (0, 11, 47871), avg-magnitude=0.81905
[I]                 ---- Histogram ----
                    Bin Range        |  Num Elems | Visualization
                    (3.4e-07, 0.574) |    6758688 | ########################################
                    (0.574  , 1.15 ) |    5077625 | ##############################
                    (1.15   , 1.72 ) |    3851361 | ######################
                    (1.72   , 2.3  ) |     936867 | #####
                    (2.3    , 2.87 ) |     134072 |
                    (2.87   , 3.44 ) |      16417 |
                    (3.44   , 4.02 ) |       1931 |
                    (4.02   , 4.59 ) |        222 |
                    (4.59   , 5.17 ) |         29 |
                    (5.17   , 5.74 ) |          4 |
[I]             Relative Difference | Stats: mean=0.99609, std-dev=0.003915, var=1.5327e-05, median=0.99998, min$
0.84108 at (1, 7, 46214), max=1.0935 at (1, 7, 112736), avg-magnitude=0.99609
[I]                 ---- Histogram ----
                    Bin Range      |  Num Elems | Visualization
                    (0.841, 0.866) |          2 |
                    (0.866, 0.892) |          2 |
                    (0.892, 0.917) |          2 |
                    (0.917, 0.942) |          5 |
                    (0.942, 0.967) |         12 |
                    (0.967, 0.993) |    8386932 | #######################################
                    (0.993, 1.02 ) |    8390241 | ########################################
                    (1.02 , 1.04 ) |         13 |
                    (1.04 , 1.07 ) |          3 |
                    (1.07 , 1.09 ) |          4 |
[E]         FAILED | Output: '/input_blocks.1/input_blocks.1.0/in_layers.0/InstanceNormalization_output_0' | Difference exceeds tolerance (rel=1e-05, abs=1e-05)
```

Is there any bug for InstanceNormalization layer in TensorRT? Because my InstanceNorm layer is a 32 group GroupNorm actually.

**Comment by zerollzeng** [comment]
Thanks, I can reproduce the numerical error and looks like it's caused by InstanceNorm, I've filed internal bug 4002778 to track this.

Thanks for reporting this!

**Comment by zerollzeng** [comment]
The issue is fixed at TRT 8.6 which will release soon. Thanks!

**Comment by 1049451037** [comment]
OK. Could official docker container provides cuda 11.x version for TRT 8.6? Since I notice that from [23.01](https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/index.html#rel-23-01), the docker container is built with cuda 12.x, which is not convenient sometimes due to cuda driver incompatibility. I really hope that both cuda 11.x and 12.x are provided!

**Comment by 1049451037** [comment]
Moreover, is there any workaround before the new release comes up? I notice there are group normalization plugins in the repo. However, they don't have any docs or readmes. I wonder if I can use them? and If yes, how?

* https://github.com/NVIDIA/TensorRT/tree/main/plugin/groupNormalizationPlugin
* https://github.com/NVIDIA/TensorRT/tree/main/plugin/groupNormPlugin

**Comment by c-schumacher** [comment]
hey @1049451037, i've often noticed this as well when converting models with normalization layers to fp16. this is a little post-processing script (based on an example from this repo) that i use to keep select operations in fp32 to avoid overflow issues. it generally fixes the issue for me with layernorms, but i've never tried it with group norm so you may need to tweak it a bit.
```
import tensorrt as trt
from tensorrt.tensorrt import IElementWiseLayer, IReduceLayer

# based on https://github.com/NVIDIA/TensorRT/blob/main/tools/Polygraphy/examples/cli/run/08_adding_precision_constraints/add_constraints.py 
def postprocess(network):
    """
    Traverses the parsed network and constrains precisions
    for specific layers to FP32.
    Args:
        network (trt.INetworkDefinition): The network to modify.
    Returns:
        None
    """

    print("Beginning post-processing...")
    for layer_index in range(network.num_layers - 1):
        layer: ILayer = network.get_layer(layer_index)
        next_layer: ILayer = network.get_layer(layer_index + 1)
        if layer.type == trt.LayerType.ELEMENTWISE and next_layer.type == trt.LayerType.REDUCE:
            # casting to get access to op attribute
            layer.__class__ = IElementWiseLayer
            next_layer.__class__ = IReduceLayer
            if layer.op == trt.ElementWiseOperation.POW:                
                layer.precision = trt.DataType.FLOAT
                next_layer.precision = trt.DataType.FLOAT
                print(f'Adjusting precision of {[layer.name](http://layer.name/)}, and {[next_layer.name](http://next_layer.name/)}')
            layer.set_output_type(index=0, dtype=trt.DataType.FLOAT)
            next_layer.set_output_type(index=0, dtype=trt.DataType.FLOAT)
```
you can try this with polygraphy conversion to trt by adding a flag:
```
--trt-network-postprocess-script=[whatever you name the above]
```
good luck! hopefully this helps
