### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/TensorRT#2835]
Hi.
When I run the TRT plugin inference code, I get the following error message. 

       File "utils/infer_visiontransformer_plugin.py", line 154, in run_trt_plugin
          torch.cuda.synchronize()
        File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 496, in synchronize
          return torch._C._cuda_synchronize()
      RuntimeError: CUDA error: an illegal memory access was encountered
      CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
      For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
      
      [03/31/2023-01:15:50] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
      [03/31/2023-01:15:50] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
      [03/31/2023-01:15:50] [TRT] [E] 1: [cudaResources.cpp::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
      Error on file ViTPlugin.cpp line 159: CUDNN_STATUS_INTERNAL_ERROR

OS: Ubuntu 18.04
GPU: 3080ti
Driver Version: 515
Python Version: 3.8
cuda Version: 11.6
cudnn Version: 8.4.1
pytorch Version: 1.12
tensorrt Version: 8.4.3.1

**Comment by zerollzeng** [comment]
Looks like bugs in the plugin, try debugging it with cuda-gdb or cuda-memcheck?

**Comment by ywfwyht** [comment]
@zerollzeng 
Could you help me check the building TRT engine log， is right ?

'''
Building TRT engine....
[04/03/2023-06:31:37] [TRT] [V] Applying generic optimizations to the graph for inference.
[04/03/2023-06:31:37] [TRT] [V] Original: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After dead-layer removal: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After Myelin optimization: 1 layers
[04/03/2023-06:31:37] [TRT] [V] Applying ScaleNodes fusions.
[04/03/2023-06:31:37] [TRT] [V] After scale fusion: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After dupe layer removal: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After final dead-layer removal: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After tensor merging: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After vertical fusions: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After dupe layer removal: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After final dead-layer removal: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After tensor merging: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After slice removal: 1 layers
[04/03/2023-06:31:37] [TRT] [V] After concat removal: 1 layers
[04/03/2023-06:31:37] [TRT] [V] Trying to split Reshape and strided tensor
[04/03/2023-06:31:37] [TRT] [V] Graph construction and optimization completed in 0.109824 seconds.
[04/03/2023-06:31:37] [TRT] [V] Using cublasLt as a tactic source
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +67, GPU +8, now: CPU 4520, GPU 3365 (MiB)
[04/03/2023-06:31:37] [TRT] [V] Using cuDNN as a tactic source
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 4520, GPU 3375 (MiB)
[04/03/2023-06:31:37] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[04/03/2023-06:31:37] [TRT] [V] Constructing optimization profile number 0 [1/1].
[04/03/2023-06:31:37] [TRT] [V] Reserving memory for host IO tensors. Host: 0 bytes
[04/03/2023-06:31:37] [TRT] [V] =============== Computing reformatting costs
[04/03/2023-06:31:37] [TRT] [V] =============== Computing reformatting costs
[04/03/2023-06:31:37] [TRT] [V] =============== Computing costs for 
[04/03/2023-06:31:37] [TRT] [V] *************** Autotuning format combination: Float(1327104,20736,144,1) -> Float(165888,512,1) ***************
[04/03/2023-06:31:37] [TRT] [V] Formats and tactics selection completed in 0.0769389 seconds.
[04/03/2023-06:31:37] [TRT] [V] After reformat layers: 1 layers
[04/03/2023-06:31:37] [TRT] [V] Pre-optimized block assignment.
[04/03/2023-06:31:37] [TRT] [V] Block size 8589934592
[04/03/2023-06:31:37] [TRT] [V] Total Activation Memory: 8589934592
[04/03/2023-06:31:37] [TRT] [I] Detected 1 inputs and 1 output network tensors.
[04/03/2023-06:31:37] [TRT] [V] Layer: (Unnamed Layer* 0) [PluginV2DynamicExt] Host Persistent: 112 Device Persistent: 0 Scratch Memory: 0
[04/03/2023-06:31:37] [TRT] [I] Total Host Persistent Memory: 112
[04/03/2023-06:31:37] [TRT] [I] Total Device Persistent Memory: 0
[04/03/2023-06:31:37] [TRT] [I] Total Scratch Memory: 0
[04/03/2023-06:31:37] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 0 MiB
[04/03/2023-06:31:37] [TRT] [V] Optimized block assignment.
[04/03/2023-06:31:37] [TRT] [I] Total Activation Memory: 0
[04/03/2023-06:31:37] [TRT] [V] Disabling unused tactic source: EDGE_MASK_CONVOLUTIONS
[04/03/2023-06:31:37] [TRT] [V] Using cublasLt as a tactic source
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 4609, GPU 3821 (MiB)
[04/03/2023-06:31:37] [TRT] [V] Using cuDNN as a tactic source
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 4609, GPU 3829 (MiB)
[04/03/2023-06:31:37] [TRT] [V] Engine generation completed in 0.829331 seconds.
[04/03/2023-06:31:37] [TRT] [V] Engine Layer Information:
Layer(PluginV2): (Unnamed Layer* 0) [PluginV2DynamicExt], Tactic: 0x0000000000000000, input_img[Float(-2,64,144,144)] -> vision_transformer_output[Float(-2,324,512)]
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[04/03/2023-06:31:37] [TRT] [V] Using cublasLt as a tactic source
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 4564, GPU 3681 (MiB)
[04/03/2023-06:31:37] [TRT] [V] Using cuDNN as a tactic source
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 4564, GPU 3689 (MiB)
[04/03/2023-06:31:37] [TRT] [V] Total per-runner device persistent memory is 0
[04/03/2023-06:31:37] [TRT] [V] Total per-runner host persistent memory is 112
[04/03/2023-06:31:37] [TRT] [V] Allocated activation device memory of size 0
[04/03/2023-06:31:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
'''

**Comment by ywfwyht** [comment]
No, inference have error, When it run the line of code torch.cuda.synchronize().

**Comment by zerollzeng** [comment]
Can you run the engine with trtexec?

**Comment by ywfwyht** [comment]
> Can you run the engine with trtexec?
Failed.
```
[04/06/2023-01:27:12] [I] TensorRT version: 8.4.3
[04/06/2023-01:27:12] [I] Engine loaded in 0.0470083 sec.
[04/06/2023-01:27:12] [I] [TRT] [MemUsageChange] Init CUDA: CPU +331, GPU +0, now: CPU 384, GPU 629 (MiB)
[04/06/2023-01:27:13] [I] [TRT] Loaded engine size: 44 MiB
[04/06/2023-01:27:13] [E] Error[1]: [pluginV2Runner.cpp::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[04/06/2023-01:27:13] [E] Error[4]: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
[04/06/2023-01:27:13] [E] Engine deserialization failed
[04/06/2023-01:27:13] [E] Got invalid engine!
[04/06/2023-01:27:13] [E] Inference set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8403] # /opt/TensorRT-8.4.3.1/bin/trtexec --loadEngine=./ViTEngine_8_16_3_2048_512_2_144_324_0.engine --dumpOutput
```

**Comment by ywfwyht** [comment]
> > [04/06/2023-01:27:13] [E] Error[1]: [pluginV2Runner.cpp::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
> 
> Please also load the plugin so with --plugins.

```
[04/07/2023-00:51:49] [I] 
[04/07/2023-00:51:49] [I] === Performance summary ===
[04/07/2023-00:51:49] [I] Throughput: 582.185 qps
[04/07/2023-00:51:49] [I] Latency: min = 1.77612 ms, max = 2.04077 ms, mean = 1.84071 ms, median = 1.83154 ms, percentile(99%) = 1.96692 ms
[04/07/2023-00:51:49] [I] Enqueue Time: min = 0.109863 ms, max = 0.999512 ms, mean = 0.196183 ms, median = 0.154297 ms, percentile(99%) = 0.664062 ms
[04/07/2023-00:51:49] [I] H2D Latency: min = 0.137329 ms, max = 0.324707 ms, mean = 0.15187 ms, median = 0.144562 ms, percentile(99%) = 0.221436 ms
[04/07/2023-00:51:49] [I] GPU Compute Time: min = 1.53156 ms, max = 1.62109 ms, mean = 1.56025 ms, median = 1.55817 ms, percentile(99%) = 1.58984 ms
[04/07/2023-00:51:49] [I] D2H Latency: min = 0.0708008 ms, max = 0.250488 ms, mean = 0.128594 ms, median = 0.124023 ms, percentile(99%) = 0.181396 ms
[04/07/2023-00:51:49] [I] Total Host Walltime: 2.5284 s
[04/07/2023-00:51:49] [I] Total GPU Compute Time: 2.29668 s
[04/07/2023-00:51:49] [I] Explanations of the performance metrics are printed in the verbose logs.
[04/07/2023-00:51:49] [I] 
&&&& PASSED TensorRT.trtexec [TensorRT v8403] # /opt/TensorRT-8.4.3.1/bin/trtexec --loadEngine=./ViTEngine_16_12_3_3072_768_2_384_576_0.engine --plugins=./build/lib/libvit_plugin.so
```
Thanks. It passed.

**Comment by zerollzeng** [comment]
> No, inference have error, When it run the line of code torch.cuda.synchronize().

If it can pass with trtexec then the engine is good, maybe you should not use torch.cuda.synchronize?

**Comment by ywfwyht** [comment]
> > No, inference have error, When it run the line of code torch.cuda.synchronize().
> 
> If it can pass with trtexec then the engine is good, maybe you should not use torch.cuda.synchronize?

Now, The problem has been fixed.

**Comment by jeethesh-pai** [comment]
> 

Hi, I am encountering the same error. But in my case using --plugins does not help. Can you tell me how to execute cuda-memcheck on the custom plugin
