### ISSUE TITLE
Dependency to cudnn of trtexec (TensorRT 8.6)

### ISSUE THREAD

**Issue by jaehyuck0103** [NVIDIA/TensorRT#2908]
## Description

From the TensorRT 8.6 Release Note, cuDNN looks not a default tactic source anymore.
I usually use the prebuilt trtexec in the TensorRT release.

1. 
Even though I tune off the cuDNN tactic option (`--tacticSources=-CUDNN`), trtexec still requires the cuDNN library.
`[E] Uncaught exception detected: Unable to open library: libnvinfer_plugin.so.8 due to libcudnn.so.8: cannot open shared object file: No such file or directory`

When turning off the cuDNN tactic option, is it possible to change it to not require the cuDNN library?

2.
The default `tacticSources` option of the trtexec is `all available tactics`.
How about removing cuDNN from the default option to align with tensorrt's new plan?

## Environment

**TensorRT Version**: 8.6.0.12
**NVIDIA GPU**: 3090
**NVIDIA Driver Version**:  530.30.02
**CUDA Version**: 12.1
**Operating System**: Ubuntu 22.04

**Comment by zerollzeng** [comment]
@nvpohanh I think the `[E] Uncaught exception detected: Unable to open library: libnvinfer_plugin.so.8 due to libcudnn.so.8: cannot open shared object file: No such file or directory` error comes from TRT plugins, am I correct?

**Comment by jaehyuck0103** [comment]
@zerollzeng 

I attach a detailed log.
When not using the cudnn tactic source, can we remove the dependency on the cudnn library?

``` sh-session
foo@bar:~/TensorRT-8.6.0.12/bin$ ./trtexec --onnx=my.onnx --saveEngine=my.trt --tacticSources=-CUDNN
&&&& RUNNING TensorRT.trtexec [TensorRT v8600] # ./trtexec --onnx=my.onnx --saveEngine=my.trt --tacticSources=-CUDNN
[04/29/2023-01:57:21] [I] === Model Options ===
[04/29/2023-01:57:21] [I] Format: ONNX
[04/29/2023-01:57:21] [I] Model: my.onnx
[04/29/2023-01:57:21] [I] Output:
[04/29/2023-01:57:21] [I] === Build Options ===
[04/29/2023-01:57:21] [I] Max batch: explicit batch
[04/29/2023-01:57:21] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[04/29/2023-01:57:21] [I] minTiming: 1
[04/29/2023-01:57:21] [I] avgTiming: 8
[04/29/2023-01:57:21] [I] Precision: FP32
[04/29/2023-01:57:21] [I] LayerPrecisions:
[04/29/2023-01:57:21] [I] Layer Device Types:
[04/29/2023-01:57:21] [I] Calibration:
[04/29/2023-01:57:21] [I] Refit: Disabled
[04/29/2023-01:57:21] [I] Version Compatible: Disabled
[04/29/2023-01:57:21] [I] TensorRT runtime: full
[04/29/2023-01:57:21] [I] Lean DLL Path:
[04/29/2023-01:57:21] [I] Tempfile Controls: { in_memory: allow, temporary: allow }
[04/29/2023-01:57:21] [I] Exclude Lean Runtime: Disabled
[04/29/2023-01:57:21] [I] Sparsity: Disabled
[04/29/2023-01:57:21] [I] Safe mode: Disabled
[04/29/2023-01:57:21] [I] DirectIO mode: Disabled
[04/29/2023-01:57:21] [I] Restricted mode: Disabled
[04/29/2023-01:57:21] [I] Skip inference: Disabled
[04/29/2023-01:57:21] [I] Save engine: my.trt
[04/29/2023-01:57:21] [I] Load engine:
[04/29/2023-01:57:21] [I] Profiling verbosity: 0
[04/29/2023-01:57:21] [I] Tactic sources: cudnn [OFF],
[04/29/2023-01:57:21] [I] timingCacheMode: local
[04/29/2023-01:57:21] [I] timingCacheFile:
[04/29/2023-01:57:21] [I] Heuristic: Disabled
[04/29/2023-01:57:21] [I] Preview Features: Use default preview flags.
[04/29/2023-01:57:21] [I] MaxAuxStreams: -1
[04/29/2023-01:57:21] [I] BuilderOptimizationLevel: 3
[04/29/2023-01:57:21] [I] Input(s)s format: fp32:CHW
[04/29/2023-01:57:21] [I] Output(s)s format: fp32:CHW
[04/29/2023-01:57:21] [I] Input build shapes: model
[04/29/2023-01:57:21] [I] Input calibration shapes: model
[04/29/2023-01:57:21] [I] === System Options ===
[04/29/2023-01:57:21] [I] Device: 0
[04/29/2023-01:57:21] [I] DLACore:
[04/29/2023-01:57:21] [I] Plugins:
[04/29/2023-01:57:21] [I] setPluginsToSerialize:
[04/29/2023-01:57:21] [I] dynamicPlugins:
[04/29/2023-01:57:21] [I] ignoreParsedPluginLibs: 0
[04/29/2023-01:57:21] [I]
[04/29/2023-01:57:21] [I] === Inference Options ===
[04/29/2023-01:57:21] [I] Batch: Explicit
[04/29/2023-01:57:21] [I] Input inference shapes: model
[04/29/2023-01:57:21] [I] Iterations: 10
[04/29/2023-01:57:21] [I] Duration: 3s (+ 200ms warm up)
[04/29/2023-01:57:21] [I] Sleep time: 0ms
[04/29/2023-01:57:21] [I] Idle time: 0ms
[04/29/2023-01:57:21] [I] Inference Streams: 1
[04/29/2023-01:57:21] [I] ExposeDMA: Disabled
[04/29/2023-01:57:21] [I] Data transfers: Enabled
[04/29/2023-01:57:21] [I] Spin-wait: Disabled
[04/29/2023-01:57:21] [I] Multithreading: Disabled
[04/29/2023-01:57:21] [I] CUDA Graph: Disabled
[04/29/2023-01:57:21] [I] Separate profiling: Disabled
[04/29/2023-01:57:21] [I] Time Deserialize: Disabled
[04/29/2023-01:57:21] [I] Time Refit: Disabled
[04/29/2023-01:57:21] [I] NVTX verbosity: 0
[04/29/2023-01:57:21] [I] Persistent Cache Ratio: 0
[04/29/2023-01:57:21] [I] Inputs:
[04/29/2023-01:57:21] [I] === Reporting Options ===
[04/29/2023-01:57:21] [I] Verbose: Disabled
[04/29/2023-01:57:21] [I] Averages: 10 inferences
[04/29/2023-01:57:21] [I] Percentiles: 90,95,99
[04/29/2023-01:57:21] [I] Dump refittable layers:Disabled
[04/29/2023-01:57:21] [I] Dump output: Disabled
[04/29/2023-01:57:21] [I] Profile: Disabled
[04/29/2023-01:57:21] [I] Export timing to JSON file:
[04/29/2023-01:57:21] [I] Export output to JSON file:
[04/29/2023-01:57:21] [I] Export profile to JSON file:
[04/29/2023-01:57:21] [I]
[04/29/2023-01:57:21] [I] === Device Information ===
[04/29/2023-01:57:21] [I] Selected Device: NVIDIA GeForce RTX 3090
[04/29/2023-01:57:21] [I] Compute Capability: 8.6
[04/29/2023-01:57:21] [I] SMs: 82
[04/29/2023-01:57:21] [I] Device Global Memory: 24259 MiB
[04/29/2023-01:57:21] [I] Shared Memory per SM: 100 KiB
[04/29/2023-01:57:21] [I] Memory Bus Width: 384 bits (ECC disabled)
[04/29/2023-01:57:21] [I] Application Compute Clock Rate: 1.695 GHz
[04/29/2023-01:57:21] [I] Application Memory Clock Rate: 9.751 GHz
[04/29/2023-01:57:21] [I]
[04/29/2023-01:57:21] [I] Note: The application clock rates do not reflect the actual clock rates that the GPU is currently running at.
[04/29/2023-01:57:21] [I]
[04/29/2023-01:57:21] [I] TensorRT version: 8.6.0
[04/29/2023-01:57:21] [I] Loading standard plugins
[04/29/2023-01:57:21] [E] Uncaught exception detected: Unable to open library: libnvinfer_plugin.so.8 due to libcudnn.so.8: cannot open shared object file: No such file or directory
&&&& FAILED TensorRT.trtexec [TensorRT v8600] # ./trtexec --onnx=my.onnx --saveEngine=my.trt --tacticSources=-CUDNN
```

**Comment by nvpohanh** [comment]
The plugins still depend on CUDNN in TRT 8.6, but not the TRT core (libnvinfer.so). We are going to remove this dependency in the future as well.

**Comment by lixhk** [comment]
@jaehyuck0103   If you use cudnn tactic, run follow cmd: `./trtexec --onnx=my.onnx --saveEngine=my.trt  --verbose`   , it will report error ?    If still error, you can upload log

**Comment by chrjxj** [comment]
> The plugins still depend on CUDNN in TRT 8.6, but not the TRT core (libnvinfer.so). We are going to remove this dependency in the future as well.

may i ask which TRT version, we could remove this dependency? thank you.

**Comment by zerollzeng** [comment]
> does it mean that, if plugins don't use cudnn, 

Yes, if you don't load our prebuilt TRT plugins.

> and we disable tactic sources using DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805, in runtime, we could avoid install cudnn/cublass libs?

I think it's https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a9e1d81e5a8bfeb38b86e22a66d5f836a

> may i ask which TRT version, we could remove this dependency?

We already removed it in core lib, not sure about plugins, maybe in TRT 10.

**Comment by aqeeljanjua** [comment]
I have found the Solution if you are using Windows. Add `C:/TensorRT-x.x.x.x/` and `C:/TensorRT-x.x.x.x/lib`  to the path. replace x.x.x.x with your versions
