### ISSUE TITLE
nn.Embedding() exported engine only works on 1st sample of every batch

### ISSUE THREAD

**Issue by prikmm** [NVIDIA/TensorRT#3004]
## Description

I  am working on a Feed Forward Transformer model which contains `nn.Embedding()` as its first layer. After converting the entire model to engine, I found the model was only giving correct output for 1st sample of every batch. I separated all the major components with `nn.Embedding` being the first one. 

When I created `nn.Embedding` to engine, I found that the converted engine only performs on 1st Sample of every batch. 
Eg: 

```
# Batch of 2 same samples.
Inputs: tensor([[99,  9, 18,  7, 75, 19, 16, 79, 86, 26, 84, 20, 93, 43, 19, 91, 11, 37,
         74, 33, 62, 32, 84, 62],
        [99,  9, 18,  7, 75, 19, 16, 79, 86, 26, 84, 20, 93, 43, 19, 91, 11, 37,
         74, 33, 62, 32, 84, 62]], device='cuda:0', dtype=torch.int32)
Sample Input Shape:  torch.Size([2, 24])

TensorRT Output: 
 tensor([[[ 1.1833, -0.5865,  0.1120,  ..., -1.6805,  1.1251, -0.8562],
         [-0.2279, -0.5442,  0.4009,  ...,  1.0756,  0.8656,  0.1123],
         [ 0.9833, -0.3362, -0.4182,  ...,  0.3714,  0.3207, -1.0970],
         ...,
         [-0.4601, -0.7182,  1.1472,  ...,  0.6628, -0.1934,  1.3754],
         [-0.8550,  0.6012,  0.8912,  ...,  1.7152,  1.0759,  1.6254],
         [-0.1336, -0.1680,  0.3406,  ...,  0.0943, -2.1272, -1.2128]],
                                                              ---------------Output of 2nd Sample is all Zeroes
        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],
       device='cuda:0')
TensorRT Output Shape:  torch.Size([2, 24, 512])

```

## Desired Output:
```
 tensor([[[ 1.1833, -0.5865,  0.1120,  ..., -1.6805,  1.1251, -0.8562],
         [-0.2279, -0.5442,  0.4009,  ...,  1.0756,  0.8656,  0.1123],
         [ 0.9833, -0.3362, -0.4182,  ...,  0.3714,  0.3207, -1.0970],
         ...,
         [-0.4601, -0.7182,  1.1472,  ...,  0.6628, -0.1934,  1.3754],
         [-0.8550,  0.6012,  0.8912,  ...,  1.7152,  1.0759,  1.6254],
         [-0.1336, -0.1680,  0.3406,  ...,  0.0943, -2.1272, -1.2128]],
                                                            ---------------Output of 2nd Sample should be same as 1st Sample
        [[ 1.1833, -0.5865,  0.1120,  ..., -1.6805,  1.1251, -0.8562],
         [-0.2279, -0.5442,  0.4009,  ...,  1.0756,  0.8656,  0.1123],
         [ 0.9833, -0.3362, -0.4182,  ...,  0.3714,  0.3207, -1.0970],
         ...,
         [-0.4601, -0.7182,  1.1472,  ...,  0.6628, -0.1934,  1.3754],
         [-0.8550,  0.6012,  0.8912,  ...,  1.7152,  1.0759,  1.6254],
         [-0.1336, -0.1680,  0.3406,  ...,  0.0943, -2.1272, -1.2128]]],
       device='cuda:0')
```

## Environment

**TensorRT Version**:  8.6.1 / 8.5.3.1

**NVIDIA GPU**:  Tesla T4 16GB

**NVIDIA Driver Version**:  530.30.02

**CUDA Version**:  12.1.66

**CUDNN Version**:  

Operating System: Ubuntu 20.04.5 LTS

Python Version (if applicable):  3.8.10

Tensorflow Version (if applicable): N/A
 
PyTorch Version (if applicable): 1.13.1+cu117

Baremetal or Container (if so, version):  nvcr.io/nvidia/tensorrt:23.04-py3

## Relevant Files

**Reproducible Script**: 
**CODE**
```python
import torch
import onnx
import tensorrt as trt
from cuda import cuda, cudart, nvrtc       # Using Cuda Python
import os
import onnxruntime as ort

print("Torch Version: ", torch.__version__)
print("Onnx Version: ", onnx.__version__)
print("TensorRT Version: ", trt.__version__)
print("OnnxRuntime Version: ", ort.__version__)

# Initialize CUDA Driver API
err, = cuda.cuInit(0)

# Retrieve handle for device 0
err, cuDevice = cuda.cuDeviceGet(0)

# Create context
err, context = cuda.cuCtxCreate(0, cuDevice)

def ASSERT_DRV(err):
    if isinstance(err, cuda.CUresult):
        if err != cuda.CUresult.CUDA_SUCCESS:   
            raise RuntimeError("Cuda Error: {}".format(err))
    elif isinstance(err, nvrtc.nvrtcResult):
        if err != nvrtc.nvrtcResult.NVRTC_SUCCESS:
            raise RuntimeError("Nvrtc Error: {}".format(err))
    else:
        raise RuntimeError("Unknown error type: {}".format(err))

def load_model(trt_engine_file):
    trt_logger = trt.Logger()
    trt_logger.min_severity = trt.Logger.VERBOSE
   
    with open(trt_engine_file, "rb") as f:
        trt_runtime = trt.Runtime(trt_logger)
        trt_engine = trt_runtime.deserialize_cuda_engine(f.read())
        trt_context = trt_engine.create_execution_context()

    return {
        "runtime": trt_runtime,
        "engine": trt_engine,
        "context": trt_context
    }

def allocate_binding_buffer(types_dict, shapes_dict):
    '''
    Allocate binding buffers for trt based on provided types and shapes dict
    '''
    return {
        k: torch.empty(
            size=shape,
            dtype=types_dict[k],
            device='cuda',
        )
        for k, shape in shapes_dict.items()
    }

def _allocate_memory(model):
    # print(model)
    """Helper function for binding several inputs at once and pre-allocating the results."""
    # Allocate memories as 1D linear buffers for simpler handling of dynamic shapes.
    inputs = allocate_binding_buffer(model["dim_specs"]["input_types"], model["dim_specs"]["input_shapes"])
    outputs = allocate_binding_buffer(model["dim_specs"]["output_types"], model["dim_specs"]["output_shapes"])

    bindings = [None] * model["engine"].num_bindings
    device_memory_addresses = {}
    for binding in model["engine"]:
        binding_idx = model["engine"].get_binding_index(binding)
        dtype = trt.nptype(model["engine"].get_binding_dtype(binding))

        if model["engine"].binding_is_input(binding):
            bindings[binding_idx] = int(inputs[binding].data_ptr())
            device_memory_addresses[binding] = int(inputs[binding].data_ptr())
        else:
            bindings[binding_idx] = int(outputs[binding].data_ptr())
            device_memory_addresses[binding] = int(outputs[binding].data_ptr())

    return {
        "bindings": bindings,
        "inputs": inputs,
        "outputs": outputs,
        "device_mem_address": device_memory_addresses
    }

def load_trt_models(trt_path, model_dim_specs):
    model = load_model(trt_path)
    model["data_stream"] = {}
    for binding in model["engine"]:
        err, model["data_stream"][binding] = cuda.cuStreamCreate(1)
    err, model["model_stream"] = cuda.cuStreamCreate(1)
    model["dim_specs"] = model_dim_specs
    model["io"] = _allocate_memory(model)
    return model

def release_trt_resources(model):
    for binding in model["engine"]:
        err, = cuda.cuStreamDestroy(model["data_stream"][binding])

    for node in model["io"]["device_mem_address"].keys():
        err, = cuda.cuMemFree(model["io"]["device_mem_address"][node])    

    err, = cuda.cuStreamDestroy(model["model_stream"])    
    return True

def export_onnx(emb):
    torch.onnx.export(
        model=emb,
        args=(sample),
        f="/tmp/emb.onnx",
        export_params=True,
        opset_version=16,
        do_constant_folding=True,
        input_names=['x'],
        output_names=['x_emb'],
        dynamic_axes={
            'x': {0: 'bs', 1: 'sequence_length'},
        },
        verbose=False,
    )

    onnx_model = onnx.load("/tmp/emb.onnx")
    onnx.checker.check_model(onnx_model)
    return True

def build_engine(onnx_model_path, engine_model_path, dim_specs):

    trt_logger = trt.Logger(trt.Logger.ERROR)
    builder = trt.Builder(trt_logger)
    network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
    profile = builder.create_optimization_profile()
    config = builder.create_builder_config()
    config.builder_optimization_level = 5   # comment this out if you are using tensorrt-8.5.3.1

    profile = builder.create_optimization_profile()

    for input_name, dims in dim_specs.items():
        profile.set_shape(input_name, dims["min"], dims["opt"], dims["max"])
    config.add_optimization_profile(profile)

    parser = trt.OnnxParser(network, trt_logger)
    if not os.path.exists(onnx_model_path):
        print("Failed finding ONNX file!")
        exit()
    print("Succeeded finding ONNX file!")
    with open(onnx_model_path, "rb") as model:
        if not parser.parse(model.read()):
            print("Failed parsing .onnx file!")
            for error in range(parser.num_errors):
            	print(parser.get_error(error))
            exit()
        print("Succeeded parsing .onnx file!")

    # Write engine
    engineString = builder.build_serialized_network(network, config)
    if engineString == None:
        print("Failed building engine!")
        exit()
    print("Succeeded building engine!")
    with open(engine_model_path, "wb") as f:
        f.write(engineString)

    return True

if __name__ == "__main__":
    sample = torch.randint(0, 100, (24,), dtype=torch.int32)
    sample = sample.repeat(2, 1).to("cuda")

    bs_to_use = sample.shape[0]

    # Checking Sample
    print("Sample Input: \n", sample)
    print("Sample Input Shape: ", sample.shape)
    
    emb = torch.nn.Embedding(101, 512).to('cuda')

    with torch.no_grad():
        emb_sample = emb(sample)

    # Checking torch output
    print("\n\nTorch Output: \n", emb_sample)
    print("Torch Output Shape: ", emb_sample.shape)

    # Exporting ONNX File
    export_onnx(emb)

    # Running ORT
    emb_sess = ort.InferenceSession("/tmp/emb.onnx", providers=["CPUExecutionProvider"])
    ort_out = emb_sess.run(["x_emb"], {"x": sample.cpu().numpy()})

    # Checking ORT output
    print("\n\nOnnxRuntime Output: \n", ort_out[0])
    print("OnnxRuntime Output Shape: ", ort_out[0].shape)

    # Building TensorRT Engine
    dim_specs = {
        "x": {
            "min": (1, 1),
            "opt": (2, 24),
            "max": (6, 400),    
        },
    }
    
    build_engine( "/tmp/emb.onnx", "/tmp/emb.engine", dim_specs )

    # Running TensorRT Engine
    max_bs = 6
    max_sequence_length = 400
    encoder_hidden_size = 512
    max_decoder_sequence_length = 817

    embedding_dim_specs = {
        "input_shapes": {
            "x": (max_bs, max_sequence_length),
        },
        "input_types": {
            "x": torch.int32,
        },
        "output_shapes": {
            "x_emb": (max_bs, max_sequence_length, encoder_hidden_size),
        },
        "output_types": {
            "x_emb": torch.float32,
        }
    }

    emb_engine = load_trt_models("/tmp/emb.engine", embedding_dim_specs)

    emb_engine["io"]["inputs"]["x"][:bs_to_use, :sample.shape[1]] = sample[:bs_to_use, :]

    emb_engine["context"].set_binding_shape(emb_engine["engine"].get_binding_index("x"), 
                                            emb_engine["io"]["inputs"]["x"][:bs_to_use, :sample.shape[1]].shape)

    assert emb_engine["context"].all_binding_shapes_specified

    emb_engine["context"].execute_v2(bindings=emb_engine["io"]["bindings"])

    # Checking TensorRT Output
    print("\n\nTensorRT Output: \n", emb_engine["io"]["outputs"]["x_emb"][:bs_to_use, :sample.shape[1], :])
    print("TensorRT Output Shape: ", emb_engine["io"]["outputs"]["x_emb"][:bs_to_use, :sample.shape[1], :].shape)

    release_trt_resources(emb_engine) 
```

**OUTPUT**
```bash
Torch Version:  1.13.1+cu117
Onnx Version:  1.14.0
TensorRT Version:  8.6.1
OnnxRuntime Version:  1.14.1
Sample Input: 
 tensor([[99,  9, 18,  7, 75, 19, 16, 79, 86, 26, 84, 20, 93, 43, 19, 91, 11, 37,
         74, 33, 62, 32, 84, 62],
        [99,  9, 18,  7, 75, 19, 16, 79, 86, 26, 84, 20, 93, 43, 19, 91, 11, 37,
         74, 33, 62, 32, 84, 62]], device='cuda:0', dtype=torch.int32)
Sample Input Shape:  torch.Size([2, 24])


Torch Output: 
 tensor([[[ 1.1833, -0.5865,  0.1120,  ..., -1.6805,  1.1251, -0.8562],
         [-0.2279, -0.5442,  0.4009,  ...,  1.0756,  0.8656,  0.1123],
         [ 0.9833, -0.3362, -0.4182,  ...,  0.3714,  0.3207, -1.0970],
         ...,
         [-0.4601, -0.7182,  1.1472,  ...,  0.6628, -0.1934,  1.3754],
         [-0.8550,  0.6012,  0.8912,  ...,  1.7152,  1.0759,  1.6254],
         [-0.1336, -0.1680,  0.3406,  ...,  0.0943, -2.1272, -1.2128]],

        [[ 1.1833, -0.5865,  0.1120,  ..., -1.6805,  1.1251, -0.8562],
         [-0.2279, -0.5442,  0.4009,  ...,  1.0756,  0.8656,  0.1123],
         [ 0.9833, -0.3362, -0.4182,  ...,  0.3714,  0.3207, -1.0970],
         ...,
         [-0.4601, -0.7182,  1.1472,  ...,  0.6628, -0.1934,  1.3754],
         [-0.8550,  0.6012,  0.8912,  ...,  1.7152,  1.0759,  1.6254],
         [-0.1336, -0.1680,  0.3406,  ...,  0.0943, -2.1272, -1.2128]]],
       device='cuda:0')
Torch Output Shape:  torch.Size([2, 24, 512])


OnnxRuntime Output: 
 [[[ 1.18328    -0.586496    0.11195648 ... -1.6804901   1.1251241
   -0.85622495]
  [-0.22791901 -0.5442395   0.40086353 ...  1.0756072   0.8656352
    0.11226153]
  [ 0.98330826 -0.3361731  -0.41822764 ...  0.37136513  0.3207118
   -1.0970485 ]
  ...
  [-0.46010497 -0.7182297   1.1472144  ...  0.6627938  -0.19339955
    1.3754063 ]
  [-0.855008    0.60119826  0.8911529  ...  1.7151649   1.0758748
    1.6254461 ]
  [-0.13360038 -0.16802871  0.340648   ...  0.09429066 -2.1272085
   -1.2128183 ]]

 [[ 1.18328    -0.586496    0.11195648 ... -1.6804901   1.1251241
   -0.85622495]
  [-0.22791901 -0.5442395   0.40086353 ...  1.0756072   0.8656352
    0.11226153]
  [ 0.98330826 -0.3361731  -0.41822764 ...  0.37136513  0.3207118
   -1.0970485 ]
  ...
  [-0.46010497 -0.7182297   1.1472144  ...  0.6627938  -0.19339955
    1.3754063 ]
  [-0.855008    0.60119826  0.8911529  ...  1.7151649   1.0758748
    1.6254461 ]
  [-0.13360038 -0.16802871  0.340648   ...  0.09429066 -2.1272085
   -1.2128183 ]]]
OnnxRuntime Output Shape:  (2, 24, 512)
Succeeded finding ONNX file!
Succeeded parsing .onnx file!
Succeeded building engine!
[05/24/2023-07:07:37] [TRT] [I] Loaded engine size: 0 MiB
[05/24/2023-07:07:37] [TRT] [V] Deserialization required 8893 microseconds.
[05/24/2023-07:07:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[05/24/2023-07:07:37] [TRT] [V] Total per-runner device persistent memory is 0
[05/24/2023-07:07:37] [TRT] [V] Total per-runner host persistent memory is 32
[05/24/2023-07:07:37] [TRT] [V] Allocated activation device memory of size 0
[05/24/2023-07:07:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[05/24/2023-07:07:37] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
TTS/code/trt-codebase/embedding_issue.py:70: DeprecationWarning: Use get_tensor_name instead.
  binding_idx = model["engine"].get_binding_index(binding)
TTS/code/trt-codebase/embedding_issue.py:71: DeprecationWarning: Use get_tensor_dtype instead.
  dtype = trt.nptype(model["engine"].get_binding_dtype(binding))
TTS/code/trt-codebase/embedding_issue.py:73: DeprecationWarning: Use get_tensor_mode instead.
  if model["engine"].binding_is_input(binding):
TTS/code/trt-codebase/embedding_issue.py:232: DeprecationWarning: Use get_tensor_name instead.
  emb_engine["context"].set_binding_shape(emb_engine["engine"].get_binding_index("x"),
TTS/code/trt-codebase/embedding_issue.py:232: DeprecationWarning: Use set_input_shape instead.
  emb_engine["context"].set_binding_shape(emb_engine["engine"].get_binding_index("x"),


TensorRT Output: 
 tensor([[[ 1.1833, -0.5865,  0.1120,  ..., -1.6805,  1.1251, -0.8562],
         [-0.2279, -0.5442,  0.4009,  ...,  1.0756,  0.8656,  0.1123],
         [ 0.9833, -0.3362, -0.4182,  ...,  0.3714,  0.3207, -1.0970],
         ...,
         [-0.4601, -0.7182,  1.1472,  ...,  0.6628, -0.1934,  1.3754],
         [-0.8550,  0.6012,  0.8912,  ...,  1.7152,  1.0759,  1.6254],
         [-0.1336, -0.1680,  0.3406,  ...,  0.0943, -2.1272, -1.2128]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],
       device='cuda:0')
TensorRT Output Shape:  torch.Size([2, 24, 512])

```

**Comment by prikmm** [comment]
@zerollzeng Sorry for the delay in response. I solved this.

The issue was not with dynamic shapes but the way memory was being parsed by TensorRT.

Example:
```python
t = torch.tensor([[0., 1., 2.],  [0., 1., 2.], [0., 1., 2.]], device="cuda")
print(t)
tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]], device='cuda:0')
```
Now, tensor will be stored in a linear fashion in the memory with `row-major` format.

Now, suppose there is a `TensorRT` module. And I want to input `t[:2, :2]` as input to the module.

If I set the shape as `[2, 2]` then, `TensorRT` will read the 2 elements in `row-major` format i.e. 
```
[[0, 1, 2],
 [0]]
```
Instead of:
```
[[0, 1]
 [0, 1]]
```

This was the issue here.

#### Solution:
 Use a flat tensor of shape (bs_to_use * max_sequence_length) . This will allocate the memory + handle element insertion in row-major fashion.
