### ISSUE TITLE
Error Code 1: Myelin (CUDA error700) failure of TensorRT 8.4.0.6 when running lstm on GPU T4

### ISSUE THREAD

**Issue by tzhang2014** [NVIDIA/TensorRT#3167]
## Environment

**TensorRT Version**: 8.4.0.6

**NVIDIA GPU**: T4

**NVIDIA Driver Version**:440.33.01

**CUDA Version**:10.2

**CUDNN Version**:8.3.2

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:
[lstm.zip](https://github.com/NVIDIA/TensorRT/files/12180731/lstm.zip)

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by zerollzeng** [comment]
I've filed internal bug 4215913 to track this.

**Comment by bigmover** [comment]
> I've filed internal bug 4215913 to track this.

the question is sloved?

**Comment by zerollzeng** [comment]
The issue has been fixed in TRT 9.0, you can try the latest TRT 9.2

Link
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-11.8.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-12.2.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.ubuntu-22.04.aarch64-gnu.cuda-12.2.tar.gz
