### ISSUE TITLE
&&&& FAILED TensorRT.trtexec [TensorRT v8402] # tensorrt/bin/trtexec --onnx=/models/converted.onnx --saveEngine=engine.trt --useCudaGraph

### ISSUE THREAD

**Issue by imenselmi** [NVIDIA/TensorRT#3183]
## Environment

**TensorRT docker version  version**: 22.08

**TensorRT version**: 8.4.2.

**NVIDIA GPU**:NVIDIA GeForce GTX 1650 Ti GPU

**Memory**: 15.4 GiB

**NVIDIA Driver Version**:520.61.05

**CUDA Version**:11.08

Operating System:Ubuntu 20.04 LTS 

Python Version:3.8.10

PyTorch Version in docker container : 1.9.0

ONNX Version in docker container: 1.9.0

ONNX Runtime Version in docker container: 1.8.1

The   error : 
&&&& RUNNING TensorRT.trtexec [TensorRT v8402] # tensorrt/bin/trtexec --onnx=/models/converted.onnx --saveEngine=engine.trt --useCudaGraph
[08/02/2023-19:24:24] [I] === Model Options ===
[08/02/2023-19:24:24] [I] Format: ONNX
[08/02/2023-19:24:24] [I] Model: /models/converted.onnx
[08/02/2023-19:24:24] [I] Output:
[08/02/2023-19:24:24] [I] === Build Options ===
[08/02/2023-19:24:24] [I] Max batch: explicit batch
[08/02/2023-19:24:24] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[08/02/2023-19:24:24] [I] minTiming: 1
[08/02/2023-19:24:24] [I] avgTiming: 8
[08/02/2023-19:24:24] [I] Precision: FP32
[08/02/2023-19:24:24] [I] LayerPrecisions: 
[08/02/2023-19:24:24] [I] Calibration: 
[08/02/2023-19:24:24] [I] Refit: Disabled
[08/02/2023-19:24:24] [I] Sparsity: Disabled
[08/02/2023-19:24:24] [I] Safe mode: Disabled
[08/02/2023-19:24:24] [I] DirectIO mode: Disabled
[08/02/2023-19:24:24] [I] Restricted mode: Disabled
[08/02/2023-19:24:24] [I] Build only: Disabled
[08/02/2023-19:24:24] [I] Save engine: engine.trt
[08/02/2023-19:24:24] [I] Load engine: 
[08/02/2023-19:24:24] [I] Profiling verbosity: 0
[08/02/2023-19:24:24] [I] Tactic sources: Using default tactic sources
[08/02/2023-19:24:24] [I] timingCacheMode: local
[08/02/2023-19:24:24] [I] timingCacheFile: 
[08/02/2023-19:24:24] [I] Input(s)s format: fp32:CHW
[08/02/2023-19:24:24] [I] Output(s)s format: fp32:CHW
[08/02/2023-19:24:24] [I] Input build shapes: model
[08/02/2023-19:24:24] [I] Input calibration shapes: model
[08/02/2023-19:24:24] [I] === System Options ===
[08/02/2023-19:24:24] [I] Device: 0
[08/02/2023-19:24:24] [I] DLACore: 
[08/02/2023-19:24:24] [I] Plugins:
[08/02/2023-19:24:24] [I] === Inference Options ===
[08/02/2023-19:24:24] [I] Batch: Explicit
[08/02/2023-19:24:24] [I] Input inference shapes: model
[08/02/2023-19:24:24] [I] Iterations: 10
[08/02/2023-19:24:24] [I] Duration: 3s (+ 200ms warm up)
[08/02/2023-19:24:24] [I] Sleep time: 0ms
[08/02/2023-19:24:24] [I] Idle time: 0ms
[08/02/2023-19:24:24] [I] Streams: 1
[08/02/2023-19:24:24] [I] ExposeDMA: Disabled
[08/02/2023-19:24:24] [I] Data transfers: Enabled
[08/02/2023-19:24:24] [I] Spin-wait: Disabled
[08/02/2023-19:24:24] [I] Multithreading: Disabled
[08/02/2023-19:24:24] [I] CUDA Graph: Enabled
[08/02/2023-19:24:24] [I] Separate profiling: Disabled
[08/02/2023-19:24:24] [I] Time Deserialize: Disabled
[08/02/2023-19:24:24] [I] Time Refit: Disabled
[08/02/2023-19:24:24] [I] Inputs:
[08/02/2023-19:24:24] [I] === Reporting Options ===
[08/02/2023-19:24:24] [I] Verbose: Disabled
[08/02/2023-19:24:24] [I] Averages: 10 inferences
[08/02/2023-19:24:24] [I] Percentile: 99
[08/02/2023-19:24:24] [I] Dump refittable layers:Disabled
[08/02/2023-19:24:24] [I] Dump output: Disabled
[08/02/2023-19:24:24] [I] Profile: Disabled
[08/02/2023-19:24:24] [I] Export timing to JSON file: 
[08/02/2023-19:24:24] [I] Export output to JSON file: 
[08/02/2023-19:24:24] [I] Export profile to JSON file: 
[08/02/2023-19:24:24] [I] 
[08/02/2023-19:24:24] [I] === Device Information ===
[08/02/2023-19:24:24] [I] Selected Device: NVIDIA GeForce GTX 1650 Ti
[08/02/2023-19:24:24] [I] Compute Capability: 7.5
[08/02/2023-19:24:24] [I] SMs: 16
[08/02/2023-19:24:24] [I] Compute Clock Rate: 1.485 GHz
[08/02/2023-19:24:24] [I] Device Global Memory: 3912 MiB
[08/02/2023-19:24:24] [I] Shared Memory per SM: 64 KiB
[08/02/2023-19:24:24] [I] Memory Bus Width: 128 bits (ECC disabled)
[08/02/2023-19:24:24] [I] Memory Clock Rate: 6.001 GHz
[08/02/2023-19:24:24] [I] 
[08/02/2023-19:24:24] [I] TensorRT version: 8.4.2
[08/02/2023-19:24:24] [I] [TRT] [MemUsageChange] Init CUDA: CPU +311, GPU +0, now: CPU 319, GPU 230 (MiB)
[08/02/2023-19:24:25] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +207, GPU +68, now: CPU 545, GPU 298 (MiB)
[08/02/2023-19:24:25] [I] Start parsing network model
[08/02/2023-19:24:26] [I] [TRT] ----------------------------------------------------------------
[08/02/2023-19:24:26] [I] [TRT] Input filename:   /models/converted.onnx
[08/02/2023-19:24:26] [I] [TRT] ONNX IR version:  0.0.9
[08/02/2023-19:24:26] [I] [TRT] Opset version:    11
[08/02/2023-19:24:26] [I] [TRT] Producer name:    pytorch
[08/02/2023-19:24:26] [I] [TRT] Producer version: 2.0.1
[08/02/2023-19:24:26] [I] [TRT] Domain:           
[08/02/2023-19:24:26] [I] [TRT] Model version:    0
[08/02/2023-19:24:26] [I] [TRT] Doc string:       
[08/02/2023-19:24:26] [I] [TRT] ----------------------------------------------------------------
[08/02/2023-19:24:26] [W] [TRT] parsers/onnx/onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/02/2023-19:24:26] [I] [TRT] No importer registered for op: EfficientNMS_TRT. Attempting to import as plugin.
[08/02/2023-19:24:26] [I] [TRT] Searching for plugin: EfficientNMS_TRT, plugin_version: 1, plugin_namespace: 
[08/02/2023-19:24:26] [I] [TRT] Successfully created plugin: EfficientNMS_TRT
[08/02/2023-19:24:26] [I] [TRT] No importer registered for op: PyramidROIAlign_TRT. Attempting to import as plugin.
[08/02/2023-19:24:26] [I] [TRT] Searching for plugin: PyramidROIAlign_TRT, plugin_version: 1, plugin_namespace: 
[08/02/2023-19:24:26] [W] [TRT] parsers/onnx/builtin_op_importers.cpp:4714: Attribute roi_coords_plusone not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.
[08/02/2023-19:24:26] [W] [TRT] parsers/onnx/builtin_op_importers.cpp:4714: Attribute legacy not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.
[08/02/2023-19:24:26] [I] [TRT] Successfully created plugin: PyramidROIAlign_TRT
[08/02/2023-19:24:26] [I] [TRT] No importer registered for op: EfficientNMS_TRT. Attempting to import as plugin.
[08/02/2023-19:24:26] [I] [TRT] Searching for plugin: EfficientNMS_TRT, plugin_version: 1, plugin_namespace: 
[08/02/2023-19:24:26] [I] [TRT] Successfully created plugin: EfficientNMS_TRT
[08/02/2023-19:24:26] [I] [TRT] No importer registered for op: PyramidROIAlign_TRT. Attempting to import as plugin.
[08/02/2023-19:24:26] [I] [TRT] Searching for plugin: PyramidROIAlign_TRT, plugin_version: 1, plugin_namespace: 
[08/02/2023-19:24:26] [W] [TRT] parsers/onnx/builtin_op_importers.cpp:4714: Attribute roi_coords_plusone not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.
[08/02/2023-19:24:26] [W] [TRT] parsers/onnx/builtin_op_importers.cpp:4714: Attribute legacy not found in plugin node! Ensure that the plugin creator has a default value defined or the engine may fail to build.
[08/02/2023-19:24:26] [I] [TRT] Successfully created plugin: PyramidROIAlign_TRT
[08/02/2023-19:24:26] [I] Finish parsing network model
[08/02/2023-19:24:27] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +499, GPU +216, now: CPU 1240, GPU 522 (MiB)
[08/02/2023-19:24:27] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +117, GPU +54, now: CPU 1357, GPU 576 (MiB)
[08/02/2023-19:24:27] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[08/02/2023-19:26:38] [E] Error[2]: [virtualMemoryBuffer.cpp::resizePhysical::144] Error Code 2: OutOfMemory (no further information)
[08/02/2023-19:26:38] [E] Error[2]: [virtualMemoryBuffer.cpp::resizePhysical::144] Error Code 2: OutOfMemory (no further information)
[08/02/2023-19:26:38] [W] [TRT] -------------- The current system memory allocations dump as below --------------
[08/02/2023-19:26:38] [W] [TRT] [0x670639e0]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 19830 time: 6.64e-07
[08/02/2023-19:26:38] [W] [TRT] [0x67067980]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 19827 time: 7.65e-07
[08/02/2023-19:26:38] [W] [TRT] [0x67063560]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 19821 time: 6.3e-07
[08/02/2023-19:26:38] [W] [TRT] [0x67061120]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 19815 time: 1.158e-06

.....
....
[08/02/2023-19:26:39] [W] [TRT] [0x30e94800]:4 :: weight zero-point in internalAllocate: at runtime/common/weightsPtr.cpp: 102 idx: 17 time: 4.3e-08
[08/02/2023-19:26:39] [W] [TRT] [0x6704ae30]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 14362 time: 2.53e-07
[08/02/2023-19:26:39] [W] [TRT] [0x6704b5e0]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 14377 time: 1.89e-07
[08/02/2023-19:26:39] [W] [TRT] [0x67041840]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 10836 time: 6.33e-07
[08/02/2023-19:26:39] [W] [TRT] [0x6704a2e0]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 14693 time: 4.7e-08
[08/02/2023-19:26:39] [W] [TRT] [0x67060b80]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 19416 time: 3.9e-08
[08/02/2023-19:26:39] [W] [TRT] [0x67042650]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 14708 time: 4.7e-08
[08/02/2023-19:26:39] [W] [TRT] [0x2157ac40]:1642496 :Cudnn Builder weights ptr in internalAllocate: at runtime/common/weightsPtr.cpp: 102 idx: 175 time: 3.31e-07
[08/02/2023-19:26:39] [W] [TRT] [0x66ee9c20]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 6348 time: 2.58e-07
[08/02/2023-19:26:39] [W] [TRT] [0x67051510]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 14714 time: 1.69e-07
[08/02/2023-19:26:39] [W] [TRT] [0x67036d80]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 8885 time: 3.33e-07
[08/02/2023-19:26:39] [W] [TRT] [0x6704c810]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 15567 time: 2.73e-07
[08/02/2023-19:26:39] [W] [TRT] [0x66ee6540]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 6336 time: 1.92e-07
[08/02/2023-19:26:39] [W] [TRT] [0x6704de30]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 15573 time: 2.33e-07
[08/02/2023-19:26:39] [W] [TRT] [0x6704f560]:151 :ScratchObject in storeCachedObject: at optimizer/gpu/cudnn/convolutionBuilder.cpp: 170 idx: 15576 time: 2.88e-07
[08/02/2023-19:26:39] [W] [TRT] -------------- The current device memory allocations dump as below --------------
[08/02/2023-19:26:39] [W] [TRT] [0]:4294967296 :HybridGlobWriter in reserveMemory: at optimizer/common/globWriter.cpp: 438 idx: 4708 time: 0.0150887
[08/02/2023-19:26:39] [W] [TRT] [0x302000000]:2232418304 :HybridGlobWriter in reserveMemory: at optimizer/common/globWriter.cpp: 416 idx: 3046 time: 0.00204409
[08/02/2023-19:26:39] [W] [TRT] Requested amount of GPU memory (4294967296 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[08/02/2023-19:26:39] [W] [TRT] Skipping tactic 7 due to insufficient memory on requested size of 4294967296 detected for tactic 0x000000000000003d.
Try decreasing the workspace size with IBuilderConfig::setMemoryPoolLimit().
[08/02/2023-19:26:58] [W] [TRT] Skipping tactic 0x0000000000000000 due to Myelin error: autotuning: CUDA error 2 allocating 0-byte buffer: out of memory
[08/02/2023-19:26:58] [E] Error[10]: [optimizer.cpp::computeCosts::3626] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[box_outputs/reshape_classes...mask_head/final_reshape]}.)
[08/02/2023-19:26:58] [E] Error[2]: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[08/02/2023-19:26:58] [E] Engine could not be created from network
[08/02/2023-19:26:58] [E] Building engine failed
[08/02/2023-19:26:58] [E] Failed to create engine from model or file.
[08/02/2023-19:26:58] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8402] # tensorrt/bin/trtexec --onnx=/models/converted.onnx --saveEngine=engine.trt --useCudaGraph

![image](https://github.com/triton-inference-server/server/assets/73757851/441d5ec6-e298-4462-b988-6a4ac6bc99a0)

![image](https://github.com/triton-inference-server/server/assets/73757851/33ea8cd6-c3bc-47b0-b88d-71d15a9c58d1)

![image](https://github.com/triton-inference-server/server/assets/73757851/80cdd6eb-5435-4eb6-ace8-53cb92337ec4)

**Comment by zerollzeng** [comment]
> [08/02/2023-19:26:39] [W] [TRT] Requested amount of GPU memory (4294967296 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
> [08/02/2023-19:26:39] [W] [TRT] Skipping tactic 7 due to insufficient memory on requested size of 4294967296 detected for tactic 0x000000000000003d.
> Try decreasing the workspace size with IBuilderConfig::setMemoryPoolLimit().
> [08/02/2023-19:26:58] [W] [TRT] Skipping tactic 0x0000000000000000 due to Myelin error: autotuning: CUDA error 2 allocating 0-byte buffer: out of memory
> [08/02/2023-19:26:58] [E] Error[10]: [optimizer.cpp::computeCosts::3626] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[box_outputs/reshape_classes...mask_head/final_reshape]}.)

Insufficient memory, you need a GPU with bigger memory, I would suggest to use latest TRT.

**Comment by imenselmi** [comment]
I solved the issue by adding '--workspace=2000'. It works for me now:
tensorrt/bin/trtexec --onnx=/models/converted.onnx --saveEngine=engine.trt --workspace=2000 --useCudaGraph

**Comment by zerollzeng** [comment]
Ok, If you are using TRT 8.5+, then we set the workspace size to max by default.

I'm closing this since it's work now :-) Feel free to reopen.

**Comment by ybpei** [comment]
@imenselmi Hello, can the engine generated by the " tensorrt/bin/trtexec --onnx=/models/converted.onnx --saveEngine=engine.trt --useCudaGraph" command be correctly parsed by C++ TensorRT? Looking forward to your kindly reply!
