### ISSUE TITLE
[Bug] TensorRT 8.6.1.6 and 8.2.2.1 generate different results on the same ONNX file

### ISSUE THREAD

**Issue by mirzadeh** [NVIDIA/TensorRT#3645]
## Description

I have an ONNX model (traced from pytorch) which takes 3 inputs and produces one output. Lets call this `bad.onnx`. When I convert this model to a plan file using TensorRT 8.6.1.6, I get the wrong output (compared to pytorch result). But the same ONNX model behaves correctly if I use TensorRT 8.2.2.1. 

What is more puzzling, is that if I return two outputs (one arbitrary intermediate result as well as the desired output -- lets call this `good.onnx`), TensorRT 8.6.1.6 generates the correct results. So perhaps this is somehow related to how TRT is handling intermediates? Maybe a memory issue? 

[Here](https://github.com/NVIDIA/TensorRT/files/14114291/TRT.Comparison.zip) are `bad.onnx` and `good.onnx` files as well as sample input data that can be used to run the model. Below are some results from running both models using trtexec and sample input data. 

Any ideas what is causing the buggy behavior in TRT 8.6.1.6?

- `bad.onnx`
<img width="400" alt="bad.onnx" align="center" src="https://github.com/NVIDIA/TensorRT/assets/2917606/ee7909c1-63bb-4b9e-b8c3-2e1f4087149e">

- `good.onnx`
<img width="400" alt="good.onnx" align="center" src="https://github.com/NVIDIA/TensorRT/assets/2917606/2376d615-2c54-4d4b-bd95-577e48bdc68b">

```bash
# Run with sample input data
$ trtexec --onnx=/tmp/bad.onnx  
 --loadInputs=center_embed:/tmp/center_embed,neighbor_embed:/tmp/neighbor_embed,edge_dst_idx:/tmp/edge_dst_idx --dumpOutput
```

* TRT 8.2.2.1 (`bad.onnx`)
```
[01/30/2024-22:52:04] [I] alpha: (8x8)
[01/30/2024-22:52:04] [I] -1.61603 -2.83366 0.322892 -0.840423 -0.194691 -0.715993 0.301923 0.748454 -1.59698 1.8165 0.196624 0.0898179 0.240524 -1.13884 -0.35655 -0.0532761 0.07179 0.184793 0.0628643 2.09222 0.401996 0.25236 0.837988 -0.80628 1.82169 2.33064 -0.621996 -1.61706 0.288089 0.001417 0.824367 -1.00749 1.01369 1.00011 -0.0925989 0.650199 -0.288989 0.168037 0.379874 0.291689 -0.169028 1.59293 -0.49886 0.0861075 0.00357494 -1.14585 -0.230934 -0.13426 2.63122 -0.204885 0.360054 -0.0122467 1.06414 -0.946362 0.752912 -1.00622 -4.64957 -1.55596 1.33436 -0.0422329 -0.0541428 0.377588 -1.21095 1.34772
```

* TRT 8.6.6.1 (`bad.onnx`)
```
[01/30/2024-22:54:59] [I] alpha: (8x8)
[01/30/2024-22:54:59] [I] -1.61603 -1.59697 0.0717898 1.82169 1.01369 -0.169028 2.63121 -4.64956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 -0.674163 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

* TRT 8.6.6.1 (`good.onnx`)
```
[01/30/2024-22:54:15] [I] alpha: (8x8)
[01/30/2024-22:54:15] [I] -1.61603 -2.83365 0.322891 -0.840421 -0.194691 -0.715991 0.301922 0.748452 -1.59697 1.8165 0.196623 0.0898177 0.240523 -1.13884 -0.356549 -0.053276 0.0717898 0.184792 0.0628642 2.09222 0.401994 0.25236 0.837986 -0.806278 1.82169 2.33063 -0.621994 -1.61706 0.288089 0.001417 0.824365 -1.00748 1.01369 1.00011 -0.0925987 0.650198 -0.288988 0.168037 0.379873 0.291689 -0.169028 1.59293 -0.498859 0.0861073 0.00357493 -1.14584 -0.230933 -0.13426 2.63121 -0.204884 0.360053 -0.0122466 1.06414 -0.94636 0.75291 -1.00621 -4.64956 -1.55595 1.33435 -0.0422328 -0.0541427 0.377587 -1.21095 1.34772
```

* PyTorch eager mode (expected)
```
tensor([[-1.6160e+00, -2.8337e+00,  3.2289e-01, -8.4042e-01, -1.9469e-01,
         -7.1599e-01,  3.0192e-01,  7.4845e-01],
        [-1.5970e+00,  1.8165e+00,  1.9662e-01,  8.9818e-02,  2.4052e-01,
         -1.1388e+00, -3.5655e-01, -5.3276e-02],
        [ 7.1790e-02,  1.8479e-01,  6.2864e-02,  2.0922e+00,  4.0199e-01,
          2.5236e-01,  8.3799e-01, -8.0628e-01],
        [ 1.8217e+00,  2.3306e+00, -6.2199e-01, -1.6171e+00,  2.8809e-01,
          1.4171e-03,  8.2437e-01, -1.0075e+00],
        [ 1.0137e+00,  1.0001e+00, -9.2599e-02,  6.5020e-01, -2.8899e-01,
          1.6804e-01,  3.7987e-01,  2.9169e-01],
        [-1.6903e-01,  1.5929e+00, -4.9886e-01,  8.6107e-02,  3.5749e-03,
         -1.1458e+00, -2.3093e-01, -1.3426e-01],
        [ 2.6312e+00, -2.0488e-01,  3.6005e-01, -1.2247e-02,  1.0641e+00,
         -9.4636e-01,  7.5291e-01, -1.0062e+00],
        [-4.6496e+00, -1.5560e+00,  1.3344e+00, -4.2233e-02, -5.4143e-02,
          3.7759e-01, -1.2109e+00,  1.3477e+00]])
```

## Environment

**TensorRT Version**: 8.6.1.6 and 8.2.2.1

**NVIDIA GPU**: RTX 2080

**NVIDIA Driver Version**: 525.147.05

**CUDA Version**: 11.3.1

**CUDNN Version**: 

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**: https://github.com/NVIDIA/TensorRT/files/14114291/TRT.Comparison.zip

## Steps To Reproduce
 Extract the zip file, and run the onnx model with trtexec. You can use provided input data for reproducible results.

```bash
# Run with sample input data
$ trtexec --onnx=/tmp/bad.onnx  
 --loadInputs=center_embed:/tmp/center_embed,neighbor_embed:/tmp/neighbor_embed,edge_dst_idx:/tmp/edge_dst_idx --dumpOutput
```

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: No

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): Did not try

**Comment by mirzadeh** [comment]
I did a bit more testing. The first version that shows mismatch is v8.4.1.5. TensorRT 8.2.5.1 also produces the correct results.

**Comment by mirzadeh** [comment]
It seems that the issue is somehow related to the Reshape operation. Consider the following simpler model
```python
class DummyModel(nn.Module):
    def __init__(
        self,
        embed_dim: int,
        num_heads: int = 8,
    ) -> None:
        super().__init__()
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        assert embed_dim % num_heads == 0, "embedding dimension must be divisible by number of heads"

        self.lin_q = nn.Linear(embed_dim, embed_dim)
        self.lin_k = nn.Linear(embed_dim, embed_dim)

    def forward(
        self,
        center_embed: torch.Tensor,
        neighbor_embed: torch.Tensor,
        edge_dst_idx: torch.Tensor,
    ) -> torch.Tensor:
        head_dim = self.embed_dim // self.num_heads
        
        # This works
        # query = self.lin_q(center_embed[edge_dst_idx])
        # key = self.lin_k(neighbor_embed)
        # alpha = (query * key).view(-1, self.num_heads, head_dim).sum(dim=-1)

        # This does not work
        query = self.lin_q(center_embed[edge_dst_idx]).view(-1, self.num_heads, head_dim)
        key = self.lin_k(neighbor_embed).view(-1, self.num_heads, head_dim)
        alpha = (query * key).sum(dim=-1)
        return alpha
```

If I first reshape `key` and `query` tensors and then compute `alpha`, I get the wrong result. But, if I change the order of operations, such that reshape is done on `alpha` things seem to work. This makes me think the issue is somehow related to the temporary results of whatever node reshape is translated to (`IShuffleLayer`?). Hope this helps tracking the bug

**Comment by mirzadeh** [comment]
Hey folks, any updates on this? I just ran into this again in another part of the code. Again, the issue goes away if I change the pytorch code so that there is no reshape after Gemm. This seems like a serious bug to me

**Comment by zerollzeng** [comment]
I'll do more experiments to confirm and file internal bug to track if needed.

**Comment by zerollzeng** [comment]
File internal bug 4489947 to track this.

**Comment by zerollzeng** [comment]
Issue fixed in TRT 10, closed.

**Comment by mirzadeh** [comment]
@zerollzeng Would you be able to share a bit more details? When is TRT 10 scheduled for release and is there any plans for back-porting this fix? Is it safe to use the workaround I described above?

**Comment by zerollzeng** [comment]
I don't have a specific day, but TRT 10 EA should be released in a few weeks.

For the second question, we don't back-port fix to older release unless it's really necessary.
