### ISSUE TITLE
Loading quantized TensorRT engine failure(OOM) of TensorRT 9.2 when running SDXL on GPU A10(23G)

### ISSUE THREAD

**Issue by songh11** [NVIDIA/TensorRT#3790]
## Description

  I tried to run demo_txt2img_xl.py on A10, but it show Out of memory

[I] Loading bytes from engine_int8/unetxl-int8.l3.0.bs2.s30.c384.p0.4.a0.6.trt9.2.0.post12.dev5.plan
Loading TensorRT engine: engine_int8/vae.trt9.2.0.post12.dev5.plan
[I] Loading bytes from engine_int8/vae.trt9.2.0.post12.dev5.plan
[E] 1: [defaultAllocator.cpp::allocate::20] Error Code 1: Cuda Runtime (out of memory)
[W] Requested amount of GPU memory (22145926656 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 2: [executionContext.cpp::ExecutionContext::475] Error Code 2: OutOfMemory (no further information)
[E] 3: [executionContext.cpp::setInputShape::2278] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2278, condition: engineDims.d[i] == dims.d[i] Static dimension mismatch while setting input shape.)

## Environment

**TensorRT Version**: 9.2

**NVIDIA GPU**: A10

**NVIDIA Driver Version**: 535.104.12

**CUDA Version**: 12.2

**CUDNN Version**: 8.9.4

Operating System:

Python Version (if applicable): 3.8

Tensorflow Version (if applicable):

PyTorch Version (if applicable): 2.2.2

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by songh11** [comment]
TensorRT 10.0 also has this problem.

**Comment by songh11** [comment]
The problem has been solved. Need to set max_batch_size=1.
