### ISSUE TITLE
Is RTX 2080 TI supported?

### ISSUE THREAD

**Issue by emef** [NVIDIA/TensorRT#38]
I am using the python library to build a model:

```
with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network:
    ...
    network.add_input(...)
    etc.
```

This has worked fine for months on the 1080 TI card. I've recently added a RTX 2080 TI to my machine and it does not work. While building the model, I see this error:

```
[TensorRT] ERROR: cuda/cudaConvolutionLayer.cpp (238) - Cudnn Error in execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)
```

My configuration (using nvidia-docker):

* OS: ubuntu 16.04
* cuda: 10.0
* cudnn: 7.5.0
* tensorrt: 5.1.5

```
user@dd17d4e31b32:~$ dpkg -l | grep TensorRT
ii  libnvinfer-dev                                              5.1.5-1+cuda10.0                                      amd64        TensorRT development libraries and headers
ii  libnvinfer-samples                                          5.1.5-1+cuda10.0                                      all          TensorRT samples and documentation
ii  libnvinfer5                                                 5.1.5-1+cuda10.0                                      amd64        TensorRT runtime libraries
ii  python-libnvinfer                                           5.1.5-1+cuda10.0                                      amd64        Python bindings for TensorRT
ii  python-libnvinfer-dev                                       5.1.5-1+cuda10.0                                      amd64        Python development package for TensorRT
ii  tensorrt                                                    5.1.5.0-1+cuda10.0                                    amd64        Meta package of TensorRT

user@dd17d4e31b32:~$ dpkg -l | grep cudnn
ii  libcudnn7                                                   7.5.0.56-1+cuda10.0                                   amd64        cuDNN runtime libraries
ii  libcudnn7-dev                                               7.5.0.56-1+cuda10.0                                   amd64        cuDNN development libraries and headers
```

Relevant part of Dockerfile:

```
# cuda/cudnn
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

# Install TensorRT
RUN dpkg -i /debs/nv-tensorrt-repo-ubuntu1604-cuda10.0-trt5.1.5.0-ga-20190427_1-1_amd64.deb
RUN apt-key add /var/nv-tensorrt-repo-cuda10.0-trt5.1.5.0-ga-20190427/7fa2af80.pub
RUN apt-get update && apt-get -y install \
    libcudnn7=7.5.0.56-1+cuda10.0 \
    libcudnn7-dev=7.5.0.56-1+cuda10.0 \
    tensorrt=5.1.5.0-1+cuda10.0 \
    python-libnvinfer-dev=5.1.5-1+cuda10.0 \
    python-libnvinfer=5.1.5-1+cuda10.0 \
    libnvinfer5=5.1.5-1+cuda10.0 \
    libnvinfer-dev=5.1.5-1+cuda10.0
```

Is there a known issue with the newer cards in TensorRT or is there just a problem with my environment?

**Comment by lemonyhw** [comment]
I have the same problem which confused me several days. do you solve it now?

**Comment by emef** [comment]
No I haven't solved this yet, just using an older card for now until we can figure this out.

**Comment by rajeevsrao** [comment]
@emef @lemonyhw 2080Ti is absolutely supported. Can you please confirm that these issues are seen with the TensorRT core libraries from the release package? If its not related to the open source components contained in this repo, please file a bug report as described here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#bug-reporting

**Comment by zhuanjiao2222** [comment]
I had the same issue with TensorRT, my GPU is 2080Ti, whether this card is not supported by tensorrt or there are some wrong configurations with my computer environment?

**Comment by emef** [comment]
This did seem to be related to cudnn version. When I enabled full cuda debugging I realized the cudnn version being reported was 7.5.0 even though 7.6.3 was installed. I believe this may have been due to some shadowing from pytorch, because when I upgraded torch to 1.2.0 the problem has been fixed.

**Comment by z13974509906** [comment]
@emef 
Why pytorch affects tensorRT？ I met the same issue in T4.
My enviorment:
```
centos: 7
cuda: 10.0
cudnn: 7.5.0
tensorrt: 5.1.5
```

**Comment by z13974509906** [comment]
but I didn't use pytorch, my enviorment only has TensorRT 5.1.5

**Comment by mattforbes-gr** [comment]
@z13974509906 try upgrading to cudnn 7.6.3
