### ISSUE TITLE
pip install results in ModuleNotFoundError

### ISSUE THREAD

**Issue by coppock** [NVIDIA/TensorRT#3936]
## Description

After following [the install instructions](https://github.com/NVIDIA/TensorRT?tab=readme-ov-file#prebuilt-tensorrt-python-package) in a brand new Python virtual environment, I get a ModuleNotFoundError for module **tensorrt_bindings**. The expected behavior is that the import succeeds.

After manually installing **tensorrt_bindings**, I get a different error where **libnvinfer** can't be opened.

## Environment

* **TensorRT Version**: 10.0.1
* **NVIDIA GPU**: A30
* **NVIDIA Driver Version**: 555.42.02
* **CUDA Version**: 12.4
* Operating System: Ubuntu 20.04
* Python Version (if applicable): 3.10.12

## Steps To Reproduce

```
ubuntu$ python -m venv .venv
ubuntu$ . .venv/bin/activate
(.venv) ubuntu$ pip install tensorrt
Collecting tensorrt
  Using cached tensorrt-10.0.1-py2.py3-none-any.whl
Collecting tensorrt-cu12
  Using cached tensorrt_cu12-10.0.1-py2.py3-none-any.whl
Installing collected packages: tensorrt-cu12, tensorrt
Successfully installed tensorrt-10.0.1 tensorrt-cu12-10.0.1
(.venv) ubuntu$ python -c 'import tensorrt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/pcoppock/mlos/.venv/lib/python3.10/site-packages/tensorrt/__init__.py", line 18, in <module>
    from tensorrt_bindings import *
ModuleNotFoundError: No module named 'tensorrt_bindings'
(.venv) ubuntu$ 
```

Installing **tensorrt_bindings** doesn't solve this.

```
(.venv) ubuntu$ pip install tensorrt_bindings
Collecting tensorrt_bindings
  Using cached tensorrt_bindings-8.6.1-cp310-none-manylinux_2_17_x86_64.whl (979 kB)
Installing collected packages: tensorrt_bindings
Successfully installed tensorrt_bindings-8.6.1
(.venv) ubuntu$ python -c 'import tensorrt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/pcoppock/mlos/.venv/lib/python3.10/site-packages/tensorrt/__init__.py", line 18, in <module>
    from tensorrt_bindings import *
  File "/data/pcoppock/mlos/.venv/lib/python3.10/site-packages/tensorrt_bindings/__init__.py", line 67, in <module>
    from .tensorrt import *
ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory
(.venv) ubuntu$ 
```

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: Yes, I'm installing the default version in a clean virtual environment.

**Comment by coppock** [comment]
To solve this, I uninstalled Ubuntu's **tensorrt** package, and reinstalled, forcing it to version 8:

```
sudo apt install tensorrt=8.6.1.6-1+cuda12.0 libnvinfer-bin=8.6.1.6-1+cuda12.0 libnvinfer-dev=8.6.1.6-1+cuda12.0 libnvinfer-lean-dev=8.6.1.6-1+cuda12.0 libnvinfer-plugin-dev=8.6.1.6-1+cuda12.0 libnvinfer-vc-plugin-dev=8.6.1.6-1+cuda12.0 libnvinfer-dispatch-dev=8.6.1.6-1+cuda12.0 libnvparsers-dev=8.6.1.6-1+cuda12.0 libnvonnxparsers-dev=8.6.1.6-1+cuda12.0 libnvinfer-samples=8.6.1.6-1+cuda12.0 libnvinfer-headers-dev=8.6.1.6-1+cuda12.0 libnvinfer-headers-plugin-dev=8.6.1.6-1+cuda12.0
```

**Comment by coppock** [comment]
The previous comment was a workaround. This issue went away entirely after I removed **~/.cache/pip** and **~/.local/lib/python3.10** and reinstalled in a new virtual environment.
