### ISSUE TITLE
Different results in tensorrt 6 and 7

### ISSUE THREAD

**Issue by royinx** [NVIDIA/TensorRT#399]
## Description

The TensorRT engine outputs of 6(1912) and 7(2002) are different.

The [original repo](https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/blob/master/face_detection/deploy_tensorrt/predict_tensorrt.py#L128) is LFFD that i simplify and upload it. 
I add the **trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH** since upgrade from TRT 6 to 7.

After testing and found out two engines have different [outputs](https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/blob/master/face_detection/deploy_tensorrt/predict_tensorrt.py#L227)

## Environment

**TensorRT Version**: 2080Ti
**GPU Type**: Turing
**Nvidia Driver Version**: 440.59
**Container**: tensorrt:20.02-py3 & 19.12-py3

## Relevant Files

[[Google Drive](https://drive.google.com/open?id=1E0NhGIxilkkNqSl81ptFvE2iQO7PLim7)]
tensorRT_bug
├── debug_Image
│   ├── test1.jpg
│   ├── ...
│   └──  test6.jpg
└── onnx_files
│   └── model.onnx
└── predict_tensorrt_1912.py
└── predict_tensorrt_1912.py

## Steps To Reproduce

```
# Run container 20.02
docker run --privileged --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v ~/Downloads/<folder>:/workdir -w /workdir --runtime=nvidia nvcr.io/nvidia/tensorrt:20.02-py3 bash

# install opencv 
apt-get update \
  && apt-get install -y --no-install-recommends \
  libsm6 \
  libxext6 \
  libxrender1 && \
  pip3 install opencv-python

# run the code
python3 predict_tensorrt_2002.py
```

**Comment by royinx** [comment]
Hi @rmccorm4 , 
I checked #396 and face to the same issue, i create a new issue to make it more clear.

**Comment by rmccorm4** [comment]
Hi @royinx,

Does your model contain a `Softmax` layer? If so, I think this is a known issue: https://forums.developer.nvidia.com/t/softmax-layer-in-tensorrt7-0-has-wrong-inference-results/112689/4

If not, I'll take a look when I get the chance.

**Comment by rajeevsrao** [comment]
@royinx please try the 7.1 or later releases and let us know if this is still an issue. As Ryan mentioned above, this looks like the Softmax bug in 7.0.

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by royinx** [comment]
My model needs softamx axis=1 which is working smooth in trt6

When I shift the model from 6.0 to 7.0 / 7.1 / 7.2, the wrong result occurred.

I created a one layer softmax model for testing, with input (1,3,4,5), node (softmax axis =1),
I wanna reproduce the result in trt6 , that is 0.3333

Container tested:
|notebook|container|
|:--:|:--:|
|[TensorRT6 notebook ](https://github.com/royinx/trtis_issues/blob/master/trt6.ipynb)|19.12-py3|
|[TensorRT7 notebook ](https://github.com/royinx/trtis_issues/blob/master/trt7.ipynb)|20.09-py3<br/>20.11-py3<br/>21.03-py3|

**Comment by ttyio** [comment]
Hello @royinx , the ground truth should be 1/60 (0.01666667) in your case.

check the spec in https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Softmax-11
the input shape {1, 3, 4, 5} would first collapse into 2d shape {1, 60}, and then run softmax at axis 1.

you can verify the result using below code:

      import onnxruntime as rt
      import numpy as np
      sess = rt.InferenceSession("softmax_test4axis1.onnx")
      input_name = sess.get_inputs()[0].name
      output_name = sess.get_outputs()[0].name
      input_image = np.ones((1,3,4,5)).astype(np.float32)
      pred = sess.run([output_name], {input_name: input_image})[0]
      print(pred)

And for your inference code, you need fix 1 line to get the same result 

change from 

       input_image = np.ones((1,3,4,5))

to

        input_image = np.ones((1,3,4,5)).astype(np.float32)

**Comment by royinx** [comment]
ok I see difference, it would be collapse into 2d {1,60} in ONNX runtime and tensorrt 
what should I do if I want to softmax it by axis?
the result for me should e1 / (3*e1)  = 1/3 , 
so I should slice the NCHW into NHW and softmax by C?

**Comment by ttyio** [comment]
Hello @royinx  the `IShuffleLayer` in TRT support transpose from NCHW to NHWC, so maybe you can transpose before run softmax on {NHW, C},  finally use shuffle to transpose the NHWC back to NCHW.

https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_shuffle_layer.html

**Comment by royinx** [comment]
thank you, I just solved the problem.
I added transpose and reshape layers in mxnet, export to onnx , and use trtexec to compile. 
finally it works, thank you so much.
