### ISSUE TITLE
undefined reference to createNvOnnxParser_INTERNAL

### ISSUE THREAD

**Issue by huangrichen11** [NVIDIA/TensorRT#433]
I want parser onnx file, but i got the error below:
`ONNXParser.cpp.o: In function nvonnxparser::(anonymous namespace)::createParser(nvinfer1::INetworkDefinition&, nvinfer1::ILogger&)`
`NvOnnxParser.h:247 undefined reference to createNvOnnxParser_INTERNAL`
This error means i did not link nvparsers.so correctly. 
But In CMakeLists.txt  I've linked to the nvparsers.so library.

version:

1. onnx 1.6.0
2. trt 7.0

**Comment by rmccorm4** [comment]
Hi,

I think that might be in `libnvinfer.so` or one of the other TensorRT libraries. Can you try linking those as well?

**Comment by huangrichen11** [comment]
> Hi,
> 
> I think that might be in `libnvinfer.so` or one of the other TensorRT libraries. Can you try linking those as well?

Hi  I have already linked 3 libraries below:
-  `libnvinfer.so`
- `libnvparsers.so` 
- `libnvinfer_plugin.so`

**Comment by rmccorm4** [comment]
What about `libnvonnxparser.so` ?

**Comment by rmccorm4** [comment]
I'm not sure I understand exactly what you're trying to do, but this script can successfully build all of the OSS components from this repo for an x86 machine: https://github.com/rmccorm4/tensorrt-utils/blob/master/OSS/build_OSS.sh using the `CMakeLists.txt` defined in this repo and also in the onnx/onnx-tensorrt repo.

Maybe that will provide some insight into your issue.

**Comment by huangrichen11** [comment]
> I'm not sure I understand exactly what you're trying to do, but this script can successfully build all of the OSS components from this repo, including the ONNX parser, for an x86 machine: https://github.com/rmccorm4/tensorrt-utils/blob/master/OSS/build_OSS.sh using the `CMakeLists.txt` defined in this repo and also in the onnx/onnx-tensorrt repo.
> 
> Maybe that will provide some insight into your issue.
> 
> Example:
> 
> ```
> # (Optional) Pull and Run TensorRT 7 Container from NGC
> nvidia-docker run -it nvcr.io/nvidia/tensorrt:20.02-py3
> 
> # Build OSS Components from https://github.com/NVIDIA/TensorRT
> wget https://raw.githubusercontent.com/rmccorm4/tensorrt-utils/master/OSS/build_OSS.sh
> source build_OSS.sh
> ```

I have successfully converted onnx module using the python API and and calling TensorRT engine using C++ API. So, I think I have successfully installed TensorRT

**Comment by rmccorm4** [comment]
Do you still need help with something then?

**Comment by huangrichen11** [comment]
> Do you still need help with something then?

Yes, because I want to use the c++ API to get TensorRT engine. but got the error mentioned above

**Comment by huangrichen11** [comment]
> Hi,
> 
> I think that might be in `libnvinfer.so` or one of the other TensorRT libraries. Can you try linking those as well?

you are right. I have solved the problem when I link to `nvonnxparser.so`

**Comment by BingooYang** [comment]
I have the same problem as you. How do you link nvonnxparser.so? I don't find the nvonnxparser.so in /tensorrt_install_root/lib. Can you share how you solved this problem?

**Comment by BingooYang** [comment]
> > Hi,
> > I think that might be in `libnvinfer.so` or one of the other TensorRT libraries. Can you try linking those as well?
> 
> you are right. I have solved the problem when I link to `nvonnxparser.so`

I have the same problem as you. How do you link nvonnxparser.so? I don't find the nvonnxparser.so in /tensorrt_install_root/lib. Can you share how you solved this problem?

**Comment by iammeizu** [comment]
> > Hi,
> > I think that might be in `libnvinfer.so` or one of the other TensorRT libraries. Can you try linking those as well?
> 
> you are right. I have solved the problem when I link to `nvonnxparser.so`

check LDFLAGS when use gcc/g++ compile, -lnvonnxparser means using libnvonnxparser.so
