### ISSUE TITLE
Getting error and crash when running tensorRT 8.5.3

### ISSUE THREAD

**Issue by hayabusa232013** [NVIDIA/TensorRT#4399]
## Description

i am running the rope-live program and while running it , it keeps crashing after running for a few mins.it crashes more quick when i choose the occuluder and dlf xseg option.  i am not able to figure out what the issue is and i get the error message below:

## Environment

**TensorRT Version**: 8.5.3

**NVIDIA GPU**: gtx 980 ti

**NVIDIA Driver Version**: 32.0.15.7283

**CUDA Version**: 11.8

**CUDNN Version**: cudnn-windows-x86_64-8.6.0.163_cuda11-archive

Operating System: windows 10

Python Version (if applicable): 3.10

Tensorflow Version (if applicable):

PyTorch Version (if applicable):
torch                    2.4.1+cu124
torchaudio               2.4.1+cu124
torchvision              0.19.1+cu124

ONNXRuntime: 1.17

Error: 

D:\next\Rope-development\Rope-development>call venv\Scripts\activate.bat
[libprotobuf WARNING E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 553206116
[libprotobuf WARNING E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 553206116
[libprotobuf WARNING E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 553206707
Exception in thread Thread-1195 (thread_video_read):
Exception in thread Thread-1198 (thread_video_read):
Traceback (most recent call last):
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-1197 (thread_video_read):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self.run()
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
Exception in thread Thread-1196 (thread_video_read):
    self.run()
Traceback (most recent call last):
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 619, in thread_video_read
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 619, in thread_video_read
    self._target(*self._args, **self._kwargs)
    self.run()
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 619, in thread_video_read
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    temp = [self.swap_video(target_image, frame_number, True), frame_number]
    temp = [self.swap_video(target_image, frame_number, True), frame_number]
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 828, in swap_video
    temp = [self.swap_video(target_image, frame_number, True), frame_number]
    self._target(*self._args, **self._kwargs)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 619, in thread_video_read
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 948, in swap_video
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 948, in swap_video
    img = torch.from_numpy(target_image.astype('uint8')).to(self.models.device) #HxWxc
    temp = [self.swap_video(target_image, frame_number, True), frame_number]
    img = self.func_w_test("swap_video", self.swap_core, img, fface[0], fface[1], s_e, fface[2], found_face.get('DFLModel', False), parameters, control)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1038, in func_w_test
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 948, in swap_video
    img = self.func_w_test("swap_video", self.swap_core, img, fface[0], fface[1], s_e, fface[2], found_face.get('DFLModel', False), parameters, control)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1038, in func_w_test
    img = self.func_w_test("swap_video", self.swap_core, img, fface[0], fface[1], s_e, fface[2], found_face.get('DFLModel', False), parameters, control)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1038, in func_w_test

    result = func(*args, **argsv)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1282, in swap_core
    result = func(*args, **argsv)
    result = func(*args, **argsv)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1103, in swap_core
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1289, in swap_core
    mask = self.func_w_test('occluder', self.apply_occlusion , original_face_256, parameters["OccluderSlider"])
    original_face_512 = v2.functional.affine(img, tform.rotation*57.2958, (tform.translation[0], tform.translation[1]) , tform.scale, 0, center = (0,0), interpolation=v2.InterpolationMode.BILINEAR )
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1038, in func_w_test
  File "D:\next\Rope-development\Rope-development\venv\lib\site-packages\torchvision\transforms\v2\functional\_geometry.py", line 404, in affine
    img_mask = self.func_w_test('occluder', self.apply_dfl_xseg , original_face_256, -parameters["DFLXSegSlider"])
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1038, in func_w_test
    result = func(*args, **argsv)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1599, in apply_occlusion
    return kernel(
  File "D:\next\Rope-development\Rope-development\venv\lib\site-packages\torchvision\transforms\v2\functional\_geometry.py", line 731, in affine_image
    result = func(*args, **argsv)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 1636, in apply_dfl_xseg
    self.models.run_occluder(img, outpred)
  File "D:\next\Rope-development\Rope-development\rope\Models.py", line 899, in run_occluder
    theta = torch.tensor(matrix, dtype=dtype, device=image.device).reshape(1, 2, 3)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
    self.occluder_model.run_with_iobinding(io_binding)

  File "D:\next\Rope-development\Rope-development\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 331, in run_with_iobinding
    self.models.run_dfl_xseg(img, outpred)
    self._sess.run_with_iobinding(iobinding._iobinding, run_options)
RuntimeError: Error in execution: CUDA failure 999: unknown error ; GPU=0 ; hostname=DESKTOP-JBRGC2G ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=408 ; expr=cudaStreamSynchronize(static_cast<cudaStream_t>(stream_));
  File "D:\next\Rope-development\Rope-development\rope\Models.py", line 913, in run_dfl_xseg
    self.model_xseg.run_with_iobinding(io_binding)
  File "D:\next\Rope-development\Rope-development\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 331, in run_with_iobinding
    self._sess.run_with_iobinding(iobinding._iobinding, run_options)
RuntimeError: Error in execution: Non-zero status code returned while running TRTKernel_graph_tf2onnx_16385651659788741798_0 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_16385651659788741798_0_0' Status Message: CUDA failure 999: unknown error ; GPU=0 ; hostname=DESKTOP-JBRGC2G ; file=D:\a\_work\1\s\onnxruntime\core\providers\tensorrt\tensorrt_execution_provider.cc ; line=3578 ; expr=cudaStreamSynchronize(stream);
Exception in thread Thread-1199 (thread_video_read):
Traceback (most recent call last):
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Godspeed\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 619, in thread_video_read
    temp = [self.swap_video(target_image, frame_number, True), frame_number]
  File "D:\next\Rope-development\Rope-development\rope\VideoManager.py", line 828, in swap_video
    img = torch.from_numpy(target_image.astype('uint8')).to(self.models.device) #HxWxc
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by lix19937** [comment]
see   `Reading dangerously large protocol message. If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons. To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.`

**Comment by hayabusa232013** [comment]
> see `Reading dangerously large protocol message. If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons. To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.`

What must I do?

**Comment by lix19937** [comment]
large protocol message maybe a warning, you code raise cuda kernel error, you can run a simple torch cuda code to check your cuda env.

**Comment by poweiw** [comment]
Closing due to inactive. Please feel free to reopen!
