### ISSUE TITLE
`enqueueV3` CuTensor permute failure and zero outputs when using `.engine` from ONNX SCRFD model

### ISSUE THREAD

**Issue by hamzaziizzz** [NVIDIA/TensorRT#4427]
# Platform Info:
- OS: Ubuntu 22.04 LTS
- GPU: NVIDIA RTX 4050 Laptop GPU
- CUDA Version: 12.6
- TensorRT Version: 10.4.0
- Driver Version: 560.35.03
- Python Version: 3.10.12
- Conversion Tool: Python API
- Model: scrfd_10g_gnkps.onnx → scrfd_10g_gnkps.engine
- Input shape: [1, 3, 640, 640]

# Description
After converting my ONNX SCRFD model to a TensorRT engine with batch size = 1, the engine runs successfully at high FPS but always returns zero outputs.
In addition to that, every frame triggers this error:
```
[TRT] IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)
[TRT] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
```
Despite the inference call seemingly working, all scores are `[0.0, 0.0, ...]` and NMS returns no boxes.

## Expected behavior
Model should return actual detections as it does in ONNXRuntime.

## Output
```
[04/22/2025[-10:426/:2238] 0/2025-10:26:38] [TRT] [E] [TRT] [E] IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)

[04/22/2025-10:26:38] [TRT] [E] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
[04/22/2025-10:26:38] [TRT] [E] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
[TRT DET] [(12800,), (3200,), (800,), (51200,), (12800,), (3200,), (128000,), (32000,), (8000,)]
[TRT DET] scores (first 10) = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[TRT DET] [(12800,), (3200,), (800,), (51200,), (12800,), (3200,), (128000,), (32000,), (8000,)]
[TRT DET] scores (first 10) = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[DETECT] raw min/max per tensor: [(np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0))]
[DETECT] raw min/max per tensor: [(np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0))]
[DETECT] after NMS → 0 boxes
[DETECT] after NMS → 0 boxes
[04/22/2025-10:26:38] [TRT] [E] IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)
[04/22/2025-10:26:38] [TRT] [E] IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)
[04/22/2025-10:26:38] [TRT] [E] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
[TRT DET] [(12800,), (3200,), (800,), (51200,), (12800,), (3200,), (128000,), (32000,), (8000,)]
[04/22/2025-10:26:38] [TRT] [E] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
[TRT DET] scores (first 10) = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[DETECT] raw min/max per tensor: [(np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0))]
[TRT DET] [(12800,), (3200,), (800,), (51200,), (12800,), (3200,), (128000,), (32000,), (8000,)]
[TRT DET] scores (first 10) = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[DETECT] raw min/max per tensor: [(np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0))]
[04/22/2025-10:26:38] [TRT] [E] IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)
[DETECT] after NMS → 0 boxes
[DETECT] after NMS → 0 boxes
[04/22/2025-10:26:38] [TRT] [E] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
[TRT DET] [(12800,), (3200,), (800,), (51200,), (12800,), (3200,), (128000,), (32000,), (8000,)]
[TRT DET] scores (first 10) = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[DETECT] raw min/max per tensor: [(np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0)), (np.float32(0.0), np.float32(0.0))]
[DETECT] after NMS → 0 boxes
[04/22/2025-10:26:38] [TRT] [E] IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)
[04/22/2025-10:26:38] [TRT] [E] IExecutionContext::enqueueV3: Error Code 1: CuTensor (Internal cuTensor permutate execute failed)
[04/22/2025-10:26:38] [TRT] [E] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
[TRT DET] [(12800,), (3200,), (800,), (51200,), (12800,), (3200,), (128000,), (32000,), (8000,)]
[04/22/2025-10:26:38] [TRT] [E] [checkMacros.cpp::catchCudaError::212] Error Code 1: Cuda Runtime (invalid resource handle)
```
![Image](https://github.com/user-attachments/assets/0e09cf2f-8a76-4cf9-a271-cdf0e1c5b31f)

Please help resolve this CuTensor permutate failure or clarify if SCRFD model format has specific layout requirements for TRT 10+.

Thank you 🙏

# Python Scripts
I have added python scripts for `tesnorrt_inference.py` and `convert_onnx_to_trt.py` (used to convert ONNX to TensorRT Engine) for more details if it will help you debug and resolve the issue

```python3
import math
import time
import queue
import threading

import numpy as np
import cv2
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
from pymilvus import connections, Collection

# ─── TRT HELPERS ───────────────────────────────────────────────────────────────

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

def load_engine(path: str) -> trt.ICudaEngine:
    with open(path, "rb") as f:
        runtime = trt.Runtime(TRT_LOGGER)
        return runtime.deserialize_cuda_engine(f.read())

def allocate_buffers(context, engine: trt.ICudaEngine):
    inputs, outputs, bindings = [], [], []
    stream = cuda.Stream()
    for idx in range(engine.num_io_tensors):
        name = engine.get_tensor_name(idx)
        shape = engine.get_tensor_shape(name)
        dtype = trt.nptype(engine.get_tensor_dtype(name))
        size = int(trt.volume(shape))
        host_mem = cuda.pagelocked_empty(size, dtype)
        dev_mem = cuda.mem_alloc(host_mem.nbytes)
        bindings.append(int(dev_mem))
        context.set_tensor_address(name, bindings[idx])
        mode = engine.get_tensor_mode(name)
        if mode == trt.TensorIOMode.INPUT:
            inputs.append((host_mem, dev_mem))
        else:
            outputs.append((host_mem, dev_mem))
    return inputs, outputs, bindings, stream

# ─── DETECTOR ─────────────────────────────────────────────────────────────────

class FaceDetectorTRT:
    def __init__(self,
                 engine_path: str,
                 input_size=(640, 640),
                 conf_thresh=0.5,
                 nms_thresh=0.4):
        self.input_size = input_size
        self.conf_thresh = conf_thresh
        self.nms_thresh = nms_thresh
        self.strides = [8, 16, 32]

        self.engine  = load_engine(engine_path)
        self.context = self.engine.create_execution_context()
        self.inputs, self.outputs, self.bindings, self.stream = allocate_buffers(self.context, self.engine)

    def _iou(self, box1, boxes):
        x1 = np.maximum(box1[0], boxes[:,0])
        y1 = np.maximum(box1[1], boxes[:,1])
        x2 = np.minimum(box1[2], boxes[:,2])
        y2 = np.minimum(box1[3], boxes[:,3])
        inter = np.maximum(x2-x1,0) * np.maximum(y2-y1,0)
        area1 = (box1[2]-box1[0])*(box1[3]-box1[1])
        area2 = (boxes[:,2]-boxes[:,0])*(boxes[:,3]-boxes[:,1])
        return inter / (area1 + area2 - inter + 1e-6)

    def _nms(self, boxes, scores):
        idxs = np.argsort(scores)[::-1]
        keep = []
        while idxs.size:
            i = idxs[0]
            keep.append(i)
            if idxs.size==1: break
            ious = self._iou(boxes[i], boxes[idxs[1:]])
            idxs = idxs[1:][ious < self.nms_thresh]
        return keep

    def preprocess(self, image):
        h0, w0 = image.shape[:2]
        th, tw = self.input_size
        scale = min(tw/w0, th/h0)
        nh, nw = int(h0*scale), int(w0*scale)
        img = cv2.resize(image, (nw,nh))
        pad = np.full((th,tw,3),114,dtype=np.uint8)
        top, left = (th-nh)//2, (tw-nw)//2
        pad[top:top+nh, left:left+nw] = img
        rgb = pad[..., ::-1].astype(np.float32)
        rgb = (rgb - 127.5)/128.0
        blob = rgb.transpose(2,0,1)[None, ...]
        return blob, (h0,w0), (scale, top, left)

    def postprocess(self, outs, original, scale_info):
        h0, w0 = original
        scale, top, left = scale_info
        boxes, scores = [], []
        # each stride produces [scores, deltas]
        for i, stride in enumerate(self.strides):
            sc = outs[i].reshape(-1)
            d  = outs[i+len(self.strides)].reshape(-1,4)
            N = d.shape[0]//2  # 2 anchors per cell
            side = int(math.sqrt(N))
            ys, xs = np.meshgrid(range(side), range(side), indexing="ij")
            ctrs = np.stack((xs,ys),-1).reshape(-1,2)*stride
            ctrs = np.repeat(ctrs, 2, axis=0)
            l,t,r,b = [d[:,j]*stride for j in range(4)]
            x1 = ctrs[:,0]-l; y1=ctrs[:,1]-t
            x2 = ctrs[:,0]+r; y2=ctrs[:,1]+b
            mask = sc > self.conf_thresh
            if not mask.any(): continue
            boxes.append(np.stack([x1,y1,x2,y2],1)[mask])
            scores.append(sc[mask])
        if not boxes: return []
        boxes = np.vstack(boxes); scores = np.hstack(scores)
        keep = self._nms(boxes, scores)
        results = []
        for i in keep:
            x1,y1,x2,y2 = boxes[i]
            x1 = int(max(0, min(w0, (x1-left)/scale)))
            y1 = int(max(0, min(h0, (y1-top)/scale)))
            x2 = int(max(0, min(w0, (x2-left)/scale)))
            y2 = int(max(0, min(h0, (y2-top)/scale)))
            results.append((x1,y1,x2,y2, float(scores[i])))
        return results

    def infer(self, blob):
        # copy input
        h_in, d_in = self.inputs[0]
        np.copyto(h_in, blob.ravel())
        cuda.memcpy_htod_async(d_in, h_in, self.stream)
        # run
        self.context.execute_async_v3(self.stream.handle)
        # retrieve outputs
        host_outs = []
        for h_out, d_out in self.outputs:
            cuda.memcpy_dtoh_async(h_out, d_out, self.stream)
            host_outs.append(h_out.copy())
        self.stream.synchronize()

        # DEBUG: print shapes of every output tensor
        print("[TRT DET]", [o.shape for o in host_outs])

        # DEBUG: if first tensor is scores, show first 10
        flat0 = host_outs[0].ravel()
        print("[TRT DET] scores (first 10) =", flat0[:10])

        return host_outs

    def detect(self, image):
        blob, orig, scale_info = self.preprocess(image)
        outs = self.infer(blob)

        # DEBUG: before postprocess, show min/max of outs
        print("[DETECT] raw min/max per tensor:", [(o.min(), o.max()) for o in outs])

        dets = self.postprocess(outs, orig, scale_info)
        print(f"[DETECT] after NMS → {len(dets)} boxes")

        return self.postprocess(outs, orig, scale_info)

# ─── RECOGNIZER ────────────────────────────────────────────────────────────────

class FaceRecognizerTRT:
    def __init__(self, engine_path: str):
        self.engine  = load_engine(engine_path)
        self.context = self.engine.create_execution_context()
        self.inputs, self.outputs, self.bindings, self.stream = allocate_buffers(self.context, self.engine)

    def infer(self, blob: np.ndarray) -> np.ndarray:
        h_in, d_in = self.inputs[0]
        np.copyto(h_in, blob.ravel())
        cuda.memcpy_htod_async(d_in, h_in, self.stream)
        self.context.execute_async_v3(self.stream.handle)
        h_out, d_out = self.outputs[0]
        cuda.memcpy_dtoh_async(h_out, d_out, self.stream)
        self.stream.synchronize()
        return h_out.reshape(1, -1)

# ─── RECOGNITION PREPROCESS ───────────────────────────────────────────────────

def preprocess_recognition(face_img: np.ndarray) -> np.ndarray:
    face_rgb = cv2.cvtColor(face_img, cv2.COLOR_BGR2RGB)
    face_resized = cv2.resize(face_rgb, (112, 112), interpolation=cv2.INTER_AREA)
    norm = face_resized.astype(np.float32) / 255.0
    norm = (norm - 0.5) / 0.5
    return norm.transpose(2, 0, 1)[None, ...]

# ─── WORKER & DISPLAY ─────────────────────────────────────────────────────────

def worker(rtsp_url, out_queue, detector, recognizer, collection, params):
    cap = cv2.VideoCapture(rtsp_url)
    out_count, in_t0, out_t0, out_fps = 0, time.time(), time.time(), 0.0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret: break

        h, w = frame.shape[:2]
        det_frame = cv2.resize(frame, (640, 360), interpolation=cv2.INTER_AREA)
        # print(detector.detect(det_frame))
        for x1,y1,x2,y2,score in detector.detect(det_frame):
            sx, sy = w/640, h/360
            ox1,oy1 = int(x1*sx), int(y1*sy)
            ox2,oy2 = int(x2*sx), int(y2*sy)
            crop = frame[oy1:oy2, ox1:ox2]
            if crop.size==0: continue

            blob = preprocess_recognition(crop)
            emb  = recognizer.infer(blob)[0].tolist()

            res = collection.search(
                data=[emb], anns_field="embeddings",
                param=params, limit=1, output_fields=["name_id"]
            )

            color, label = (0,0,255), ""
            if res and res[0]:
                hit = res[0][0]
                mscore = hit.score
                nid    = hit.entity.get("name_id")
                color  = (0,255,0) if mscore>=0.4 else (0,0,255)
                label  = f"{nid}: {mscore:.2f}"

            cv2.rectangle(frame, (ox1,oy1), (ox2,oy2), color, 2)
            if label:
                cv2.putText(frame, label, (ox1,oy1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)

        # output‐FPS
        out_count += 1
        now = time.time()
        if now - out_t0 >= 1.0:
            out_fps = out_count / (now - out_t0)
            out_count, out_t0 = 0, now
        txt = f"FPS: {out_fps:.2f}"
        cv2.putText(frame, txt, (10, h-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,0,255), 2)

        if out_queue.full():
            try: out_queue.get_nowait()
            except queue.Empty: pass
        out_queue.put(frame)

    cap.release()

def main():
    # ─── init TRT engine wrappers
    detector   = FaceDetectorTRT("models/detection/trt-engine/scrfd_10g_gnkps.engine")
    recognizer = FaceRecognizerTRT("models/recognition/trt-engine/w600k_r50.engine")

    # ─── init Milvus
    connections.connect(alias="default", host="localhost", port="19530")
    coll = Collection("ABESIT_FACE_DATA_COLLECTION_FOR_COSINE")
    coll.load()
    params = {"metric_type":"COSINE","params":{"nprobe":16}}

    # ─── your RTSP / files
    streams = [
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # 0,
        # add more streams if needed
    ]

    # ─── spawn threads & queues
    queues = {}
    for url in streams:
        q = queue.Queue(maxsize=1)
        threading.Thread(target=worker,
                         args=(url, q, detector, recognizer, coll, params),
                         daemon=True).start()
        queues[url] = q

    # ─── tiled display
    THW, THH = 640, 360
    n = len(streams)
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n/cols)
    cv2.namedWindow("FaceRec‑TRT Mosaic", cv2.WINDOW_NORMAL)

    last = {u: np.zeros((THH,THW,3),dtype=np.uint8) for u in streams}
    try:
        while True:
            thumbs = []
            for u in streams:
                if not queues[u].empty():
                    last[u] = cv2.resize(queues[u].get(),
                                         (THW,THH), interpolation=cv2.INTER_AREA)
                thumbs.append(last[u])

            mosaic = np.zeros((THH*rows, THW*cols, 3), dtype=np.uint8)
            for i, thumb in enumerate(thumbs):
                r, c = divmod(i, cols)
                mosaic[r*THH:(r+1)*THH, c*THW:(c+1)*THW] = thumb

            cv2.imshow("FaceRec‑TRT Mosaic", mosaic)
            if cv2.waitKey(1)&0xFF == ord('q'):
                break
            time.sleep(0.01)
    finally:
        cv2.destroyAllWindows()

if __name__ == "__main__":
    main()
```

```python3
import os
import sys
import argparse
import tensorrt as trt

TRT_LOGGER = trt.Logger(trt.Logger.INFO)
EXPLICIT_BATCH = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)


def build_engine(onnx_path, engine_path, fp16=False, max_batch_size=1, max_workspace_size=1024):
    with trt.Builder(TRT_LOGGER) as builder, \
            builder.create_network(EXPLICIT_BATCH) as network, \
            builder.create_builder_config() as config, \
            trt.OnnxParser(network, TRT_LOGGER) as parser:

        # Set workspace size using new API for TensorRT 10+
        config.set_memory_pool_limit(
            trt.MemoryPoolType.WORKSPACE,
            max_workspace_size * (1 << 20)
        )

        # FP16 precision flag
        if fp16:
            config.set_flag(trt.BuilderFlag.FP16)
            print("[INFO] FP16 precision enabled.")

        # Parse ONNX model
        with open(onnx_path, 'rb') as model_file:
            if not parser.parse(model_file.read()):
                print("[ERROR] Failed to parse ONNX model.")
                for i in range(parser.num_errors):
                    print(parser.get_error(i))
                sys.exit(1)

        # Create optimization profile
        # input_tensor = network.get_input(0)
        # shape = list(input_tensor.shape)
        # shape[0] = 1
        # profile = builder.create_optimization_profile()
        # profile.set_shape(input_tensor.name, tuple(shape), tuple(shape), tuple(shape))
        # For SCRFD
        input_tensor = network.get_input(0)
        static_shape  = tuple(input_tensor.shape)  # e.g. (32,3,640,640)
        profile = builder.create_optimization_profile()
        profile.set_shape(
            input_tensor.name,
            static_shape,   # min = static
            static_shape,   # opt = static
            static_shape    # max = static
        )

        config.add_optimization_profile(profile)

        # Detect TensorRT 10+ environment: no config.max_workspace_size attribute
        trt10 = not hasattr(config, 'max_workspace_size')
        if trt10:
            print("[INFO] Building serialized network for TensorRT 10+")
            serialized_engine = builder.build_serialized_network(network, config)
            engine_bytes = serialized_engine
        else:
            print("[INFO] Building engine for older TensorRT versions")
            engine = builder.build_engine(network, config)
            if engine is None:
                print("[ERROR] Engine build failed.")
                sys.exit(1)
            engine_bytes = engine.serialize()

        # Write engine to disk
        with open(engine_path, 'wb') as f:
            f.write(engine_bytes)
        print(f"[SUCCESS] Saved TensorRT engine to {engine_path}")


def main():
    parser = argparse.ArgumentParser(description="Convert ONNX to TensorRT engine for TRT10+")
    parser.add_argument('--onnx', required=True, help='Path to ONNX model file')
    parser.add_argument('--engine', required=True, help='Path to save .engine file')
    parser.add_argument('--fp16', action='store_true', help='Enable FP16 precision')
    parser.add_argument('--batch_size', type=int, default=1, help='Max batch size (default:1)')
    parser.add_argument('--workspace', type=int, default=1024, help='Max workspace size in MB')
    args = parser.parse_args()

    build_engine(
        onnx_path=args.onnx,
        engine_path=args.engine,
        fp16=args.fp16,
        max_batch_size=args.batch_size,
        max_workspace_size=args.workspace
    )


if __name__ == '__main__':
    main()
```

**Comment by geraldstanje** [comment]
hi, do you have a working example without tensorrt e.g. pytorch or onnx?

**Comment by hamzaziizzz** [comment]
Yes I do have.
![Image](https://github.com/user-attachments/assets/4bee3cd9-a647-42be-9250-496b2d2b5d83)

Following is the python script `multistream_face_recognition.py`
```python3
import math
import time
import queue
import threading

import cv2
import numpy as np
import onnxruntime as ort
from pymilvus import connections, Collection

from face_detection import FaceDetectorSCRFD

# --- Global Initialization ---
# 1) GPU‑based SCRFD detector
detector = FaceDetectorSCRFD(
    model_path="models/detection/onnx/scrfd_10g_gnkps.onnx",
    input_size=(640, 640),
    conf_thresh=0.5,
    nms_thresh=0.4
)

# 2) ArcFace recognition session
rec_session = ort.InferenceSession(
    "models/recognition/onnx/w600k_r50.onnx",
    providers=["CUDAExecutionProvider", "CPUExecutionProvider"]
)
rec_input_name = rec_session.get_inputs()[0].name

# 3) Milvus connection & collection
connections.connect(alias="default", host="localhost", port="19530")
collection = Collection("ABESIT_FACE_DATA_COLLECTION_FOR_COSINE")
collection.load()

params = {"metric_type": "COSINE", "params": {"nprobe": 16}}

def preprocess_recognition(face_img: np.ndarray) -> np.ndarray:
    """Convert BGR→RGB, resize to 112×112, normalize, and add batch dim."""
    face_rgb = cv2.cvtColor(face_img, cv2.COLOR_BGR2RGB)
    face_resized = cv2.resize(face_rgb, (112, 112), interpolation=cv2.INTER_AREA)
    face_norm = face_resized.astype(np.float32) / 255.0
    face_norm = (face_norm - 0.5) / 0.5
    return face_norm.transpose(2, 0, 1)[None, ...]


def worker(rtsp_url, out_queue):
    """Read frames, detect & recognize faces, draw overlays, and push to queue."""
    cap = cv2.VideoCapture(rtsp_url)
    cap.set(cv2.CAP_PROP_FPS, 30)
    # Counters and timers
    # in_count = 0
    out_count = 0
    in_t0 = time.time()
    out_t0 = in_t0
    # in_fps = 0.0
    out_fps = 0.0

    while cap.isOpened():
        t_read = time.time()
        ret, frame = cap.read()
        if not ret:
            break

        # # —— INPUT FPS ——
        # in_count += 1
        # dt_in = t_read - in_t0
        # if dt_in >= 1.0:
        #     in_fps = in_count / dt_in
        #     in_count = 0
        #     in_t0 = t_read
        # # Draw input‐FPS in top‐left
        # cv2.putText(frame, f"In: {in_fps:.2f}FPS",
        #             (30, 80),
        #             cv2.FONT_HERSHEY_SIMPLEX, 3,
        #             (0,255,255), 8)

        orig_h, orig_w = frame.shape[:2]
        det_frame = cv2.resize(frame, (640, 360))

        for x1, y1, x2, y2, score in detector.detect(det_frame):
            sx, sy = orig_w / 640, orig_h / 360
            ox1, oy1 = int(x1 * sx), int(y1 * sy)
            ox2, oy2 = int(x2 * sx), int(y2 * sy)
            face_crop = frame[oy1:oy2, ox1:ox2]
            if face_crop.size == 0:
                continue

            blob = preprocess_recognition(face_crop)
            emb = rec_session.run(None, {rec_input_name: blob})[0].flatten().tolist()

            res = collection.search(
                data=[emb], anns_field="embeddings", param=params,
                limit=1, output_fields=["name_id"]
            )

            color = (0, 0, 255)
            label = ""
            if res and len(res[0]) > 0:
                hit = res[0][0]
                match_score = hit.score
                name_id = hit.entity.get("name_id")
                color = (0, 255, 0) if match_score >= 0.4 else (0, 0, 255)
                label = f"{name_id}: {match_score:.2f}"

            cv2.rectangle(frame, (ox1, oy1), (ox2, oy2), color, 2)
            if label:
                cv2.putText(frame, label, (ox1, oy1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.75, color, 2)

        # —— OUTPUT FPS ——
        t_proc = time.time()
        out_count += 1
        dt_out = t_proc - out_t0
        if dt_out >= 1.0:
            out_fps = out_count / dt_out
            out_count = 0
            out_t0 = t_proc

        # Draw output‐FPS in bottom‐left
        txt = f"FPS: {out_fps:.2f}"
        (tw, th), _ = cv2.getTextSize(txt, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)
        cv2.putText(frame, txt, (10, frame.shape[0] - 10), cv2.FONT_HERSHEY_SIMPLEX, 3, (255, 0, 255), 8)


        # drop old frame if queue full, then push current
        if out_queue.full():
            try:
                out_queue.get_nowait()
            except queue.Empty:
                pass
        out_queue.put(frame)

    cap.release()


def main():
    # list your sources here (file paths, RTSP URLs, or camera indices)
    streams = [
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # "/home/hamza/OfficeProjects/CCTV-Face-Recognition-Attendance-System/TEST-VIDEOS/ABESIT/ABESIT-Main-Gate-Test-Video.avi",
        # 0,
        # add more streams if needed
    ]

    # spawn one thread + queue per stream
    queues = {}
    for url in streams:
        q = queue.Queue(maxsize=1)
        queues[url] = q
        t = threading.Thread(target=worker, args=(url, q), daemon=True)
        t.start()

    # thumbnail size (adjust as needed)
    THUMB_W, THUMB_H = 640, 360

    # compute a near‑square grid
    n = len(streams)
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n / cols)
    cv2.namedWindow("Detection-Recognition Parallel Pipeline", cv2.WINDOW_NORMAL)
    cv2.setWindowProperty("Detection-Recognition Parallel Pipeline",
                          cv2.WND_PROP_FULLSCREEN,
                          cv2.WINDOW_NORMAL)

    # cache last thumbnail for each stream
    last_thumbs = {
        url: np.zeros((THUMB_H, THUMB_W, 3), dtype=np.uint8)
        for url in streams
    }

    try:
        while True:
            thumbs = []
            for url in streams:
                q = queues[url]
                if not q.empty():
                    frame = q.get()
                    thumb = cv2.resize(frame, (THUMB_W, THUMB_H),
                                       interpolation=cv2.INTER_AREA)
                    last_thumbs[url] = thumb
                thumbs.append(last_thumbs[url])

            # build mosaic canvas
            mosaic = np.zeros((THUMB_H * rows, THUMB_W * cols, 3),
                              dtype=np.uint8)
            for idx, thumb in enumerate(thumbs):
                r, c = divmod(idx, cols)
                y0, x0 = r * THUMB_H, c * THUMB_W
                mosaic[y0:y0 + THUMB_H, x0:x0 + THUMB_W] = thumb

            cv2.imshow("Detection-Recognition Parallel Pipeline", mosaic)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

            time.sleep(0.01)
    finally:
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
```

**Comment by hamzaziizzz** [comment]
I was able to resolve the issue by replacing `pycuda.autoinit` with `cuda.init()` and replacing `execute_async_v3` with `execute_v2`
