### ISSUE TITLE
it occur Cudnn Error when i run the examples in TRT

### ISSUE THREAD

**Issue by jlygit** [NVIDIA/TensorRT#51]
hello,
```c
&&&& RUNNING TensorRT.sample_uff_mnist # ./sample_uff_mnist
[I] ../../../data/mnist/lenet5.uff
[E] [TRT] cuda/cudaConvolutionLayer.cpp (238) - Cudnn Error in execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)
[E] [TRT] cuda/cudaConvolutionLayer.cpp (238) - Cudnn Error in execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)
[E] Unable to create engine
[E] Model load failed
&&&& FAILED TensorRT.sample_uff_mnist # ./sample_uff_mnist
```

it happen a cudnn error just as above when i run the examples in tesla T4 device.
GPU type - Tesla T4
CUDA version -9.0, V9.0.176
CUDNN version - 7.5.0
TRT version - 5.1.5.0

what it heppen?

thks

**Comment by PeterHuang2015** [comment]
Hi @jlygit , I'm afraid CUDA 9&combined could not support `future product` when it's published, you may upgrade to CUDA 10 to enjoy T4:https://devblogs.nvidia.com/cuda-10-features-revealed/, for convenience, you may prefer https://ngc.nvidia.com/ (pull the corresponding TensorRT docker)as if nvidia-docker got installed to set developers free from configuring dev environment.

**Comment by guods** [comment]
the speed of detection  on Tesla T4 is ? I test the int8 engine on T4 , the speed is 90ms, it is very poor.

**Comment by z13974509906** [comment]
@jlygit have you solve it? I have the same issue

**Comment by jlygit** [comment]
> @jlygit have you solve it? I have the same issue

it solve by upgrade to CUDA 10

**Comment by rtrobin** [comment]
Hi @pmixer @rmccorm4 ,

I have met a similar problem. I have a docker image with environments list below:
Driver version = 440.33.01
CUDA version = 9.0.176
CUDNN version = 7.6.3.30
TRT version = 7.0.0
python = 3.6.5
pyTorch = 1.4.0

The model can be parsed correctly on V100. However it meets error on T4. 
```
[E] [TRT] ../rtSafe/cuda/cudaConvolutionRunner.cpp (362) - Cudnn Error in execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)
```

I'm not sure which part is incompatible? My TRT7 is built on CUDA9. It already works on V100. But why failed on T4 with cuda10.2 driver.

**Comment by pmixer** [comment]
@rtrobin pls update your CUDA, for the same reason that older version of SW(CUDA) cannot support newer HW(T4 is newer than V100).

**Comment by rtrobin** [comment]
@pmixer As far as I know, CUDA application is backward compatible. Older application can still work on new hardware. So my question is, which part is incompatible? Is TRT library that not supports T4?

**Comment by rtrobin** [comment]
Oh I get it. T4 is based on Turing architecture. Turing doesn't support cuda9 any more...

**Comment by pmixer** [comment]
> Oh I get it. T4 is based on Turing architecture. Turing doesn't support cuda9 any more...

哥们咱可以说中文hhh，向后兼容是有的，比如你拿老软件跑在新硬件上只用 FP32 这样的老特性，一般是能跑的，但这样新硬件就完全没意义了。。。CUDA 9 出来的时候 T4 还没影呢，TRT 是以最大化利用最新硬件能力为目标的，必然会 hard-code 一些新硬件相关的东西，拿老 CUDA 配 T4 多多少少都会有问题。所以升级就好，祝顺利 :)

**Comment by rtrobin** [comment]
> > Oh I get it. T4 is based on Turing architecture. Turing doesn't support cuda9 any more...
> 
> 哥们咱可以说中文hhh，向后兼容是有的，比如你拿老软件跑在新硬件上只用 FP32 这样的老特性，一般是能跑的，但这样新硬件就完全没意义了。。。CUDA 9 出来的时候 T4 还没影呢，TRT 是以最大化利用最新硬件能力为目标的，必然会 hard-code 一些新硬件相关的东西，拿老 CUDA 配 T4 多多少少都会有问题。所以升级就好，祝顺利 :)

哈哈我懂。我忘记T4是图灵架构了，我也没想到图灵架构就已经弃掉cuda9。主要问题是，我是在帮别人的忙，他是否愿意升级相关代码，得看他个人意愿了

**Comment by pmixer** [comment]
@rtrobin 明白，hhh，版本适配永远有坑，相比于本机升级，可能装完 docker 再装 nvidia-docker 最后去 ngc pull 一波现成镜像更好些，这样本机只需要维护个 driver 就好了。另外，也不能叫  T4 抛弃 CUDA 9。。。一般只有 SW 选择抛弃 HW，没有 HW 抛弃 SW 一说。要用新发的硬件必须用跟随硬件一同发布或更后面发布的 CUDA 才可以。祝好～
