### ISSUE TITLE
occured OOM while using trtexe  convert onnx model to trt7

### ISSUE THREAD

**Issue by mdztravelling** [NVIDIA/TensorRT#512]
## Description

```
[04/26/2020-21:56:49] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[04/26/2020-21:56:49] [W] [TRT] GPU memory allocation error during timeReformat.
[04/26/2020-21:56:49] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[04/26/2020-21:56:49] [W] [TRT] GPU memory allocation error during timeReformat.
[04/26/2020-21:56:49] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[04/26/2020-21:56:49] [W] [TRT] GPU memory allocation error during timeReformat.
[04/26/2020-21:56:49] [E] [TRT] ../builder/cudnnBuilderUtils.cpp (360) - Cuda Error in findFastestTactic: 2 (out of memory)
[04/26/2020-21:56:49] [W] [TRT] GPU memory allocation error during timeReformat.
[04/26/2020-21:56:51] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[04/26/2020-21:56:51] [W] [TRT] GPU memory allocation error during getBestTactic: (Unnamed Layer* 189) [ElementWise]
[04/26/2020-21:56:51] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[04/26/2020-21:56:51] [W] [TRT] GPU memory allocation error during timeReformat.
[04/26/2020-21:56:51] [E] [TRT] ../builder/cudnnBuilderUtils.cpp (360) - Cuda Error in findFastestTactic: 2 (out of memory)
[04/26/2020-21:56:51] [W] [TRT] GPU memory allocation error during getBestTactic: (Unnamed Layer* 204) [Softmax]
[04/26/2020-21:56:51] [E] [TRT] Internal error: could not find any implementation for node (Unnamed Layer* 204) [Softmax], try increasing the workspace size with IBuilder::setMaxWorkspaceSize()
[04/26/2020-21:56:51] [E] [TRT] ../builder/tacticOptimizer.cpp (1523) - OutOfMemory Error in computeCosts: 0
[04/26/2020-21:56:51] [E] Engine creation failed
[04/26/2020-21:56:51] [E] Engine set up failed

```
Occured OOM when i use trtext convert onnx model to trt, and --workspace=6800 (MB),  and my command as bellow: 
```
/home/work/TensorRT-7.0.0.11/bin/trtexec  --onnx=${onnx_model} \
    --workspace=6800 \
    --explicitBatch \
    --minShapes=input0:1x1,input1:1x1x256,input2:1x1x1x1,input3:1x1x256,input4:1x1x1,output:1x6532 \
    --optShapes=input0:2x10,input1:2x512x256,input2:2x1x10x10,input3:2x10x256,input4:2x1x10,output:2x6532 \
    --maxShapes=input0:4x50,input1:4x1024x256,input2:4x1x50x50,input3:4x50x256,input4:4x1x50,output:4x6532 \
    --saveEngine=${save_trt_model} \
    --buildOnly
```
how to resolve this problem?  And the size of onnx model only 56MB. 
## Environment

**TensorRT Version**:  TensorRT-7.0.0.11
**GPU Type**:  Tesla P4
**Nvidia Driver Version**:   440.33.01
**CUDA Version**:  10.2
**CUDNN Version**:  7.6
**Operating System + Version**:  CentOS release 6.3
**Python Version (if applicable)**:  3.6.5
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**:  1.3
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi,

I can't reproduce this without your ONNX model. Please share the model so I can better help.

Also, did you try reducing the workspace size?

**Comment by jiarenyf** [comment]
Having the same problem ...

**Comment by zzzzwj** [comment]
Meet the same problem with 5.6M Pytorch-EDSR model. I've tried multi optimization profiles and found that with maximum input shape of 1x3x250x250 the engine build procedure consumes at least 8GB GPU memory, however in pytorch, it consumes less than 1GB to infer. My CUDA version is 10.2, TensorRT is 7.0.0.11. All experiments are run on an 1080Ti GPU. Is there any update upon this issue?

**Comment by ttyio** [comment]
@mdztravelling @jiarenyf @zzzzwj , thanks for reporting 

could you try @rmccorm4 's suggestion:
- upgrade to TRT 7.2
- reduce the workspace size

If you still see the failure, could you share the model? thanks

**Comment by zzzzwj** [comment]
> @mdztravelling @jiarenyf @zzzzwj , thanks for reporting
> 
> could you try @rmccorm4 's suggestion:
> 
> * upgrade to TRT 7.2
> * reduce the workspace size
> 
> If you still see the failure, could you share the model? thanks

Oh, sorry for not replying in time. I think I have fixed my problem. I found that the configuration item OptProfileSelector::kMAX decides the maximum GPU memory usage, not the OptProfileSelector::kOPT. So I just set the configuration properly and now it works. Thanks a lot for your reply.

**Comment by ttyio** [comment]
Thanks @zzzzwj , closing

**Comment by Luizerko** [comment]
@zzzzwj, I think I have the same issue and I feel like you might be able to help me.

Can you please describe your solution a little better? Where can I find this configuration item?

Thanks a lot in advance!
