### ISSUE TITLE
Cuda Error in free: 29(driver shutting down)

### ISSUE THREAD

**Issue by VCBE123** [NVIDIA/TensorRT#516]
[04/28/2020-12:13:12] [E] [TRT] ../rtExt/cuda/cudaFusedConvActRunner.cpp (97) - Cuda Error in destroyFilterTexture: 29 (driver shutting foen)

[04/28/2020-12:13:12] [E] [TRT] INTERNAL_ERROR: std::exception
[04/28/2020-12:13:12] [E] [TRT] ../rtSafe/safeRuntime.cpp (32)- Cuda Error in free: 29 (driver shutting down)terminate called after throwing an instance of 'nvinfer1::CudaError'  what(

**Comment by rmccorm4** [comment]
Hi,

Please share all of the requested environment info, and also share the script/model that can reproduce this issue. Might just be a mismatch of driver/cuda/tensorrt versions, etc.

**Comment by VCBE123** [comment]
The error occurs when I create the Engine with:
```c++
mEngine=std::shared_ptr<nvinfer1::IcudaEngine>(mRuntime->deserializeCudaEngine(data.data(),data.length(),nullptr),samplecommon::InferDeleter());
```
I solved this issue by removing the **object->destroy()** in InferDeleter().
