### ISSUE TITLE
No package python-libnvinfer available

### ISSUE THREAD

**Issue by czs1886** [NVIDIA/TensorRT#552]
When I'm installing nvinfer package for Centos(release 7.8.2003) with yum, it says 'No package python-libnvinfer available'. Is libnvinfer still available for Centos?

**Comment by rmccorm4** [comment]
Hi,

Please try following the instructions from scratch again here: https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-700/tensorrt-install-guide/index.html#installing-rpm

If it still doesn't work, please share:
1. All requested environment info in issue template
2. The commands you ran
3. The errors/outputs you received from each command

**Comment by czs1886** [comment]
> Hi,
> 
> Please try following the instructions from scratch again here: https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-700/tensorrt-install-guide/index.html#installing-rpm
> 
> If it still doesn't work, please share:
> 
> 1. All requested environment info in issue template
> 2. The commands you ran
> 3. The errors/outputs you received from each command

Thanks, it solves the issue.
BTW, if I choose the rpm installation, is the version compatible with the lib files from the tar file?
The files I'm using are:
rpm file: nv-tensorrt-repo-rhel7-cuda10.1-trt6.0.1.5-ga-20190913-1-1.x86_64.rpm
tar file: TensorRT-6.0.1.5.CentOS-7.6.x86_64-gnu.cuda-10.1.cudnn7.6.tar.gz

Best

**Comment by rmccorm4** [comment]
> BTW, if I choose the rpm installation, is the version compatible with the lib files from the tar file?

Sorry, I don't know off the top of my head. You'll have to try it out. Please report back your findings if you do 🙂

**Comment by czs1886** [comment]
nv-tensorrt-repo-rhel7-cuda10.1-trt5.1.5.0-ga-20190427-1-1.x86_64.rpm and TensorRT-5.1.5.0.Red-Hat.x86_64-gnu.cuda-10.1.cudnn7.5.tar.gz is compatible here.
