### ISSUE TITLE
TensorRT 7.1 on Jetson doesn't support ResizeBilinear from TensorFlow 1.15.2 converted by ONNX opset 11.

### ISSUE THREAD

**Issue by VincentCheng24** [NVIDIA/TensorRT#596]
## Description

**TensorRT 7.1** on **Jetson AGX Xavier** generates the wrong results of  the node converted from an ONNX `Resize` op (from **opset 11**) which is converted from a ` tf.image.resize_bilinear` node TensorFlow frozen graph.  

I'm converting [SuperPoint](https://github.com/rpautrat/SuperPoint) model into TensorRT. TensorFlow and ONNX inference generate identical inference results, while TensorRT outputs different `superpoint/descriptors` results from both TensorFlow and ONNX. After diagnosis node by node, I find the problem results from the mapping from the ONNX `Resize` op to the TensorRT operation and the ONNX `Resize` op comes from the ` tf.image.resize_bilinear` node.

![onnx_res](https://user-images.githubusercontent.com/26574998/83965705-ebfd1480-a8b5-11ea-8a71-86089eb1aa8a.png)

## Environment

**TensorRT Version**: 7.1 with Jetpack 4.4
**GPU Type**:  512-core Volta GPU with Tensor Cores (Jetson AGX Xavier)
**Nvidia Driver Version**: Jetpack 4.4 (L4T 32.4.2)
**CUDA Version**: 10.2
**CUDNN Version**: 8.0
**Operating System + Version**: Jetpack 4.4 (Costimized Ubuntu 18.04)
**Python Version (if applicable)**: 3.6
**TensorFlow Version (if applicable)**: 1.15.2 
**tf2onnx Version (if applicable)**: 1.5.6 
**ONNXRUNTIME Version**: 1.3.0

## Relevant Files

[SuperPoint repo](https://github.com/rpautrat/SuperPoint)
[onnx model and TF frozen graph](https://drive.google.com/drive/folders/1fTm1BO7HQvyIAMBmd11Yi8dzyMOa0nfW?usp=sharing)

**Comment by chiehpower** [comment]
Hi @VincentCheng24, 

I am sorry that I wonder ask a question which is irrelevant with your question.
My question is:
How did you install the OnnxRuntime `v1.3.0` on AGX with JetPack `v4.4`?
As I knew, Onnxruntime official instruction was using the branch v1.1.2 to build from source.

Thank you in advance.

**Comment by VincentCheng24** [comment]
Hi @chiehpower,
Glad to share it.
The `OnnxRuntime v1.3.0` was installed by `pip install onnxruntime` in a virtual environment created by `virtualenv`. I didn't try to build from source as `pip` worked well and no error showed up during installation and inference.

**Comment by chiehpower** [comment]
> Hi @chiehpower,
> Glad to share it.
> The `OnnxRuntime v1.3.0` was installed by `pip install onnxruntime` in a virtual environment created by `virtualenv`. I didn't try to build from source as `pip` worked well and no error showed up during installation and inference.

Hi @VincentCheng24,

Thanks for your reply!
It is a little bit tricky that as the AGX is ARM architecture, so it should be requested to build from source. (cannot support directly to install by `pip`)

And my environment is as same as what yours. (I was also installing JetPack 4.4 on AGX.)

Here is my command:
```
$ sudo -H python3 -m pip install onnxruntime-gpu                                                                                         
```
Terminal Output:
```
Collecting onnxruntime-gpu
  Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: )
No matching distribution found for onnxruntime-gpu
```
so I guess that you were installing on Desktop, was it? Or is your meaning that you created a virtual environment on AGX, and installed `onnxruntime` by `pip` on AGX?

I will be grateful if you could share me any information. 

BTW as your problem, my experience is that sometimes I met the ops issues and I can fix it by other different `opset` version. So you can try to use other version that you might be able to fix the problem. 
  
Thank you again!

**Comment by HaoLiuHust** [comment]
where did you download tensorrt7.1?

**Comment by chiehpower** [comment]
> where did you download tensorrt7.1?

The default TensorRT version on JetPack 4.4 is `7.1.0.16`.
And I already checked that NVIDIA (TensorRT) official website haven't update yet.

**Comment by HaoLiuHust** [comment]
I see... I am still waiting their update because of a gpu memory leak

**Comment by VincentCheng24** [comment]
Hi @chiehpower,
Sorry for the late reply.

I installed all the python packages in a virtual environment.  I had the same problem as you had when installing `onnxruntime-gpu`. Thus, I installed `onnxruntime` rather than `onnxruntime-gpu`. I only use `onnxruntime` to validate the tf2onnx conversion, so CPU version is enough.

And I also had some doubt about the compatibility between different architectures. So I compared  the inference results, one from Jetson and the other from the local PC, and they were identical, which helped resolve the concern.

Thanks for you suggestion of trying other `opset`. I already tried them but all led to failure. 

My current workaround is converting part of the model supported by TensorRT and using TF to deal with operations from the other part.

**Comment by chiehpower** [comment]
> Hi @chiehpower,
> Sorry for the late reply.
> 
> I installed all the python packages in a virtual environment. I had the same problem as you had when installing `onnxruntime-gpu`. Thus, I installed `onnxruntime` rather than `onnxruntime-gpu`. I only use `onnxruntime` to validate the tf2onnx conversion, so CPU version is enough.
> 
> And I also had some doubt about the compatibility between different architectures. So I compared the inference results, one from Jetson and the other from the local PC, and they were identical, which helped resolve the concern.
> 
> Thanks for you suggestion of trying other `opset`. I already tried them but all led to failure.
> 
> My current workaround is converting part of the model supported by TensorRT and using TF to deal with operations from the other part.

Hi @VincentCheng24,

Got it.
Thanks for your reply and sharing!
I can understand what you did, and I already resolved the issue of building onnxruntime-gpu from source! 
So that's not a problem now!

BR,
Chieh

**Comment by VincentCheng24** [comment]
Hi @chiehpower,
No problem. Glad to know that your problem has been solved.

**Comment by ttyio** [comment]
Hello @VincentCheng24 , thanks for reporting.
Yes we aware the gap between onnx and onnx-trt for resize operator. 

https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L2599

We internally working on closing the gap for the next major release, before that, you have to workaround this by experiment different setting of `align_corners = 0` and `half_pixel = 1`. thanks!

**Comment by ttyio** [comment]
I will close this, please reopen if you still have question, thanks!
