### ISSUE TITLE
Serializing engine of dynamic input shape costs too much GPU memory

### ISSUE THREAD

**Issue by TerryBryant** [NVIDIA/TensorRT#638]
## Description
My original model is a image super resolution model, which can take a 2048x2048 image and return a 4096x4096 image on my Tesla P40 card. Then I migrate it to tensorrt of dynamic input shape with the following command
```
TensorRT-7.0.0.11/targets/x86_64-linux-gnu/bin/trtexec --explicitBatch --onnx=dynamic.onnx \
--minShapes=input:1x3x10x10 \
--optShapes=input:1x3x1024x1024 \
--maxShapes=input:1x3x1224x1224 \
--calib=calib.cache \
--workspace=20000 \
--fp16 \
--int8 \
--saveEngine=dynamic.int8.engine
``` 
Error happens as follows
```
[TensorRT] ERROR: ../builder/cudnnBuilderUtils.cpp (360) - Cuda Error in findFastestTactic: 2 (out of memory)
[TensorRT] ERROR: Internal error: could not find any implementation for node (Unnamed Layer* 49) [Shuffle], try increasing the workspace size with IBuilder::setMaxWorkspaceSize()
[TensorRT] ERROR: ../builder/tacticOptimizer.cpp (1523) - OutOfMemory Error in computeCosts: 0
```
I search the error, and find this happens due to the lack of workspace size, so I have to reduce the min, opt, max shapes, then I can serialize the engine. Now when I use this engine to do the inferece, I can only feed a less than 1024x1024 image, which is quiet inconvenient. Is this a bug or something?

## Environment

**TensorRT Version**: 7.0.0
**GPU Type**: Tesla P40
**Nvidia Driver Version**: 418.67
**CUDA Version**: 10.1
**CUDNN Version**: 7603
**Operating System + Version**: CentOS Linux release 7.5.1804
**Python Version (if applicable)**: 3.6.5
**TensorFlow Version (if applicable)**: None
**PyTorch Version (if applicable)**: 1.4.0
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files
[dynamic.onnx](https://drive.google.com/file/d/1L_spe4vZFBAq6tHlgnvGxXTAZ5x1LKf6/view?usp=sharing)
[calib.cache](https://drive.google.com/file/d/1yf4fSrbChCN-a7e4cXk1iVdVmlv2KYR8/view?usp=sharing)

**Comment by rmccorm4** [comment]
Hi @TerryBryant ,

I don't think this model is actually using too much memory, I believe this was a known issue with TensorRT 7.0 + INT8 Calibration + Dynamic Shapes. I recommend upgrading to TensorRT 7.1 (just released a few days ago) and trying again, I believe it should be fixed now. 

This is essentially a duplicate of https://github.com/NVIDIA/TensorRT/issues/289, so I'll close this for now. Feel free to let us know if you still have issues after upgrading to TensorRT 7.1

**Comment by TerryBryant** [comment]
@rmccorm4 after upgrade to tensort7.1, this problem fixed, thanks a lot!
