### ISSUE TITLE
Deserializing model results in segmentation fault

### ISSUE THREAD

**Issue by Bidski** [NVIDIA/TensorRT#786]
## Description

I serialise a model using

```
std::ofstream ofs(engine_file, std::ios::out | std::ios::binary);
std::shared_ptr<nvinfer1::IHostMemory> serialised_model(engine->serialize(),
    [](nvinfer1::IHostMemory* ptr) {
        if (ptr) {
            ptr->destroy();
        }
    });
ofs.write(reinterpret_cast<char*>(serialised_model->data()), serialised_model->size());
ofs.close();
```

and then deserialize it using

```
initLibNvInferPlugins(&logger.getTRTLogger(), "");

auto runtime = std::shared_ptr<nvinfer1::IRuntime> 
    nvinfer1::createInferRuntime(logger.getTRTLogger()),
        [](nvinfer1::IRuntime* ptr) {
            if (ptr) {
                ptr->destroy();
            }
        });

if (!runtime) {
    throw std::runtime_error("Failed to create TensorRT inference runtime");
}

std::string engine_data = loadFromFile(engine_file);
engine                  = std::shared_ptr<nvinfer1::ICudaEngine>(
                    runtime->deserializeCudaEngine(engine_data.data(), engine_data.size(), nullptr),
    [](nvinfer1::ICudaEngine* ptr) {
        if (ptr) {
             ptr->destroy();
        }
    });

if (!engine) {
    throw std::runtime_error("TensorRT inference runtime failed to deserialise engine");
}
```

When I use the deserialized engine and allocate a buffer using the [BufferManager](https://github.com/NVIDIA/TensorRT/blob/master/samples/common/buffers.h#L236) class, I get a segmentation fault when trying to copy data to the input buffer.

```
std::vector<uint8_t> image;

/// populate image vector

BufferManager managed_buffer(engine, 1, context.get());

float* host_data = static_cast<float*> managed_buffer.getHostBuffer(config.input_tensors[0]));

std::transform(image.begin(), image.end(), host_data,
    [](const uint8_t& val) { return (2.0f / 255.0f) * float(val) - 1.0f; });
```

However, if I build the engine from a UFF file (same as [this procedure](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffSSD/sampleUffSSD.cpp#L124-L165)) the data transfer to the input buffer succeeds without issue.

The serialized engine is being deserialized on the same machine that serialized it.

Deserialization and inference are happening in separate threads.

When using the engine built from the UFF model, engine creation and inference are also run in separate threads.

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: GeForce GTX 1080
**Nvidia Driver Version**: 440.82
**CUDA Version**: 10.2
**CUDNN Version**: 7.6
**Operating System + Version**: Arch Linux, kernel version 5.6.10-arch1-1
**Python Version (if applicable)**: N/A
**TensorFlow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**:  N/A
**Baremetal or Container (which commit + image + tag)**: Baremetal

## Relevant Files

UFF file is generated from the samples (SampleUffSSD) provided in TensorRT 7.0.0.11

## Steps To Reproduce

1. Load UFF model and build the engine following the procedure in [SampleUffSSD](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffSSD/sampleUffSSD.cpp#L124-L165)
2. Serialize the built engine using the above code
3. Deserialize the engine using the above code
4. Run inference on the deserialized engine, as per SampleUffSSD. Perform deserialization and inference in separate threads (not sure if this is pertinent to reproducing the error).

**Comment by coolbei** [comment]
how you solve it

**Comment by Bidski** [comment]
@coolbei it turned out that I wasn't correctly setting the variable that I used to store the input dimensions which resulted in allocating the wrong amount of memory
