### ISSUE TITLE
Installing TensorRT on docker |  Depends: libnvinfer7 (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed

### ISSUE THREAD

**Issue by ashuezy** [NVIDIA/TensorRT#792]
## Description

My base system is ubuntu 18.04 with nvidia-driver. **I just installed the driver and it is showing cuda 11.**
While installing TensorRT in the docker it is showing me this error. I haven't installed any drivers in the docker image.

```
root@b2f8be4565fe:/home/asd/Downloads/docker_folder# apt-get install tensorrt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tensorrt : Depends: libnvinfer7 (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvinfer-plugin7 (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvparsers7 (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvonnxparsers7 (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvinfer-bin (= 7.1.3-1+cuda10.2) but it is not going to be installed
            Depends: libnvinfer-dev (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvinfer-plugin-dev (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvparsers-dev (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvonnxparsers-dev (= 7.1.3-1+cuda10.2) but 7.2.0-1+cuda11.0 is to be installed
            Depends: libnvinfer-samples (= 7.1.3-1+cuda10.2) but it is not going to be installed
            Depends: libnvinfer-doc (= 7.1.3-1+cuda10.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0

Details about the docker
docker pull nvidia/cuda:10.2-devel-ubuntu18.04
dpkg -i libcudnn8_8.0.3.33-1+cuda10.2_amd64.deb
dpkg -i libcudnn8-dev_8.0.3.33-1+cuda10.2_amd64.deb

## Environment

**TensorRT Version**: 7.1.3
**GPU Type**: 1050 TI
**Nvidia Driver Version**: 450.66
**CUDA Version**:  10.2
**CUDNN Version**:  8.0.3
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: N/Aa
**TensorFlow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**: N/
**Baremetal or Container (which commit + image + tag)**: N/A

## Steps To Reproduce
apt-get install tensorrt

**Comment by ashuezy** [comment]
Can you provide support Nvidia ?
We are stuck on our deployment for a very important client of ours.
TensorRT seems to taking cuda versions for the base machine instead of the docker for which it is installed.

**Comment by tamisalex** [comment]
I am also experiencing this issue. Trying to get deepstream 5 and TensorRT 7.1.3.4 in a docker container and I came across this issue.

**Comment by Rapternmn** [comment]
@tamisalex were you able to build this system?
Deepstream + TRT 7.1?

**Comment by tamisalex** [comment]
I abandoned trying to install inside a docker container.

**Comment by huanga2** [comment]
I found that the CUDA docker image have an additional PPA repo registered `/etc/apt/sources.list.d/nvidia-ml.list`. This seems to overshadow the specific file deb repo with the cuda11.0 version of libnvinfer7.

I just added a line to delete `nvidia-ml.list` and it seems to install TensorRT 7.0 on CUDA 10.0 fine. I am not sure on the long term effects though, as my native Ubuntu install does not have `nvidia-ml.list` anyway.

**Comment by mk-nvidia** [comment]
This is documented on the official TensorRT docs page.
I was able to follow these instructions to install TensorRT 7.1.3 in the cuda10.2 container in @ashuezy 's original post. You would probably only need steps 2 and 4 since you're already using a CUDA container:

https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#maclearn-net-repo-install-rpm

**Comment by khanhha** [comment]
We have the same problem as well.
 - Cuda 11.0.2
 - Cudnn 8.0 
 - TensorRT 7.2

**Comment by gmt710** [comment]
https://blog.csdn.net/qq_35975447/article/details/115632742

It may helps.

**Comment by hungvm2** [comment]
> I found that the CUDA docker image have an additional PPA repo registered `/etc/apt/sources.list.d/nvidia-ml.list`. This seems to overshadow the specific file deb repo with the cuda11.0 version of libnvinfer7.
> 
> I just added a line to delete `nvidia-ml.list` and it seems to install TensorRT 7.0 on CUDA 10.0 fine. I am not sure on the long term effects though, as my native Ubuntu install does not have `nvidia-ml.list` anyway.

For someone tried this approach yet the problem didn't get solved, it seems like there are more than one place storing nvidia deb-src links (https://developer.download.nvidia.com/compute/*) and these links overshadowed actual deb link of dependencies corresponding with your tensorrt version. 
Just comment out these links in every possible place inside /etc/apt directory at your system (for instance: /etc/apt/sources.list , /etc/apt/sources.list.d/cuda.list , /etc/apt/sources.list.d/nvidia-ml.list (except your nv-tensorrt deb-src link)) before run "apt install tensorrt" then everything works like a charm (uncomment these links after installation completes).
