### ISSUE TITLE
8 bit quantization calibrator error

### ISSUE THREAD

**Issue by justinblaber** [NVIDIA/TensorRT#815]
## Description

I've implemented the `trt.IInt8EntropyCalibrator2` as so:

```
class Int8Calibrator(trt.IInt8EntropyCalibrator2):
    def __init__(self, files_batch):
        super().__init__()
        self.files_batch = files_batch
        self.count = 0
        self.buf_h = cuda.pagelocked_empty(384*512, dtype=np.float32)
        self.buf_d = cuda.mem_alloc(self.buf_h.nbytes)
    
    def read_calibration_cache(self, *args, **kwargs): 
        return None
    
    def write_calibration_cache(self, cache, *args, **kwargs):
        pass
    
    def get_batch_size(self): 
        return 1
    
    def get_batch(self, *args, **kwargs): 
        if self.count < len(self.files_batch):
            with open(self.files_batch[self.count], 'rb') as f:
                f.readinto(self.buf_h)
            cuda.memcpy_htod_async(self.buf_d, self.buf_h)
            self.count += 1
            return [int(self.buf_d)]
        else:
            return []
```

```
calibrator_int8 = Int8Calibrator([Path('batches/X0.raw')])
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
builder = trt.Builder(TRT_LOGGER)
network = builder.create_network(EXPLICIT_BATCH)
parser = trt.OnnxParser(network, TRT_LOGGER)
parser.parse_from_file('model.onnx')
config = builder.create_builder_config()
config.max_workspace_size = 1 << 30
config.set_flag(trt.BuilderFlag.INT8)
config.int8_calibrator = calibrator_int8
engine = builder.build_engine(network, config)
```

Terminal output shows:

```
[TensorRT] INFO: Starting Calibration.
[TensorRT] ERROR: ../rtExt/cuda/calibrator.cu (105) - Cuda Error in absTensorMax: 9 (invalid configuration argument)
[TensorRT] ERROR: ../rtExt/cuda/calibrator.cu (105) - Cuda Error in absTensorMax: 9 (invalid configuration argument)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
[TensorRT] ERROR: ../rtExt/cuda/calibrator.cu (105) - Cuda Error in absTensorMax: 9 (invalid configuration argument)
[TensorRT] ERROR: ../rtExt/cuda/calibrator.cu (105) - Cuda Error in absTensorMax: 9 (invalid configuration argument)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
[TensorRT] ERROR: ../rtExt/cuda/calibrator.cu (105) - Cuda Error in absTensorMax: 9 (invalid configuration argument)
[TensorRT] ERROR: ../rtExt/cuda/calibrator.cu (105) - Cuda Error in absTensorMax: 9 (invalid configuration argument)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
[TensorRT] INFO:   Calibrated batch 0 in 0.127317 seconds.
```

The strange thing is it appears to actually convert it to int8. I've nvprof'd the resulting engine and it is using int8 instructions. But the errors are concerning.

## Environment

**TensorRT Version**:  TensorRT-7.2.0.14
**GPU Type**: 2070 Max-Q
**Nvidia Driver Version**:  450.51.06
**CUDA Version**: 11.0 (update 1)
**CUDNN Version**: 8.0.2
**Operating System + Version**: ubuntu 18.04
**Python Version (if applicable)**: 3.7.7
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**:  1.7.0
**Baremetal or Container (which commit + image + tag)**:

**Comment by ttyio** [comment]
Hello @justinblaber , thanks for reporting the issue.

The error come from the calibration stage when TensorRT collect data statistics from intermediate tensors, the error will result some inaccuracy dynamic range is generated, or some layer fallback to `fp32` precision due to lack of `int8` dynamic range. So even with this error, when you check your engine, you can still see model partially run in `int8` precision.

From the error symptom `invalid configuration argument`, usually it means we are trying to launch a kernel exceed the hardware limitation (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications). 

For better triage, is it possible to share the `model.onnx`? Thanks!

**Comment by ttyio** [comment]
Sorry I will close this issue since get no response for more than 2 weeks, please reopen if you still have question, thanks!

**Comment by cocoyen1995** [comment]
Hi @ttyio ,

I'm facing the same issue with @justinblaber.
Could you please take a look for me if possible?
The error message of calibration with int8 shows like this:

```
[01/04/2021-16:00:28] [W] [TRT] Explicit batch network detected and batch size specified, use execute without batch size instead.
[01/04/2021-16:00:28] [E] [TRT] C:/source/rtExt/cuda/calibrator.cu (106) - Cuda Error in cuCalibrator::absTensorMax: 11 (invalid argument)
[01/04/2021-16:00:28] [E] [TRT] FAILED_ALLOCATION: Unknown exception
[01/04/2021-16:00:28] [E] [TRT] C:/source/rtSafe/cuda/genericReformat.cu (1262) - Cuda Error in genericReformat::executeMemcpy: 11 (invalid argument)
[01/04/2021-16:00:28] [E] [TRT] FAILED_EXECUTION: Unknown exception
[01/04/2021-16:00:28] [I] [TRT]   Calibrated batch 26 in 0.0038049 seconds.
[01/04/2021-16:00:28] [I] [TRT]   Post Processing Calibration data in 0.0420402 seconds.
[01/04/2021-16:00:28] [I] [TRT] Calibration completed in 21.0442 seconds.
[01/04/2021-16:00:28] [I] [TRT] Writing Calibration Cache for calibrator: TRT-7000-EntropyCalibration

```
with some additional warning shows afterwards:
(Seems like some layers in the model)
```
[01/04/2021-16:00:28] [W] [TRT] Missing dynamic range for tensor input_1_1:01, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[01/04/2021-16:00:28] [W] [TRT] Missing dynamic range for tensor adjusted_input7, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[01/04/2021-16:00:28] [W] [TRT] Missing dynamic range for tensor conv2d_1_1/Relu:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[01/04/2021-16:00:28] [W] [TRT] Missing dynamic range for tensor batch_norm_output_buffer4, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[01/04/2021-16:00:28] [W] [TRT] Missing dynamic range for tensor conv2d_2_1/Relu:0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
......
```

The engine file still generated successfully, and inference faster than the one generated with fp16.
Here are some info about the onnx file:
```
Input filename:   ./sys/model/20210104/resunet1_concate_Transpose_rs1920.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    keras2onnx
Producer version: 1.6.0
Domain:           onnx
Model version:    0
Doc string: 
```
and here's the onnx file if it's needed:
[resunet1_concate_Transpose_rs1920.onnx](https://drive.google.com/file/d/1Xq5Mm9rm7-A2_-YARtdThkkCSH6hIFnm/view?usp=sharing)

The onnx file is saved from keras, and the layers are being reshaped with [this code](https://drive.google.com/file/d/1JKBmcHxFkGrSRkMmdpK3ZxiuZ7z_Ceit/view?usp=sharing)
(Since the size of images are different when training and inferencing)
and it seems the calibration works fine without doing the reshape process...

I'm not sure whether the engine generated in this way work correctly or not,
(The inference result looks exactly the same with fp16's engine, but with faster speed.)

Environment
----------
**TensorRT Version:** TensorRT-7.0.0.11
**GPU Type:** RTX2080 Ti
**Nvidia Driver Version:** 451.82
**CUDA Version**: 10.0
**CUDNN Version**: 7.4.2
**Operating System + Version**: Windows10 1909
**Python Version (if applicable)**: 3.6.8
**TensorFlow Version (if applicable):**1.13.1
**PyTorch Version (if applicable)**: 

P.S.
The reason why I use cuda10 is that, 
for one thing, I build tensorflow with that version; 
for another, some of the GPUs which the model is going to deploy on may not being supported by newer version of driver or cuda.
So I would like to keep the original environment if possible.

**Any help or advice would be appreciated!**  😃

**Comment by ttyio** [comment]
Hello @cocoyen1995 , thanks for reporting.
I tried to run int8 using your model with the same configuration, I find I have to setup 1G workspace to run the FP32 model, and when build INT8 engine using 1G workspace, I get a different out of memory error:

    [01/05/2021-07:08:00] [E] [TRT] C:\source\rtSafe\safeRuntime.cpp (25) - Cuda Error in nvinfer1::internal::DefaultAllocator::allocate: 2 (out of memory)

Could you share me with a minimal repro code since I get different error than you. Or maybe you can try change your model with a smaller input size to see if you also hit the out of memory issue.

**Comment by cocoyen1995** [comment]
Hi @ttyio , thanks for your quick reply!
While rearranging the code I was going to provide you, the errors gone magically...
I haven't look into what's the reason, but I'll update here if I still need your help.
Have a nice day and take care! 👍

**Comment by cocoyen1995** [comment]
Hi @ttyio , sorry to bother again.
I have a question that is not very related to this issue, I'm not sure if it's proper to ask it here 😟 

The question is... **using TensorRT didn't speed up the inference process in my case (resunet).** 
The whole process goes like this:
1. Get resunet model(keras) 480*480
2. Change model input size(keras) 1920*1920
3. Convert model from .h5/.hdf5 to .onnx
4. Convert .onnx to TensorRT (FP16, INT8) engine

After going through the whole process,
it turned out that the inference time with using TensorRT was longer than the one only use with tensorflow
However, if I skip step2 (i.e. inference with its original size),
the inference process was slightly faster as expected.
(But I didn't see huge difference on the inference time between using fp16 and int8)

I've checked the model structure before/after conversion with [netron](https://netron.app/),
but I couldn't see any difference. 😕 
I'm confused what cause this situation, [here's the code and model](https://drive.google.com/file/d/1GK3byyMhf7diYQuMpukzWjHcKHCAfuqY/view?usp=sharing) I use during the process,
**any help or advice would be appreciated, thanks in advance!**


(In case this info is needed, I add it here...)
The whole process inference with tensorflow goes like this:
1. Get resunet model(keras) 480*480
2. Convert model from .h5/.hdf5 to pb
3. Change model input size(tensorflow) 1920*1920
