### ISSUE TITLE
Cuda Error in allocate: 2 (out of memory)

### ISSUE THREAD

**Issue by hadoop2xu** [NVIDIA/TensorRT#840]
I build a network with tensorrt API , when i call "with builder.build_cuda_engine(network) as engine", the follow bug appear .
![image](https://user-images.githubusercontent.com/48076281/96972322-f4927680-1548-11eb-8bd0-3fd6fce739e2.png)
what problem ?

**Comment by ttyio** [comment]
Hello @hadoop2xu , thanks for reporting.
Can you reproduce the error using latest TRT 7.2? If so could you share a repro for better triage, thanks!

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!

**Comment by KleinXin** [comment]
Same Error encountered, any sulotions?

**Comment by Egozjuer** [comment]
> Hello @hadoop2xu , thanks for reporting.
> Can you reproduce the error using latest TRT 7.2? If so could you share a repro for better triage, thanks!

Hi,I was using TensorRT7.2.1.6,and the same error encountered

**Comment by ttyio** [comment]
@KleinXin  @Egozjuer , to solve this out of memory issue, have you tried set a smaller work space, also try run on fp16 precision?

**Comment by Egozjuer** [comment]
@ttyio ,i have tried set a smaller work size ,such as nvinfer1::IBuilderConfig * config;config->setMaxWorkspaceSize(1<<10);
but the same error encountered again

**Comment by Egozjuer** [comment]
also i changed config to fp16 precision

**Comment by Egozjuer** [comment]
@ttyio 

File does not exist : ../configs/yolov3-kHALF-batch64.engine
Building the TensorRT Engine...
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: (Unnamed Layer* 1) [ElementWise]
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: leaky_1
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: leaky_1
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: leaky_1
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during timeReformat.
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: conv_2 + leaky_2
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: conv_2 + leaky_2
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: PWN(leaky_4, shortcut_5)
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: PWN(leaky_4, shortcut_5)
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
WARNING: Get cuda error during getBestTactic: PWN(leaky_4, shortcut_5)
Building complete!
Serializing the TensorRT Engine...
Serialized plan file cached at location : ../configs/yolov3-kHALF-batch64.engine
Loading TRT Engine...
Loading Complete!
ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
ERROR: FAILED_ALLOCATION: std::exception
yolo-trt: ~/GPU/TensorRT/yolo-tensorrt/modules/yolo.cpp:102: Yolo::Yolo(const NetworkInfo&, const InferParams&): Assertion `m_Context != nullptr' failed.
Aborted (core dumped)

**Comment by ttyio** [comment]
@Egozjuer , could you also change your batch size to a smaller number since you hit out of memory in cudaMalloc?

**Comment by KleinXin** [comment]
> @KleinXin @Egozjuer , to solve this out of memory issue, have you tried set a smaller work space, also try run on fp16 precision?

It is already solved. The memory was occupied by some other applications.

**Comment by Egozjuer** [comment]
Yes, I solved the problem as what KleinXin did

**Comment by zhaohb** [comment]
yes,I solved this problem by reduce batchsize

**Comment by deepti-pushpak** [comment]
Hi, I had the same error "Cuda Error in allocate: 2 (out of memory)" with tensorRT version 7.*
I upgraded the tensorRT version to 8.2.3.0, the error got solved and I was able to build the tensorrt engine file.
I suggest you to updgrade tensorrt version to 8.*
